prompt PL/SQL Developer import file
prompt Created on 2013年1月30日 by Administrator
set feedback off
set define off
prompt Dropping STATISTIC_YEAR...
drop table STATISTIC_YEAR cascade constraints;
prompt Creating STATISTIC_YEAR...
create table STATISTIC_YEAR
(
  YEAR                        VARCHAR2(4),
  ID                          VARCHAR2(40) not null,
  MONTH                       VARCHAR2(4) default to_char(sysdate,'MM'),
  REG_ENTERPRISE_NUM          NUMBER(10),
  REG_USER_NUM                NUMBER(10),
  REG_ENTERPRISE_GROWTH       NUMBER(10,6),
  REG_USER_GROWTH             NUMBER(10,6),
  ENTRY_USER_NUM              NUMBER(10),
  ENTRY_USER_TIMES            NUMBER(10),
  ENTRY_COUREHOURS            NUMBER(10),
  FEE_AMOUNT                  NUMBER(10,2),
  ENTRY_USER_GROWTH           NUMBER(10,6),
  ENTRY_USER_TIMES_GROWTH     NUMBER(10,6),
  ENTRY_COUREHOURS_GROWTH     NUMBER(10,6),
  FEE_AMOUNT_GROWTH           NUMBER(10,6),
  REFUND_NUM                  NUMBER(10),
  REFUND_AMOUNT               NUMBER(10,2),
  OVERYEAR_REFUND_NUM         NUMBER(10),
  OVERYEAR_REFUND_AMOUNT      NUMBER(10,2),
  STUDY_BEGIN_TIMES           NUMBER(10),
  STUDY_COMPLETE_TIMES        NUMBER(10),
  STUDY_BEGIN_RATE            NUMBER(10,6),
  STUDY_COMPLETE_RATE         NUMBER(10,6),
  STUDY_BEGIN_TIMES_GROWTH    NUMBER(10,6),
  STUDY_COMPLETE_TIMES_GROWTH NUMBER(10,6),
  TEST_BEGIN_TIMES            NUMBER(10),
  TEST_COMPLETE_TIMES         NUMBER(10),
  TEST_BEGIN_TIMES_GROWTH     NUMBER(10,6),
  TEST_COMPLETE_TIMES_GROWTH  NUMBER(10,6),
  TEST_COMPLETE_RATE          NUMBER(10),
  CREATE_DATE                 DATE default sysdate not null,
  UPDATE_DATE                 DATE,
  REG_ENTERPRISE_COUNT        NUMBER(10),
  REG_USER_COUNT              NUMBER(10),
  OVERYEAR_REFUND_TIMES       NUMBER(10),
  OVERYEAR_REFUND_HOURS       NUMBER(10),
  REFUND_TIMES                NUMBER(10),
  REFUND_HOURS                NUMBER(10,2),
  COM_TEN_HOURS_NUM           NUMBER(10),
  COM_FIFTEEN_HOURS_NUM       NUMBER(10)
)
tablespace HZPH
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 8K
    minextents 1
    maxextents unlimited
  );
comment on table STATISTIC_YEAR
  is '综合统计-年度汇总';
comment on column STATISTIC_YEAR.YEAR
  is '年';
comment on column STATISTIC_YEAR.MONTH
  is '月';
comment on column STATISTIC_YEAR.REG_ENTERPRISE_NUM
  is '注册机构数量';
comment on column STATISTIC_YEAR.REG_USER_NUM
  is '注册人数';
comment on column STATISTIC_YEAR.REG_ENTERPRISE_GROWTH
  is '注册单位数累计同比';
comment on column STATISTIC_YEAR.REG_USER_GROWTH
  is '注册人数累计同比';
comment on column STATISTIC_YEAR.ENTRY_USER_NUM
  is '报名人数';
comment on column STATISTIC_YEAR.ENTRY_USER_TIMES
  is '报名人次';
comment on column STATISTIC_YEAR.ENTRY_COUREHOURS
  is '报名学时数';
comment on column STATISTIC_YEAR.FEE_AMOUNT
  is '付费金额';
comment on column STATISTIC_YEAR.ENTRY_USER_GROWTH
  is '报名人数同比';
comment on column STATISTIC_YEAR.ENTRY_USER_TIMES_GROWTH
  is '报名人次同比';
comment on column STATISTIC_YEAR.ENTRY_COUREHOURS_GROWTH
  is '报名学时数同比';
comment on column STATISTIC_YEAR.FEE_AMOUNT_GROWTH
  is '付费金额同比';
comment on column STATISTIC_YEAR.REFUND_NUM
  is '退费人数';
comment on column STATISTIC_YEAR.REFUND_AMOUNT
  is '退费金额';
comment on column STATISTIC_YEAR.OVERYEAR_REFUND_NUM
  is '跨年退人数';
comment on column STATISTIC_YEAR.OVERYEAR_REFUND_AMOUNT
  is '跨年退金额';
comment on column STATISTIC_YEAR.STUDY_BEGIN_TIMES
  is '开始学习人次';
comment on column STATISTIC_YEAR.STUDY_COMPLETE_TIMES
  is '完成学习人次';
comment on column STATISTIC_YEAR.STUDY_BEGIN_RATE
  is '开始学习比率（%）';
comment on column STATISTIC_YEAR.STUDY_COMPLETE_RATE
  is '学习完成率（%）';
comment on column STATISTIC_YEAR.STUDY_BEGIN_TIMES_GROWTH
  is '开始学习人次同比（%）';
comment on column STATISTIC_YEAR.STUDY_COMPLETE_TIMES_GROWTH
  is '完成学习人次同比（%）';
comment on column STATISTIC_YEAR.TEST_BEGIN_TIMES
  is '开始测验人次';
comment on column STATISTIC_YEAR.TEST_COMPLETE_TIMES
  is '完成测验人次';
comment on column STATISTIC_YEAR.TEST_BEGIN_TIMES_GROWTH
  is '开始测验人次同比（%）';
comment on column STATISTIC_YEAR.TEST_COMPLETE_TIMES_GROWTH
  is '完成测验人次同比（%）';
comment on column STATISTIC_YEAR.TEST_COMPLETE_RATE
  is '测验完成率（%）';
comment on column STATISTIC_YEAR.CREATE_DATE
  is '创建时间';
comment on column STATISTIC_YEAR.UPDATE_DATE
  is '更新时间';
comment on column STATISTIC_YEAR.REG_ENTERPRISE_COUNT
  is '注册机构数量累计';
comment on column STATISTIC_YEAR.REG_USER_COUNT
  is '注册人数累计';
comment on column STATISTIC_YEAR.OVERYEAR_REFUND_TIMES
  is '跨年退人次';
comment on column STATISTIC_YEAR.OVERYEAR_REFUND_HOURS
  is '跨年退学时';
comment on column STATISTIC_YEAR.REFUND_TIMES
  is '退费人次';
comment on column STATISTIC_YEAR.REFUND_HOURS
  is '退费学时';
comment on column STATISTIC_YEAR.COM_TEN_HOURS_NUM
  is '完成10个学时数人数';
comment on column STATISTIC_YEAR.COM_FIFTEEN_HOURS_NUM
  is '完成15个学时数人数';
alter table STATISTIC_YEAR
  add constraint STATI_ID primary key (ID)
  using index 
  tablespace HZPH
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table STATISTIC_YEAR
  add constraint STATI_YEAR unique (YEAR)
  using index 
  tablespace HZPH
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

prompt Disabling triggers for STATISTIC_YEAR...
alter table STATISTIC_YEAR disable all triggers;
prompt Loading STATISTIC_YEAR...
insert into STATISTIC_YEAR (YEAR, ID, MONTH, REG_ENTERPRISE_NUM, REG_USER_NUM, REG_ENTERPRISE_GROWTH, REG_USER_GROWTH, ENTRY_USER_NUM, ENTRY_USER_TIMES, ENTRY_COUREHOURS, FEE_AMOUNT, ENTRY_USER_GROWTH, ENTRY_USER_TIMES_GROWTH, ENTRY_COUREHOURS_GROWTH, FEE_AMOUNT_GROWTH, REFUND_NUM, REFUND_AMOUNT, OVERYEAR_REFUND_NUM, OVERYEAR_REFUND_AMOUNT, STUDY_BEGIN_TIMES, STUDY_COMPLETE_TIMES, STUDY_BEGIN_RATE, STUDY_COMPLETE_RATE, STUDY_BEGIN_TIMES_GROWTH, STUDY_COMPLETE_TIMES_GROWTH, TEST_BEGIN_TIMES, TEST_COMPLETE_TIMES, TEST_BEGIN_TIMES_GROWTH, TEST_COMPLETE_TIMES_GROWTH, TEST_COMPLETE_RATE, CREATE_DATE, UPDATE_DATE, REG_ENTERPRISE_COUNT, REG_USER_COUNT, OVERYEAR_REFUND_TIMES, OVERYEAR_REFUND_HOURS, REFUND_TIMES, REFUND_HOURS, COM_TEN_HOURS_NUM, COM_FIFTEEN_HOURS_NUM)
values ('2008', '1', '01', 163, 72352, null, null, 72968, 513405, 964102, 19282040, null, null, null, null, 21, 17760, null, null, 501382, 497070, null, .9914, null, null, null, null, null, null, null, to_date('16-01-2013 10:58:36', 'dd-mm-yyyy hh24:mi:ss'), null, 163, 72352, null, null, 488, 888, 69217, 38360);
insert into STATISTIC_YEAR (YEAR, ID, MONTH, REG_ENTERPRISE_NUM, REG_USER_NUM, REG_ENTERPRISE_GROWTH, REG_USER_GROWTH, ENTRY_USER_NUM, ENTRY_USER_TIMES, ENTRY_COUREHOURS, FEE_AMOUNT, ENTRY_USER_GROWTH, ENTRY_USER_TIMES_GROWTH, ENTRY_COUREHOURS_GROWTH, FEE_AMOUNT_GROWTH, REFUND_NUM, REFUND_AMOUNT, OVERYEAR_REFUND_NUM, OVERYEAR_REFUND_AMOUNT, STUDY_BEGIN_TIMES, STUDY_COMPLETE_TIMES, STUDY_BEGIN_RATE, STUDY_COMPLETE_RATE, STUDY_BEGIN_TIMES_GROWTH, STUDY_COMPLETE_TIMES_GROWTH, TEST_BEGIN_TIMES, TEST_COMPLETE_TIMES, TEST_BEGIN_TIMES_GROWTH, TEST_COMPLETE_TIMES_GROWTH, TEST_COMPLETE_RATE, CREATE_DATE, UPDATE_DATE, REG_ENTERPRISE_COUNT, REG_USER_COUNT, OVERYEAR_REFUND_TIMES, OVERYEAR_REFUND_HOURS, REFUND_TIMES, REFUND_HOURS, COM_TEN_HOURS_NUM, COM_FIFTEEN_HOURS_NUM)
values ('2009', '2', '01', 67, 32381, null, null, 95633, 660527, 1275929, 25518580, .3101, .2798, .3162, .3162, 67, 163440, 5, 2120, 638802, 634011, null, .9925, null, null, null, null, null, null, null, to_date('16-01-2013 10:58:36', 'dd-mm-yyyy hh24:mi:ss'), null, 230, 104733, 58, 106, 4097, 8172, 88685, 48602);
insert into STATISTIC_YEAR (YEAR, ID, MONTH, REG_ENTERPRISE_NUM, REG_USER_NUM, REG_ENTERPRISE_GROWTH, REG_USER_GROWTH, ENTRY_USER_NUM, ENTRY_USER_TIMES, ENTRY_COUREHOURS, FEE_AMOUNT, ENTRY_USER_GROWTH, ENTRY_USER_TIMES_GROWTH, ENTRY_COUREHOURS_GROWTH, FEE_AMOUNT_GROWTH, REFUND_NUM, REFUND_AMOUNT, OVERYEAR_REFUND_NUM, OVERYEAR_REFUND_AMOUNT, STUDY_BEGIN_TIMES, STUDY_COMPLETE_TIMES, STUDY_BEGIN_RATE, STUDY_COMPLETE_RATE, STUDY_BEGIN_TIMES_GROWTH, STUDY_COMPLETE_TIMES_GROWTH, TEST_BEGIN_TIMES, TEST_COMPLETE_TIMES, TEST_BEGIN_TIMES_GROWTH, TEST_COMPLETE_TIMES_GROWTH, TEST_COMPLETE_RATE, CREATE_DATE, UPDATE_DATE, REG_ENTERPRISE_COUNT, REG_USER_COUNT, OVERYEAR_REFUND_TIMES, OVERYEAR_REFUND_HOURS, REFUND_TIMES, REFUND_HOURS, COM_TEN_HOURS_NUM, COM_FIFTEEN_HOURS_NUM)
values ('2010', '3', '01', 27, 59913, null, null, 142258, 1041008, 1923465, 33525320, .4878, .5828, .5138, .319, 74, 80920, null, 360, 1002854, 994731, null, .9919, null, null, null, null, null, null, null, to_date('16-01-2013 10:58:36', 'dd-mm-yyyy hh24:mi:ss'), null, 257, 164646, 11, 18, 1984, 4362.5, 128441, 75791);
insert into STATISTIC_YEAR (YEAR, ID, MONTH, REG_ENTERPRISE_NUM, REG_USER_NUM, REG_ENTERPRISE_GROWTH, REG_USER_GROWTH, ENTRY_USER_NUM, ENTRY_USER_TIMES, ENTRY_COUREHOURS, FEE_AMOUNT, ENTRY_USER_GROWTH, ENTRY_USER_TIMES_GROWTH, ENTRY_COUREHOURS_GROWTH, FEE_AMOUNT_GROWTH, REFUND_NUM, REFUND_AMOUNT, OVERYEAR_REFUND_NUM, OVERYEAR_REFUND_AMOUNT, STUDY_BEGIN_TIMES, STUDY_COMPLETE_TIMES, STUDY_BEGIN_RATE, STUDY_COMPLETE_RATE, STUDY_BEGIN_TIMES_GROWTH, STUDY_COMPLETE_TIMES_GROWTH, TEST_BEGIN_TIMES, TEST_COMPLETE_TIMES, TEST_BEGIN_TIMES_GROWTH, TEST_COMPLETE_TIMES_GROWTH, TEST_COMPLETE_RATE, CREATE_DATE, UPDATE_DATE, REG_ENTERPRISE_COUNT, REG_USER_COUNT, OVERYEAR_REFUND_TIMES, OVERYEAR_REFUND_HOURS, REFUND_TIMES, REFUND_HOURS, COM_TEN_HOURS_NUM, COM_FIFTEEN_HOURS_NUM)
values ('2011', '4', '01', 18, 78728, null, null, 207131, 1466076, 2842465, 56189420, .4564, .4091, .4792, .6778, 54, 76120, null, null, 1419819, 1410590, null, .9935, null, null, null, null, null, null, null, to_date('16-01-2013 10:58:36', 'dd-mm-yyyy hh24:mi:ss'), null, 275, 243374, null, null, 2022, 3804, 194183, 114895);
insert into STATISTIC_YEAR (YEAR, ID, MONTH, REG_ENTERPRISE_NUM, REG_USER_NUM, REG_ENTERPRISE_GROWTH, REG_USER_GROWTH, ENTRY_USER_NUM, ENTRY_USER_TIMES, ENTRY_COUREHOURS, FEE_AMOUNT, ENTRY_USER_GROWTH, ENTRY_USER_TIMES_GROWTH, ENTRY_COUREHOURS_GROWTH, FEE_AMOUNT_GROWTH, REFUND_NUM, REFUND_AMOUNT, OVERYEAR_REFUND_NUM, OVERYEAR_REFUND_AMOUNT, STUDY_BEGIN_TIMES, STUDY_COMPLETE_TIMES, STUDY_BEGIN_RATE, STUDY_COMPLETE_RATE, STUDY_BEGIN_TIMES_GROWTH, STUDY_COMPLETE_TIMES_GROWTH, TEST_BEGIN_TIMES, TEST_COMPLETE_TIMES, TEST_BEGIN_TIMES_GROWTH, TEST_COMPLETE_TIMES_GROWTH, TEST_COMPLETE_RATE, CREATE_DATE, UPDATE_DATE, REG_ENTERPRISE_COUNT, REG_USER_COUNT, OVERYEAR_REFUND_TIMES, OVERYEAR_REFUND_HOURS, REFUND_TIMES, REFUND_HOURS, COM_TEN_HOURS_NUM, COM_FIFTEEN_HOURS_NUM)
values ('2012', '5', '01', 9, 54346, null, null, 230922, 1783696, 3189765, 63301140, .115, .2163, .1218, .1262, 34, 107320, 3, 2640, 1719142, 1709687, null, .9945, null, null, null, null, null, null, null, to_date('16-01-2013 10:58:36', 'dd-mm-yyyy hh24:mi:ss'), null, 284, 297720, 91, 156, 2911, 5350, 218023, 132442);
commit;
prompt 5 records loaded
prompt Enabling triggers for STATISTIC_YEAR...
alter table STATISTIC_YEAR enable all triggers;
set feedback on
set define on
prompt Done.
