package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * EnumConst generated by MyEclipse - Hibernate Tools
 */

public class EnumConst extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {

	
	private static final long serialVersionUID = 3921197919074627275L;
    // Fields    

     private String id;
     private String name;
     private String code;
     private String namespace;
     private String isDefault;
     private Date createDate;
     private String note;
     private Set prTchStuElectivesForFlagScorePub = new HashSet(0);
     private Set prStuChangeSchoolsForFlagAbortschoolType = new HashSet(0);
     private Set peStudentsForScoreUniteShuxue = new HashSet(0);
     private Set peStudentsForScoreUniteYuwen = new HashSet(0);
     private Set prTchOpencoursesForFlagBak = new HashSet(0);
     private Set peStudentsForScoreUniteEnglishC = new HashSet(0);
     private Set peExamPatrolsForGender = new HashSet(0);
     private Set peExamPatrolsForFlagIsXunkao = new HashSet(0);
     private Set peStudentsForFlagMajorType = new HashSet(0);
     private Set peSitesForFlagBak = new HashSet(0);
     private Set peVotePapersForFlagIsvalid = new HashSet(0);
     private Set peMajorsForFlagBak = new HashSet(0);
     private Set peVotePapersForFlagLimitDiffip = new HashSet(0);
     private Set peVotePapersForFlagLimitDiffsession = new HashSet(0);
     private Set systemVariablesesForFlagBak = new HashSet(0);
     private Set peFeeBatchsForFlagFeeCheck = new HashSet(0);
     private Set peFeeBatchsForFlagBak = new HashSet(0);
     private Set peTchBooksForFlagIsvalid = new HashSet(0);
     private Set peVotePapersForFlagType = new HashSet(0);
     private Set peTchBooksForFlagBak = new HashSet(0);
     private Set peVotePapersForFlagViewSuggest = new HashSet(0);
     private Set pePcNewsesForFlagIssue = new HashSet(0);
     private Set prCourseArrangesForFlagBak = new HashSet(0);
     private Set prTchStuElectivesForFlagElectiveAdmission = new HashSet(0);
     private Set prTchStuPapersForFlagFinalLastUpdate = new HashSet(0);
     private Set prTchStuElectivesForFlagScoreStatus = new HashSet(0);
     private Set peStudentsForFlagAdvanced = new HashSet(0);
     private Set peBzzTchCoursewaresForFlagBak = new HashSet(0);
     private Set peStudentsForFlagStudentStatus = new HashSet(0);
     private Set peStudentsForScoreUniteComputer = new HashSet(0);
     private Set peStudentsForScoreUniteEnglishA = new HashSet(0);
     private Set peStudentsForFlagDisobey = new HashSet(0);
     private Set peStudentsForScoreUniteEnglishB = new HashSet(0);
     private Set peSitesForFlagActive = new HashSet(0);
     private Set peStudentsForDegreeEnglishType = new HashSet(0);
     private Set ssoUsersForFlagIsvalid = new HashSet(0);
     private Set peTchProgramsForFlagDegreeCandisobey = new HashSet(0);
     private Set peTeachersForFlagActive = new HashSet(0);
     private Set peRecExamcoursesForFlagArrangeRoom = new HashSet(0);
     private Set peSmsInfosForFlagSmsStatus = new HashSet(0);
     private Set prTchCourseTeachersForFlagBak = new HashSet(0);
     private Set peSmsSystempointsForFlagSmsStatus = new HashSet(0);
     private Set prExamStuMaincoursesForFlagScorePub = new HashSet(0);
     private Set prExamStuMaincoursesForFlagScoreStatus = new HashSet(0);
     private Set peRecExamcoursesForFlagBak = new HashSet(0);
     private Set peTchCoursewaresForFlagIsvalid = new HashSet(0);
     private Set peRecStudentsForFlagRecChannel = new HashSet(0);
     private Set ssoUsersForFlagBak = new HashSet(0);
     private Set peRecStudentsForFlagXueliCheck = new HashSet(0);
     private Set peRecStudentsForFlagMajorType = new HashSet(0);
     private Set peSitemanagersForFlagIsvalid = new HashSet(0);
     private Set pePriRolesForFlagRoleType = new HashSet(0);
     private Set peRecStudentsForFlagTeacherStatus = new HashSet(0);
     private Set prDocumentsForFlagRead = new HashSet(0);
     private Set peRecStudentsForFlagTeacher = new HashSet(0);
     private Set peBulletinsForFlagIsvalid = new HashSet(0);
     private Set peRecStudentsForFlagMatriculate = new HashSet(0);
     private Set peManagersForFlagIsvalid = new HashSet(0);
     private Set prStuChangeSchoolsForFlagBak = new HashSet(0);
     private Set prVoteQuestionsForFlagQuestionType = new HashSet(0);
     private Set pePcNewsesForFlagBak = new HashSet(0);
     private Set peRecStudentsForFlagRecStatus = new HashSet(0);
     private Set prBzzTchOpencourses = new HashSet(0);
     private Set prFeeDetailsForFlagFeeType = new HashSet(0);
     private Set prFeeDetailsForFlagFeeCheck = new HashSet(0);
     private Set prVoteSuggestsForFlagBak = new HashSet(0);
     private Set prVoteSuggestsForFlagCheck = new HashSet(0);
     private Set prVoteQuestionsForFlagBak = new HashSet(0);
     private Set prBzzTchStuElectivesForFlagScorePub = new HashSet(0);
     private Set systemVariablesesForFlagPlatformSection = new HashSet(0);
     private Set systemAppliesForApplyType = new HashSet(0);
     private Set prBzzTchStuElectivesForFlagScoreStatus = new HashSet(0);
     private Set prTchStuPapersForFlagSyllabusLastUpdate = new HashSet(0);
     private Set peTeachersForFlagPaper = new HashSet(0);
     private Set peManagersForGender = new HashSet(0);
     private Set peEnterpriseManagersForFlagIsvalid = new HashSet(0);
     private Set prPcElectivesForFlagBak = new HashSet(0);
     private Set peRecStudentsForFlagNoexam = new HashSet(0);
     private Set peRecStudentsForFlagNoexamStatus = new HashSet(0);
     private Set peRecStudentsForFlagPublish = new HashSet(0);
     private Set peMajorsForFlagIsEducation = new HashSet(0);
     private Set peInfoNewsesForFlagIsactive = new HashSet(0);
     private Set peExamPatrolsForFlagIsJiankao = new HashSet(0);
     private Set peSitemanagersForGender = new HashSet(0);
     private Set peBzzTchCoursewaresForFlagIsvalid = new HashSet(0);
     private Set peTeachersForGender = new HashSet(0);
     private Set prTchStuPapersForFlagDraftALastUpdate = new HashSet(0);
     private Set pePcTeachersForFlagTeacherType = new HashSet(0);
     private Set peTeachersForFlagMaxXueli = new HashSet(0);
     private Set peSmsSystempointsForFlagIsauto = new HashSet(0);
     private Set prPcElectivesForFlagEnrol = new HashSet(0);
     private Set peTchCoursesForFlagIsvalid = new HashSet(0);
     private Set systemAppliesForFlagApplyStatus = new HashSet(0);
     private Set peTchCoursewaresForFlagBak = new HashSet(0);
     private Set peTeachersForFlagMaxXuewei = new HashSet(0);
     private Set peTeachersForFlagZhicheng = new HashSet(0);
     private Set peInfoNewsesForFlagNewsStatus = new HashSet(0);
     private Set pePcTeachersForFlagBak = new HashSet(0);
     private Set peDocumentsForFlagBak = new HashSet(0);
     private Set prTchPaperContentsForFlagPaperSection = new HashSet(0);
     private Set peDocumentsForFlagDel = new HashSet(0);
     private Set peFeeLevelsForFlagBak = new HashSet(0);
     private Set prExamBookingsForFlagScoreStatusa = new HashSet(0);
     private Set prTchProgramCoursesForFlagBak = new HashSet(0);
     private Set prExamBookingsForFlagScoreStatus = new HashSet(0);
     private Set prTchProgramCoursesForFlagIsMainCourse = new HashSet(0);
     private Set prCourseArrangesForFlagCourseSection = new HashSet(0);
     private Set homeworkHistoriesForFlagIscheck = new HashSet(0);
     private Set homeworkInfosForFlagBak = new HashSet(0);
     private Set homeworkHistoriesForFlagBak = new HashSet(0);
     private Set prExamBookingsForFlagScoreStatusb = new HashSet(0);
     private Set peBzzTchCoursesForFlagCoursetype = new HashSet(0);
     private Set peBzzTchCoursesForFlagIsvisitAfterPass = new HashSet(0);
     private Set peBzzTchCoursesForFlagIsvalid = new HashSet(0);
     private Set peBzzTchCoursesForFlagIsFree = new HashSet(0);
     private Set peBzzTchCoursesForFlagIsRecommend = new HashSet(0);
     private Set peFeeLevelsForFlagDefault = new HashSet(0);
     private Set peTchCoursesForFlagIspubliccourse = new HashSet(0);
     private Set peTchProgramsForFlagUniteA = new HashSet(0);
     private Set peTchProgramsForFlagUniteB = new HashSet(0);
     private Set peTchProgramsForFlagMajorType = new HashSet(0);
     private Set peEnterpriseManagersForGender = new HashSet(0);
     private Set prTchPaperContentsForFlagActionUser = new HashSet(0);
     private Set pePriRolesForFlagBak = new HashSet(0);
     private Set homeworkInfosForFlagIsvalid = new HashSet(0);
     private Set peSmsInfosForFlagSmsType = new HashSet(0);
     private Set peBulletinsForFlagIstop = new HashSet(0);
     private Set prDocumentsForFlagDel = new HashSet(0);
     private Set prTchOpencoursesForFlagExamCourse = new HashSet(0);
     private Set prTchStuPapersForFlagTitleAdmission = new HashSet(0);
     private Set prTchStuPapersForFlagPaperRejoin = new HashSet(0);
     private Set prTchCourseTeachersForFlagTeacherType = new HashSet(0);
     private Set peVotePapersForFlagCanSuggest = new HashSet(0);
     private Set peBzzTchCourseForFlagCourseCategory = new HashSet(0);
     private Set peBzzFaxInfoForFlagFpOpenState = new HashSet(0);
     private Set peBzzFaxInfoForFlagFpMailState = new HashSet(0);
     
     private Set peBzzMailInfoForFlagMailSendState = new HashSet(0);
     private Set peBzzMailInfoForFlatContainInvoiceState = new HashSet(0);
     
     private Set peBzzRecruitForFlagRegistState = new HashSet(0);
     private Set peBzzStudentForFlagRankState = new HashSet(0);
     private Set peEnterpriseForFlagElective = new HashSet(0);
     
     
     private Set peBzzGoodStuForFlaggoodState = new HashSet(0);
     private Set peBzzGoodMagForFlaggoodState = new HashSet(0);
     private Set peBzzPartyForFlagPartyState = new HashSet(0);
     
     private Set peGradeForFlagIsvalid = new HashSet(0);

     private Set peBzzBatchs = new HashSet(0);
     private Set peBzzOrderInfoFlagOrderType = new HashSet(0);
     private Set prBzzTchStuElectiveFlagElectivePayStatus = new HashSet(0);
     private Set peBzzOrderInfoRefundState = new HashSet(0);
     
     private Set peElectiveCoursePeriodFlagElePeriodPayStatus = new HashSet(0);
     private Set peBzzTchCoursFlagCanJoinBatch = new HashSet(0);
     private Set stuBatchFlagBatchPayStates = new HashSet(0);
     
     private Set peBzzTchCourseFlagIsExam = new HashSet(0);
     
     private Set peBzzInvoiceFlagPrint =new HashSet(0);
    // Constructors

   

	public Set getPeBzzTchCourseFlagIsExam() {
		return peBzzTchCourseFlagIsExam;
	}

	public void setPeBzzTchCourseFlagIsExam(Set peBzzTchCourseFlagIsExam) {
		this.peBzzTchCourseFlagIsExam = peBzzTchCourseFlagIsExam;
	}

	/** default constructor */
    public EnumConst() {
    }

	/** minimal constructor */
    public EnumConst(String name, String namespace) {
        this.name = name;
        this.namespace = namespace;
    }
    
    /** full constructor */
    public EnumConst(String id, String name, String code, String namespace,
			String isDefault, Date createDate, String note,
			Set prTchStuElectivesForFlagScorePub,
			Set prStuChangeSchoolsForFlagAbortschoolType,
			Set peStudentsForScoreUniteShuxue,
			Set peStudentsForScoreUniteYuwen, Set prTchOpencoursesForFlagBak,
			Set peStudentsForScoreUniteEnglishC, Set peExamPatrolsForGender,
			Set peExamPatrolsForFlagIsXunkao, Set peStudentsForFlagMajorType,
			Set peSitesForFlagBak, Set peVotePapersForFlagIsvalid,
			Set peMajorsForFlagBak, Set peVotePapersForFlagLimitDiffip,
			Set peVotePapersForFlagLimitDiffsession,
			Set systemVariablesesForFlagBak, Set peFeeBatchsForFlagFeeCheck,
			Set peFeeBatchsForFlagBak, Set peTchBooksForFlagIsvalid,
			Set peVotePapersForFlagType, Set peTchBooksForFlagBak,
			Set peVotePapersForFlagViewSuggest, Set pePcNewsesForFlagIssue,
			Set prCourseArrangesForFlagBak,
			Set prTchStuElectivesForFlagElectiveAdmission,
			Set prTchStuPapersForFlagFinalLastUpdate,
			Set prTchStuElectivesForFlagScoreStatus,
			Set peStudentsForFlagAdvanced, Set peBzzTchCoursewaresForFlagBak,
			Set peStudentsForFlagStudentStatus,
			Set peStudentsForScoreUniteComputer,
			Set peStudentsForScoreUniteEnglishA, Set peStudentsForFlagDisobey,
			Set peStudentsForScoreUniteEnglishB, Set peSitesForFlagActive,
			Set peStudentsForDegreeEnglishType, Set ssoUsersForFlagIsvalid,
			Set peTchProgramsForFlagDegreeCandisobey,
			Set peTeachersForFlagActive,
			Set peRecExamcoursesForFlagArrangeRoom,
			Set peSmsInfosForFlagSmsStatus, Set prTchCourseTeachersForFlagBak,
			Set peSmsSystempointsForFlagSmsStatus,
			Set prExamStuMaincoursesForFlagScorePub,
			Set prExamStuMaincoursesForFlagScoreStatus,
			Set peRecExamcoursesForFlagBak, Set peTchCoursewaresForFlagIsvalid,
			Set peRecStudentsForFlagRecChannel, Set ssoUsersForFlagBak,
			Set peRecStudentsForFlagXueliCheck,
			Set peRecStudentsForFlagMajorType,
			Set peSitemanagersForFlagIsvalid, Set pePriRolesForFlagRoleType,
			Set peRecStudentsForFlagTeacherStatus, Set prDocumentsForFlagRead,
			Set peRecStudentsForFlagTeacher, Set peBulletinsForFlagIsvalid,
			Set peRecStudentsForFlagMatriculate, Set peManagersForFlagIsvalid,
			Set prStuChangeSchoolsForFlagBak,
			Set prVoteQuestionsForFlagQuestionType, Set pePcNewsesForFlagBak,
			Set peRecStudentsForFlagRecStatus, Set prBzzTchOpencourses,
			Set prFeeDetailsForFlagFeeType, Set prFeeDetailsForFlagFeeCheck,
			Set prVoteSuggestsForFlagBak, Set prVoteSuggestsForFlagCheck,
			Set prVoteQuestionsForFlagBak,
			Set prBzzTchStuElectivesForFlagScorePub,
			Set systemVariablesesForFlagPlatformSection,
			Set systemAppliesForApplyType,
			Set prBzzTchStuElectivesForFlagScoreStatus,
			Set prTchStuPapersForFlagSyllabusLastUpdate,
			Set peTeachersForFlagPaper, Set peManagersForGender,
			Set peEnterpriseManagersForFlagIsvalid,
			Set prPcElectivesForFlagBak, Set peRecStudentsForFlagNoexam,
			Set peRecStudentsForFlagNoexamStatus,
			Set peRecStudentsForFlagPublish, Set peMajorsForFlagIsEducation,
			Set peInfoNewsesForFlagIsactive, Set peExamPatrolsForFlagIsJiankao,
			Set peSitemanagersForGender, Set peBzzTchCoursewaresForFlagIsvalid,
			Set peTeachersForGender, Set prTchStuPapersForFlagDraftALastUpdate,
			Set pePcTeachersForFlagTeacherType, Set peTeachersForFlagMaxXueli,
			Set peSmsSystempointsForFlagIsauto, Set prPcElectivesForFlagEnrol,
			Set peTchCoursesForFlagIsvalid,
			Set systemAppliesForFlagApplyStatus,
			Set peTchCoursewaresForFlagBak, Set peTeachersForFlagMaxXuewei,
			Set peTeachersForFlagZhicheng, Set peInfoNewsesForFlagNewsStatus,
			Set pePcTeachersForFlagBak, Set peDocumentsForFlagBak,
			Set prTchPaperContentsForFlagPaperSection,
			Set peDocumentsForFlagDel, Set peFeeLevelsForFlagBak,
			Set prExamBookingsForFlagScoreStatusa,
			Set prTchProgramCoursesForFlagBak,
			Set prExamBookingsForFlagScoreStatus,
			Set prTchProgramCoursesForFlagIsMainCourse,
			Set prCourseArrangesForFlagCourseSection,
			Set homeworkHistoriesForFlagIscheck, Set homeworkInfosForFlagBak,
			Set homeworkHistoriesForFlagBak,
			Set prExamBookingsForFlagScoreStatusb,
			Set peBzzTchCoursesForFlagCoursetype,
			Set peBzzTchCoursesForFlagIsvisitAfterPass,
			Set peBzzTchCoursesForFlagIsvalid,
			Set peBzzTchCoursesForFlagIsFree,
			Set peBzzTchCoursesForFlagIsRecommend,
			Set peFeeLevelsForFlagDefault,
			Set peTchCoursesForFlagIspubliccourse,
			Set peTchProgramsForFlagUniteA, Set peTchProgramsForFlagUniteB,
			Set peTchProgramsForFlagMajorType,
			Set peEnterpriseManagersForGender,
			Set prTchPaperContentsForFlagActionUser, Set pePriRolesForFlagBak,
			Set homeworkInfosForFlagIsvalid, Set peSmsInfosForFlagSmsType,
			Set peBulletinsForFlagIstop, Set prDocumentsForFlagDel,
			Set prTchOpencoursesForFlagExamCourse,
			Set prTchStuPapersForFlagTitleAdmission,
			Set prTchStuPapersForFlagPaperRejoin,
			Set prTchCourseTeachersForFlagTeacherType,
			Set peVotePapersForFlagCanSuggest,
			Set peBzzTchCourseForFlagCourseCategory,
			Set peBzzFaxInfoForFlagFpOpenState,
			Set peBzzFaxInfoForFlagFpMailState,
			Set peBzzMailInfoForFlagMailSendState,
			Set peBzzMailInfoForFlatContainInvoiceState,
			Set peBzzRecruitForFlagRegistState,
			Set peBzzStudentForFlagRankState, Set peEnterpriseForFlagElective,
			Set peBzzGoodStuForFlaggoodState, Set peBzzGoodMagForFlaggoodState,
			Set peBzzPartyForFlagPartyState, Set peGradeForFlagIsvalid,
			Set peBzzBatchs, Set peBzzOrderInfoFlagOrderType,
			Set prBzzTchStuElectiveFlagElectivePayStatus,
			Set peBzzOrderInfoRefundState,
			Set peElectiveCoursePeriodFlagElePeriodPayStatus,
			Set peBzzTchCoursFlagCanJoinBatch, Set stuBatchFlagBatchPayStates,
			Set peBzzTchCourseFlagIsExam, Set peBzzInvoiceFlagPrint) {
		super();
		this.id = id;
		this.name = name;
		this.code = code;
		this.namespace = namespace;
		this.isDefault = isDefault;
		this.createDate = createDate;
		this.note = note;
		this.prTchStuElectivesForFlagScorePub = prTchStuElectivesForFlagScorePub;
		this.prStuChangeSchoolsForFlagAbortschoolType = prStuChangeSchoolsForFlagAbortschoolType;
		this.peStudentsForScoreUniteShuxue = peStudentsForScoreUniteShuxue;
		this.peStudentsForScoreUniteYuwen = peStudentsForScoreUniteYuwen;
		this.prTchOpencoursesForFlagBak = prTchOpencoursesForFlagBak;
		this.peStudentsForScoreUniteEnglishC = peStudentsForScoreUniteEnglishC;
		this.peExamPatrolsForGender = peExamPatrolsForGender;
		this.peExamPatrolsForFlagIsXunkao = peExamPatrolsForFlagIsXunkao;
		this.peStudentsForFlagMajorType = peStudentsForFlagMajorType;
		this.peSitesForFlagBak = peSitesForFlagBak;
		this.peVotePapersForFlagIsvalid = peVotePapersForFlagIsvalid;
		this.peMajorsForFlagBak = peMajorsForFlagBak;
		this.peVotePapersForFlagLimitDiffip = peVotePapersForFlagLimitDiffip;
		this.peVotePapersForFlagLimitDiffsession = peVotePapersForFlagLimitDiffsession;
		this.systemVariablesesForFlagBak = systemVariablesesForFlagBak;
		this.peFeeBatchsForFlagFeeCheck = peFeeBatchsForFlagFeeCheck;
		this.peFeeBatchsForFlagBak = peFeeBatchsForFlagBak;
		this.peTchBooksForFlagIsvalid = peTchBooksForFlagIsvalid;
		this.peVotePapersForFlagType = peVotePapersForFlagType;
		this.peTchBooksForFlagBak = peTchBooksForFlagBak;
		this.peVotePapersForFlagViewSuggest = peVotePapersForFlagViewSuggest;
		this.pePcNewsesForFlagIssue = pePcNewsesForFlagIssue;
		this.prCourseArrangesForFlagBak = prCourseArrangesForFlagBak;
		this.prTchStuElectivesForFlagElectiveAdmission = prTchStuElectivesForFlagElectiveAdmission;
		this.prTchStuPapersForFlagFinalLastUpdate = prTchStuPapersForFlagFinalLastUpdate;
		this.prTchStuElectivesForFlagScoreStatus = prTchStuElectivesForFlagScoreStatus;
		this.peStudentsForFlagAdvanced = peStudentsForFlagAdvanced;
		this.peBzzTchCoursewaresForFlagBak = peBzzTchCoursewaresForFlagBak;
		this.peStudentsForFlagStudentStatus = peStudentsForFlagStudentStatus;
		this.peStudentsForScoreUniteComputer = peStudentsForScoreUniteComputer;
		this.peStudentsForScoreUniteEnglishA = peStudentsForScoreUniteEnglishA;
		this.peStudentsForFlagDisobey = peStudentsForFlagDisobey;
		this.peStudentsForScoreUniteEnglishB = peStudentsForScoreUniteEnglishB;
		this.peSitesForFlagActive = peSitesForFlagActive;
		this.peStudentsForDegreeEnglishType = peStudentsForDegreeEnglishType;
		this.ssoUsersForFlagIsvalid = ssoUsersForFlagIsvalid;
		this.peTchProgramsForFlagDegreeCandisobey = peTchProgramsForFlagDegreeCandisobey;
		this.peTeachersForFlagActive = peTeachersForFlagActive;
		this.peRecExamcoursesForFlagArrangeRoom = peRecExamcoursesForFlagArrangeRoom;
		this.peSmsInfosForFlagSmsStatus = peSmsInfosForFlagSmsStatus;
		this.prTchCourseTeachersForFlagBak = prTchCourseTeachersForFlagBak;
		this.peSmsSystempointsForFlagSmsStatus = peSmsSystempointsForFlagSmsStatus;
		this.prExamStuMaincoursesForFlagScorePub = prExamStuMaincoursesForFlagScorePub;
		this.prExamStuMaincoursesForFlagScoreStatus = prExamStuMaincoursesForFlagScoreStatus;
		this.peRecExamcoursesForFlagBak = peRecExamcoursesForFlagBak;
		this.peTchCoursewaresForFlagIsvalid = peTchCoursewaresForFlagIsvalid;
		this.peRecStudentsForFlagRecChannel = peRecStudentsForFlagRecChannel;
		this.ssoUsersForFlagBak = ssoUsersForFlagBak;
		this.peRecStudentsForFlagXueliCheck = peRecStudentsForFlagXueliCheck;
		this.peRecStudentsForFlagMajorType = peRecStudentsForFlagMajorType;
		this.peSitemanagersForFlagIsvalid = peSitemanagersForFlagIsvalid;
		this.pePriRolesForFlagRoleType = pePriRolesForFlagRoleType;
		this.peRecStudentsForFlagTeacherStatus = peRecStudentsForFlagTeacherStatus;
		this.prDocumentsForFlagRead = prDocumentsForFlagRead;
		this.peRecStudentsForFlagTeacher = peRecStudentsForFlagTeacher;
		this.peBulletinsForFlagIsvalid = peBulletinsForFlagIsvalid;
		this.peRecStudentsForFlagMatriculate = peRecStudentsForFlagMatriculate;
		this.peManagersForFlagIsvalid = peManagersForFlagIsvalid;
		this.prStuChangeSchoolsForFlagBak = prStuChangeSchoolsForFlagBak;
		this.prVoteQuestionsForFlagQuestionType = prVoteQuestionsForFlagQuestionType;
		this.pePcNewsesForFlagBak = pePcNewsesForFlagBak;
		this.peRecStudentsForFlagRecStatus = peRecStudentsForFlagRecStatus;
		this.prBzzTchOpencourses = prBzzTchOpencourses;
		this.prFeeDetailsForFlagFeeType = prFeeDetailsForFlagFeeType;
		this.prFeeDetailsForFlagFeeCheck = prFeeDetailsForFlagFeeCheck;
		this.prVoteSuggestsForFlagBak = prVoteSuggestsForFlagBak;
		this.prVoteSuggestsForFlagCheck = prVoteSuggestsForFlagCheck;
		this.prVoteQuestionsForFlagBak = prVoteQuestionsForFlagBak;
		this.prBzzTchStuElectivesForFlagScorePub = prBzzTchStuElectivesForFlagScorePub;
		this.systemVariablesesForFlagPlatformSection = systemVariablesesForFlagPlatformSection;
		this.systemAppliesForApplyType = systemAppliesForApplyType;
		this.prBzzTchStuElectivesForFlagScoreStatus = prBzzTchStuElectivesForFlagScoreStatus;
		this.prTchStuPapersForFlagSyllabusLastUpdate = prTchStuPapersForFlagSyllabusLastUpdate;
		this.peTeachersForFlagPaper = peTeachersForFlagPaper;
		this.peManagersForGender = peManagersForGender;
		this.peEnterpriseManagersForFlagIsvalid = peEnterpriseManagersForFlagIsvalid;
		this.prPcElectivesForFlagBak = prPcElectivesForFlagBak;
		this.peRecStudentsForFlagNoexam = peRecStudentsForFlagNoexam;
		this.peRecStudentsForFlagNoexamStatus = peRecStudentsForFlagNoexamStatus;
		this.peRecStudentsForFlagPublish = peRecStudentsForFlagPublish;
		this.peMajorsForFlagIsEducation = peMajorsForFlagIsEducation;
		this.peInfoNewsesForFlagIsactive = peInfoNewsesForFlagIsactive;
		this.peExamPatrolsForFlagIsJiankao = peExamPatrolsForFlagIsJiankao;
		this.peSitemanagersForGender = peSitemanagersForGender;
		this.peBzzTchCoursewaresForFlagIsvalid = peBzzTchCoursewaresForFlagIsvalid;
		this.peTeachersForGender = peTeachersForGender;
		this.prTchStuPapersForFlagDraftALastUpdate = prTchStuPapersForFlagDraftALastUpdate;
		this.pePcTeachersForFlagTeacherType = pePcTeachersForFlagTeacherType;
		this.peTeachersForFlagMaxXueli = peTeachersForFlagMaxXueli;
		this.peSmsSystempointsForFlagIsauto = peSmsSystempointsForFlagIsauto;
		this.prPcElectivesForFlagEnrol = prPcElectivesForFlagEnrol;
		this.peTchCoursesForFlagIsvalid = peTchCoursesForFlagIsvalid;
		this.systemAppliesForFlagApplyStatus = systemAppliesForFlagApplyStatus;
		this.peTchCoursewaresForFlagBak = peTchCoursewaresForFlagBak;
		this.peTeachersForFlagMaxXuewei = peTeachersForFlagMaxXuewei;
		this.peTeachersForFlagZhicheng = peTeachersForFlagZhicheng;
		this.peInfoNewsesForFlagNewsStatus = peInfoNewsesForFlagNewsStatus;
		this.pePcTeachersForFlagBak = pePcTeachersForFlagBak;
		this.peDocumentsForFlagBak = peDocumentsForFlagBak;
		this.prTchPaperContentsForFlagPaperSection = prTchPaperContentsForFlagPaperSection;
		this.peDocumentsForFlagDel = peDocumentsForFlagDel;
		this.peFeeLevelsForFlagBak = peFeeLevelsForFlagBak;
		this.prExamBookingsForFlagScoreStatusa = prExamBookingsForFlagScoreStatusa;
		this.prTchProgramCoursesForFlagBak = prTchProgramCoursesForFlagBak;
		this.prExamBookingsForFlagScoreStatus = prExamBookingsForFlagScoreStatus;
		this.prTchProgramCoursesForFlagIsMainCourse = prTchProgramCoursesForFlagIsMainCourse;
		this.prCourseArrangesForFlagCourseSection = prCourseArrangesForFlagCourseSection;
		this.homeworkHistoriesForFlagIscheck = homeworkHistoriesForFlagIscheck;
		this.homeworkInfosForFlagBak = homeworkInfosForFlagBak;
		this.homeworkHistoriesForFlagBak = homeworkHistoriesForFlagBak;
		this.prExamBookingsForFlagScoreStatusb = prExamBookingsForFlagScoreStatusb;
		this.peBzzTchCoursesForFlagCoursetype = peBzzTchCoursesForFlagCoursetype;
		this.peBzzTchCoursesForFlagIsvisitAfterPass = peBzzTchCoursesForFlagIsvisitAfterPass;
		this.peBzzTchCoursesForFlagIsvalid = peBzzTchCoursesForFlagIsvalid;
		this.peBzzTchCoursesForFlagIsFree = peBzzTchCoursesForFlagIsFree;
		this.peBzzTchCoursesForFlagIsRecommend = peBzzTchCoursesForFlagIsRecommend;
		this.peFeeLevelsForFlagDefault = peFeeLevelsForFlagDefault;
		this.peTchCoursesForFlagIspubliccourse = peTchCoursesForFlagIspubliccourse;
		this.peTchProgramsForFlagUniteA = peTchProgramsForFlagUniteA;
		this.peTchProgramsForFlagUniteB = peTchProgramsForFlagUniteB;
		this.peTchProgramsForFlagMajorType = peTchProgramsForFlagMajorType;
		this.peEnterpriseManagersForGender = peEnterpriseManagersForGender;
		this.prTchPaperContentsForFlagActionUser = prTchPaperContentsForFlagActionUser;
		this.pePriRolesForFlagBak = pePriRolesForFlagBak;
		this.homeworkInfosForFlagIsvalid = homeworkInfosForFlagIsvalid;
		this.peSmsInfosForFlagSmsType = peSmsInfosForFlagSmsType;
		this.peBulletinsForFlagIstop = peBulletinsForFlagIstop;
		this.prDocumentsForFlagDel = prDocumentsForFlagDel;
		this.prTchOpencoursesForFlagExamCourse = prTchOpencoursesForFlagExamCourse;
		this.prTchStuPapersForFlagTitleAdmission = prTchStuPapersForFlagTitleAdmission;
		this.prTchStuPapersForFlagPaperRejoin = prTchStuPapersForFlagPaperRejoin;
		this.prTchCourseTeachersForFlagTeacherType = prTchCourseTeachersForFlagTeacherType;
		this.peVotePapersForFlagCanSuggest = peVotePapersForFlagCanSuggest;
		this.peBzzTchCourseForFlagCourseCategory = peBzzTchCourseForFlagCourseCategory;
		this.peBzzFaxInfoForFlagFpOpenState = peBzzFaxInfoForFlagFpOpenState;
		this.peBzzFaxInfoForFlagFpMailState = peBzzFaxInfoForFlagFpMailState;
		this.peBzzMailInfoForFlagMailSendState = peBzzMailInfoForFlagMailSendState;
		this.peBzzMailInfoForFlatContainInvoiceState = peBzzMailInfoForFlatContainInvoiceState;
		this.peBzzRecruitForFlagRegistState = peBzzRecruitForFlagRegistState;
		this.peBzzStudentForFlagRankState = peBzzStudentForFlagRankState;
		this.peEnterpriseForFlagElective = peEnterpriseForFlagElective;
		this.peBzzGoodStuForFlaggoodState = peBzzGoodStuForFlaggoodState;
		this.peBzzGoodMagForFlaggoodState = peBzzGoodMagForFlaggoodState;
		this.peBzzPartyForFlagPartyState = peBzzPartyForFlagPartyState;
		this.peGradeForFlagIsvalid = peGradeForFlagIsvalid;
		this.peBzzBatchs = peBzzBatchs;
		this.peBzzOrderInfoFlagOrderType = peBzzOrderInfoFlagOrderType;
		this.prBzzTchStuElectiveFlagElectivePayStatus = prBzzTchStuElectiveFlagElectivePayStatus;
		this.peBzzOrderInfoRefundState = peBzzOrderInfoRefundState;
		this.peElectiveCoursePeriodFlagElePeriodPayStatus = peElectiveCoursePeriodFlagElePeriodPayStatus;
		this.peBzzTchCoursFlagCanJoinBatch = peBzzTchCoursFlagCanJoinBatch;
		this.stuBatchFlagBatchPayStates = stuBatchFlagBatchPayStates;
		this.peBzzTchCourseFlagIsExam = peBzzTchCourseFlagIsExam;
		this.peBzzInvoiceFlagPrint = peBzzInvoiceFlagPrint;
	}
   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getNamespace() {
        return this.namespace;
    }
    
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    public String getIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public Set getPrTchStuElectivesForFlagScorePub() {
        return this.prTchStuElectivesForFlagScorePub;
    }
    
    public void setPrTchStuElectivesForFlagScorePub(Set prTchStuElectivesForFlagScorePub) {
        this.prTchStuElectivesForFlagScorePub = prTchStuElectivesForFlagScorePub;
    }

    public Set getPrStuChangeSchoolsForFlagAbortschoolType() {
        return this.prStuChangeSchoolsForFlagAbortschoolType;
    }
    
    public void setPrStuChangeSchoolsForFlagAbortschoolType(Set prStuChangeSchoolsForFlagAbortschoolType) {
        this.prStuChangeSchoolsForFlagAbortschoolType = prStuChangeSchoolsForFlagAbortschoolType;
    }

    public Set getPeStudentsForScoreUniteShuxue() {
        return this.peStudentsForScoreUniteShuxue;
    }
    
    public void setPeStudentsForScoreUniteShuxue(Set peStudentsForScoreUniteShuxue) {
        this.peStudentsForScoreUniteShuxue = peStudentsForScoreUniteShuxue;
    }

    public Set getPeStudentsForScoreUniteYuwen() {
        return this.peStudentsForScoreUniteYuwen;
    }
    
    public void setPeStudentsForScoreUniteYuwen(Set peStudentsForScoreUniteYuwen) {
        this.peStudentsForScoreUniteYuwen = peStudentsForScoreUniteYuwen;
    }

    public Set getPrTchOpencoursesForFlagBak() {
        return this.prTchOpencoursesForFlagBak;
    }
    
    public void setPrTchOpencoursesForFlagBak(Set prTchOpencoursesForFlagBak) {
        this.prTchOpencoursesForFlagBak = prTchOpencoursesForFlagBak;
    }

    public Set getPeStudentsForScoreUniteEnglishC() {
        return this.peStudentsForScoreUniteEnglishC;
    }
    
    public void setPeStudentsForScoreUniteEnglishC(Set peStudentsForScoreUniteEnglishC) {
        this.peStudentsForScoreUniteEnglishC = peStudentsForScoreUniteEnglishC;
    }

    public Set getPeExamPatrolsForGender() {
        return this.peExamPatrolsForGender;
    }
    
    public void setPeExamPatrolsForGender(Set peExamPatrolsForGender) {
        this.peExamPatrolsForGender = peExamPatrolsForGender;
    }

    public Set getPeExamPatrolsForFlagIsXunkao() {
        return this.peExamPatrolsForFlagIsXunkao;
    }
    
    public void setPeExamPatrolsForFlagIsXunkao(Set peExamPatrolsForFlagIsXunkao) {
        this.peExamPatrolsForFlagIsXunkao = peExamPatrolsForFlagIsXunkao;
    }

    public Set getPeStudentsForFlagMajorType() {
        return this.peStudentsForFlagMajorType;
    }
    
    public void setPeStudentsForFlagMajorType(Set peStudentsForFlagMajorType) {
        this.peStudentsForFlagMajorType = peStudentsForFlagMajorType;
    }

    public Set getPeSitesForFlagBak() {
        return this.peSitesForFlagBak;
    }
    
    public void setPeSitesForFlagBak(Set peSitesForFlagBak) {
        this.peSitesForFlagBak = peSitesForFlagBak;
    }

    public Set getPeVotePapersForFlagIsvalid() {
        return this.peVotePapersForFlagIsvalid;
    }
    
    public void setPeVotePapersForFlagIsvalid(Set peVotePapersForFlagIsvalid) {
        this.peVotePapersForFlagIsvalid = peVotePapersForFlagIsvalid;
    }

    public Set getPeMajorsForFlagBak() {
        return this.peMajorsForFlagBak;
    }
    
    public void setPeMajorsForFlagBak(Set peMajorsForFlagBak) {
        this.peMajorsForFlagBak = peMajorsForFlagBak;
    }

    public Set getPeVotePapersForFlagLimitDiffip() {
        return this.peVotePapersForFlagLimitDiffip;
    }
    
    public void setPeVotePapersForFlagLimitDiffip(Set peVotePapersForFlagLimitDiffip) {
        this.peVotePapersForFlagLimitDiffip = peVotePapersForFlagLimitDiffip;
    }

    public Set getPeVotePapersForFlagLimitDiffsession() {
        return this.peVotePapersForFlagLimitDiffsession;
    }
    
    public void setPeVotePapersForFlagLimitDiffsession(Set peVotePapersForFlagLimitDiffsession) {
        this.peVotePapersForFlagLimitDiffsession = peVotePapersForFlagLimitDiffsession;
    }

    public Set getSystemVariablesesForFlagBak() {
        return this.systemVariablesesForFlagBak;
    }
    
    public void setSystemVariablesesForFlagBak(Set systemVariablesesForFlagBak) {
        this.systemVariablesesForFlagBak = systemVariablesesForFlagBak;
    }

    public Set getPeFeeBatchsForFlagFeeCheck() {
        return this.peFeeBatchsForFlagFeeCheck;
    }
    
    public void setPeFeeBatchsForFlagFeeCheck(Set peFeeBatchsForFlagFeeCheck) {
        this.peFeeBatchsForFlagFeeCheck = peFeeBatchsForFlagFeeCheck;
    }

    public Set getPeFeeBatchsForFlagBak() {
        return this.peFeeBatchsForFlagBak;
    }
    
    public void setPeFeeBatchsForFlagBak(Set peFeeBatchsForFlagBak) {
        this.peFeeBatchsForFlagBak = peFeeBatchsForFlagBak;
    }

    public Set getPeTchBooksForFlagIsvalid() {
        return this.peTchBooksForFlagIsvalid;
    }
    
    public void setPeTchBooksForFlagIsvalid(Set peTchBooksForFlagIsvalid) {
        this.peTchBooksForFlagIsvalid = peTchBooksForFlagIsvalid;
    }

    public Set getPeVotePapersForFlagType() {
        return this.peVotePapersForFlagType;
    }
    
    public void setPeVotePapersForFlagType(Set peVotePapersForFlagType) {
        this.peVotePapersForFlagType = peVotePapersForFlagType;
    }

    public Set getPeTchBooksForFlagBak() {
        return this.peTchBooksForFlagBak;
    }
    
    public void setPeTchBooksForFlagBak(Set peTchBooksForFlagBak) {
        this.peTchBooksForFlagBak = peTchBooksForFlagBak;
    }

    public Set getPeVotePapersForFlagViewSuggest() {
        return this.peVotePapersForFlagViewSuggest;
    }
    
    public void setPeVotePapersForFlagViewSuggest(Set peVotePapersForFlagViewSuggest) {
        this.peVotePapersForFlagViewSuggest = peVotePapersForFlagViewSuggest;
    }

    public Set getPePcNewsesForFlagIssue() {
        return this.pePcNewsesForFlagIssue;
    }
    
    public void setPePcNewsesForFlagIssue(Set pePcNewsesForFlagIssue) {
        this.pePcNewsesForFlagIssue = pePcNewsesForFlagIssue;
    }

    public Set getPrCourseArrangesForFlagBak() {
        return this.prCourseArrangesForFlagBak;
    }
    
    public void setPrCourseArrangesForFlagBak(Set prCourseArrangesForFlagBak) {
        this.prCourseArrangesForFlagBak = prCourseArrangesForFlagBak;
    }

    public Set getPrTchStuElectivesForFlagElectiveAdmission() {
        return this.prTchStuElectivesForFlagElectiveAdmission;
    }
    
    public void setPrTchStuElectivesForFlagElectiveAdmission(Set prTchStuElectivesForFlagElectiveAdmission) {
        this.prTchStuElectivesForFlagElectiveAdmission = prTchStuElectivesForFlagElectiveAdmission;
    }

    public Set getPrTchStuPapersForFlagFinalLastUpdate() {
        return this.prTchStuPapersForFlagFinalLastUpdate;
    }
    
    public void setPrTchStuPapersForFlagFinalLastUpdate(Set prTchStuPapersForFlagFinalLastUpdate) {
        this.prTchStuPapersForFlagFinalLastUpdate = prTchStuPapersForFlagFinalLastUpdate;
    }

    public Set getPrTchStuElectivesForFlagScoreStatus() {
        return this.prTchStuElectivesForFlagScoreStatus;
    }
    
    public void setPrTchStuElectivesForFlagScoreStatus(Set prTchStuElectivesForFlagScoreStatus) {
        this.prTchStuElectivesForFlagScoreStatus = prTchStuElectivesForFlagScoreStatus;
    }

    public Set getPeStudentsForFlagAdvanced() {
        return this.peStudentsForFlagAdvanced;
    }
    
    public void setPeStudentsForFlagAdvanced(Set peStudentsForFlagAdvanced) {
        this.peStudentsForFlagAdvanced = peStudentsForFlagAdvanced;
    }

    public Set getPeBzzTchCoursewaresForFlagBak() {
        return this.peBzzTchCoursewaresForFlagBak;
    }
    
    public void setPeBzzTchCoursewaresForFlagBak(Set peBzzTchCoursewaresForFlagBak) {
        this.peBzzTchCoursewaresForFlagBak = peBzzTchCoursewaresForFlagBak;
    }

    public Set getPeStudentsForFlagStudentStatus() {
        return this.peStudentsForFlagStudentStatus;
    }
    
    public void setPeStudentsForFlagStudentStatus(Set peStudentsForFlagStudentStatus) {
        this.peStudentsForFlagStudentStatus = peStudentsForFlagStudentStatus;
    }

    public Set getPeStudentsForScoreUniteComputer() {
        return this.peStudentsForScoreUniteComputer;
    }
    
    public void setPeStudentsForScoreUniteComputer(Set peStudentsForScoreUniteComputer) {
        this.peStudentsForScoreUniteComputer = peStudentsForScoreUniteComputer;
    }

    public Set getPeStudentsForScoreUniteEnglishA() {
        return this.peStudentsForScoreUniteEnglishA;
    }
    
    public void setPeStudentsForScoreUniteEnglishA(Set peStudentsForScoreUniteEnglishA) {
        this.peStudentsForScoreUniteEnglishA = peStudentsForScoreUniteEnglishA;
    }

    public Set getPeStudentsForFlagDisobey() {
        return this.peStudentsForFlagDisobey;
    }
    
    public void setPeStudentsForFlagDisobey(Set peStudentsForFlagDisobey) {
        this.peStudentsForFlagDisobey = peStudentsForFlagDisobey;
    }

    public Set getPeStudentsForScoreUniteEnglishB() {
        return this.peStudentsForScoreUniteEnglishB;
    }
    
    public void setPeStudentsForScoreUniteEnglishB(Set peStudentsForScoreUniteEnglishB) {
        this.peStudentsForScoreUniteEnglishB = peStudentsForScoreUniteEnglishB;
    }

    public Set getPeSitesForFlagActive() {
        return this.peSitesForFlagActive;
    }
    
    public void setPeSitesForFlagActive(Set peSitesForFlagActive) {
        this.peSitesForFlagActive = peSitesForFlagActive;
    }

    public Set getPeStudentsForDegreeEnglishType() {
        return this.peStudentsForDegreeEnglishType;
    }
    
    public void setPeStudentsForDegreeEnglishType(Set peStudentsForDegreeEnglishType) {
        this.peStudentsForDegreeEnglishType = peStudentsForDegreeEnglishType;
    }

    public Set getSsoUsersForFlagIsvalid() {
        return this.ssoUsersForFlagIsvalid;
    }
    
    public void setSsoUsersForFlagIsvalid(Set ssoUsersForFlagIsvalid) {
        this.ssoUsersForFlagIsvalid = ssoUsersForFlagIsvalid;
    }

    public Set getPeTchProgramsForFlagDegreeCandisobey() {
        return this.peTchProgramsForFlagDegreeCandisobey;
    }
    
    public void setPeTchProgramsForFlagDegreeCandisobey(Set peTchProgramsForFlagDegreeCandisobey) {
        this.peTchProgramsForFlagDegreeCandisobey = peTchProgramsForFlagDegreeCandisobey;
    }

    public Set getPeTeachersForFlagActive() {
        return this.peTeachersForFlagActive;
    }
    
    public void setPeTeachersForFlagActive(Set peTeachersForFlagActive) {
        this.peTeachersForFlagActive = peTeachersForFlagActive;
    }

    public Set getPeRecExamcoursesForFlagArrangeRoom() {
        return this.peRecExamcoursesForFlagArrangeRoom;
    }
    
    public void setPeRecExamcoursesForFlagArrangeRoom(Set peRecExamcoursesForFlagArrangeRoom) {
        this.peRecExamcoursesForFlagArrangeRoom = peRecExamcoursesForFlagArrangeRoom;
    }

    public Set getPeSmsInfosForFlagSmsStatus() {
        return this.peSmsInfosForFlagSmsStatus;
    }
    
    public void setPeSmsInfosForFlagSmsStatus(Set peSmsInfosForFlagSmsStatus) {
        this.peSmsInfosForFlagSmsStatus = peSmsInfosForFlagSmsStatus;
    }

    public Set getPrTchCourseTeachersForFlagBak() {
        return this.prTchCourseTeachersForFlagBak;
    }
    
    public void setPrTchCourseTeachersForFlagBak(Set prTchCourseTeachersForFlagBak) {
        this.prTchCourseTeachersForFlagBak = prTchCourseTeachersForFlagBak;
    }

    public Set getPeSmsSystempointsForFlagSmsStatus() {
        return this.peSmsSystempointsForFlagSmsStatus;
    }
    
    public void setPeSmsSystempointsForFlagSmsStatus(Set peSmsSystempointsForFlagSmsStatus) {
        this.peSmsSystempointsForFlagSmsStatus = peSmsSystempointsForFlagSmsStatus;
    }

    public Set getPrExamStuMaincoursesForFlagScorePub() {
        return this.prExamStuMaincoursesForFlagScorePub;
    }
    
    public void setPrExamStuMaincoursesForFlagScorePub(Set prExamStuMaincoursesForFlagScorePub) {
        this.prExamStuMaincoursesForFlagScorePub = prExamStuMaincoursesForFlagScorePub;
    }

    public Set getPrExamStuMaincoursesForFlagScoreStatus() {
        return this.prExamStuMaincoursesForFlagScoreStatus;
    }
    
    public void setPrExamStuMaincoursesForFlagScoreStatus(Set prExamStuMaincoursesForFlagScoreStatus) {
        this.prExamStuMaincoursesForFlagScoreStatus = prExamStuMaincoursesForFlagScoreStatus;
    }

    public Set getPeRecExamcoursesForFlagBak() {
        return this.peRecExamcoursesForFlagBak;
    }
    
    public void setPeRecExamcoursesForFlagBak(Set peRecExamcoursesForFlagBak) {
        this.peRecExamcoursesForFlagBak = peRecExamcoursesForFlagBak;
    }

    public Set getPeTchCoursewaresForFlagIsvalid() {
        return this.peTchCoursewaresForFlagIsvalid;
    }
    
    public void setPeTchCoursewaresForFlagIsvalid(Set peTchCoursewaresForFlagIsvalid) {
        this.peTchCoursewaresForFlagIsvalid = peTchCoursewaresForFlagIsvalid;
    }

    public Set getPeRecStudentsForFlagRecChannel() {
        return this.peRecStudentsForFlagRecChannel;
    }
    
    public void setPeRecStudentsForFlagRecChannel(Set peRecStudentsForFlagRecChannel) {
        this.peRecStudentsForFlagRecChannel = peRecStudentsForFlagRecChannel;
    }

    public Set getSsoUsersForFlagBak() {
        return this.ssoUsersForFlagBak;
    }
    
    public void setSsoUsersForFlagBak(Set ssoUsersForFlagBak) {
        this.ssoUsersForFlagBak = ssoUsersForFlagBak;
    }

    public Set getPeRecStudentsForFlagXueliCheck() {
        return this.peRecStudentsForFlagXueliCheck;
    }
    
    public void setPeRecStudentsForFlagXueliCheck(Set peRecStudentsForFlagXueliCheck) {
        this.peRecStudentsForFlagXueliCheck = peRecStudentsForFlagXueliCheck;
    }

    public Set getPeRecStudentsForFlagMajorType() {
        return this.peRecStudentsForFlagMajorType;
    }
    
    public void setPeRecStudentsForFlagMajorType(Set peRecStudentsForFlagMajorType) {
        this.peRecStudentsForFlagMajorType = peRecStudentsForFlagMajorType;
    }

    public Set getPeSitemanagersForFlagIsvalid() {
        return this.peSitemanagersForFlagIsvalid;
    }
    
    public void setPeSitemanagersForFlagIsvalid(Set peSitemanagersForFlagIsvalid) {
        this.peSitemanagersForFlagIsvalid = peSitemanagersForFlagIsvalid;
    }

    public Set getPePriRolesForFlagRoleType() {
        return this.pePriRolesForFlagRoleType;
    }
    
    public void setPePriRolesForFlagRoleType(Set pePriRolesForFlagRoleType) {
        this.pePriRolesForFlagRoleType = pePriRolesForFlagRoleType;
    }

    public Set getPeRecStudentsForFlagTeacherStatus() {
        return this.peRecStudentsForFlagTeacherStatus;
    }
    
    public void setPeRecStudentsForFlagTeacherStatus(Set peRecStudentsForFlagTeacherStatus) {
        this.peRecStudentsForFlagTeacherStatus = peRecStudentsForFlagTeacherStatus;
    }

    public Set getPrDocumentsForFlagRead() {
        return this.prDocumentsForFlagRead;
    }
    
    public void setPrDocumentsForFlagRead(Set prDocumentsForFlagRead) {
        this.prDocumentsForFlagRead = prDocumentsForFlagRead;
    }

    public Set getPeRecStudentsForFlagTeacher() {
        return this.peRecStudentsForFlagTeacher;
    }
    
    public void setPeRecStudentsForFlagTeacher(Set peRecStudentsForFlagTeacher) {
        this.peRecStudentsForFlagTeacher = peRecStudentsForFlagTeacher;
    }

    public Set getPeBulletinsForFlagIsvalid() {
        return this.peBulletinsForFlagIsvalid;
    }
    
    public void setPeBulletinsForFlagIsvalid(Set peBulletinsForFlagIsvalid) {
        this.peBulletinsForFlagIsvalid = peBulletinsForFlagIsvalid;
    }

    public Set getPeRecStudentsForFlagMatriculate() {
        return this.peRecStudentsForFlagMatriculate;
    }
    
    public void setPeRecStudentsForFlagMatriculate(Set peRecStudentsForFlagMatriculate) {
        this.peRecStudentsForFlagMatriculate = peRecStudentsForFlagMatriculate;
    }

    public Set getPeManagersForFlagIsvalid() {
        return this.peManagersForFlagIsvalid;
    }
    
    public void setPeManagersForFlagIsvalid(Set peManagersForFlagIsvalid) {
        this.peManagersForFlagIsvalid = peManagersForFlagIsvalid;
    }

    public Set getPrStuChangeSchoolsForFlagBak() {
        return this.prStuChangeSchoolsForFlagBak;
    }
    
    public void setPrStuChangeSchoolsForFlagBak(Set prStuChangeSchoolsForFlagBak) {
        this.prStuChangeSchoolsForFlagBak = prStuChangeSchoolsForFlagBak;
    }

    public Set getPrVoteQuestionsForFlagQuestionType() {
        return this.prVoteQuestionsForFlagQuestionType;
    }
    
    public void setPrVoteQuestionsForFlagQuestionType(Set prVoteQuestionsForFlagQuestionType) {
        this.prVoteQuestionsForFlagQuestionType = prVoteQuestionsForFlagQuestionType;
    }

    public Set getPePcNewsesForFlagBak() {
        return this.pePcNewsesForFlagBak;
    }
    
    public void setPePcNewsesForFlagBak(Set pePcNewsesForFlagBak) {
        this.pePcNewsesForFlagBak = pePcNewsesForFlagBak;
    }

    public Set getPeRecStudentsForFlagRecStatus() {
        return this.peRecStudentsForFlagRecStatus;
    }
    
    public void setPeRecStudentsForFlagRecStatus(Set peRecStudentsForFlagRecStatus) {
        this.peRecStudentsForFlagRecStatus = peRecStudentsForFlagRecStatus;
    }

    public Set getPrBzzTchOpencourses() {
        return this.prBzzTchOpencourses;
    }
    
    public void setPrBzzTchOpencourses(Set prBzzTchOpencourses) {
        this.prBzzTchOpencourses = prBzzTchOpencourses;
    }

    public Set getPrFeeDetailsForFlagFeeType() {
        return this.prFeeDetailsForFlagFeeType;
    }
    
    public void setPrFeeDetailsForFlagFeeType(Set prFeeDetailsForFlagFeeType) {
        this.prFeeDetailsForFlagFeeType = prFeeDetailsForFlagFeeType;
    }

    public Set getPrFeeDetailsForFlagFeeCheck() {
        return this.prFeeDetailsForFlagFeeCheck;
    }
    
    public void setPrFeeDetailsForFlagFeeCheck(Set prFeeDetailsForFlagFeeCheck) {
        this.prFeeDetailsForFlagFeeCheck = prFeeDetailsForFlagFeeCheck;
    }

    public Set getPrVoteSuggestsForFlagBak() {
        return this.prVoteSuggestsForFlagBak;
    }
    
    public void setPrVoteSuggestsForFlagBak(Set prVoteSuggestsForFlagBak) {
        this.prVoteSuggestsForFlagBak = prVoteSuggestsForFlagBak;
    }

    public Set getPrVoteSuggestsForFlagCheck() {
        return this.prVoteSuggestsForFlagCheck;
    }
    
    public void setPrVoteSuggestsForFlagCheck(Set prVoteSuggestsForFlagCheck) {
        this.prVoteSuggestsForFlagCheck = prVoteSuggestsForFlagCheck;
    }

    public Set getPrVoteQuestionsForFlagBak() {
        return this.prVoteQuestionsForFlagBak;
    }
    
    public void setPrVoteQuestionsForFlagBak(Set prVoteQuestionsForFlagBak) {
        this.prVoteQuestionsForFlagBak = prVoteQuestionsForFlagBak;
    }

    public Set getPrBzzTchStuElectivesForFlagScorePub() {
        return this.prBzzTchStuElectivesForFlagScorePub;
    }
    
    public void setPrBzzTchStuElectivesForFlagScorePub(Set prBzzTchStuElectivesForFlagScorePub) {
        this.prBzzTchStuElectivesForFlagScorePub = prBzzTchStuElectivesForFlagScorePub;
    }

    public Set getSystemVariablesesForFlagPlatformSection() {
        return this.systemVariablesesForFlagPlatformSection;
    }
    
    public void setSystemVariablesesForFlagPlatformSection(Set systemVariablesesForFlagPlatformSection) {
        this.systemVariablesesForFlagPlatformSection = systemVariablesesForFlagPlatformSection;
    }

    public Set getSystemAppliesForApplyType() {
        return this.systemAppliesForApplyType;
    }
    
    public void setSystemAppliesForApplyType(Set systemAppliesForApplyType) {
        this.systemAppliesForApplyType = systemAppliesForApplyType;
    }

    public Set getPrBzzTchStuElectivesForFlagScoreStatus() {
        return this.prBzzTchStuElectivesForFlagScoreStatus;
    }
    
    public void setPrBzzTchStuElectivesForFlagScoreStatus(Set prBzzTchStuElectivesForFlagScoreStatus) {
        this.prBzzTchStuElectivesForFlagScoreStatus = prBzzTchStuElectivesForFlagScoreStatus;
    }

    public Set getPrTchStuPapersForFlagSyllabusLastUpdate() {
        return this.prTchStuPapersForFlagSyllabusLastUpdate;
    }
    
    public void setPrTchStuPapersForFlagSyllabusLastUpdate(Set prTchStuPapersForFlagSyllabusLastUpdate) {
        this.prTchStuPapersForFlagSyllabusLastUpdate = prTchStuPapersForFlagSyllabusLastUpdate;
    }

    public Set getPeTeachersForFlagPaper() {
        return this.peTeachersForFlagPaper;
    }
    
    public void setPeTeachersForFlagPaper(Set peTeachersForFlagPaper) {
        this.peTeachersForFlagPaper = peTeachersForFlagPaper;
    }

    public Set getPeManagersForGender() {
        return this.peManagersForGender;
    }
    
    public void setPeManagersForGender(Set peManagersForGender) {
        this.peManagersForGender = peManagersForGender;
    }

    public Set getPeEnterpriseManagersForFlagIsvalid() {
        return this.peEnterpriseManagersForFlagIsvalid;
    }
    
    public void setPeEnterpriseManagersForFlagIsvalid(Set peEnterpriseManagersForFlagIsvalid) {
        this.peEnterpriseManagersForFlagIsvalid = peEnterpriseManagersForFlagIsvalid;
    }

    public Set getPrPcElectivesForFlagBak() {
        return this.prPcElectivesForFlagBak;
    }
    
    public void setPrPcElectivesForFlagBak(Set prPcElectivesForFlagBak) {
        this.prPcElectivesForFlagBak = prPcElectivesForFlagBak;
    }

    public Set getPeRecStudentsForFlagNoexam() {
        return this.peRecStudentsForFlagNoexam;
    }
    
    public void setPeRecStudentsForFlagNoexam(Set peRecStudentsForFlagNoexam) {
        this.peRecStudentsForFlagNoexam = peRecStudentsForFlagNoexam;
    }

    public Set getPeRecStudentsForFlagNoexamStatus() {
        return this.peRecStudentsForFlagNoexamStatus;
    }
    
    public void setPeRecStudentsForFlagNoexamStatus(Set peRecStudentsForFlagNoexamStatus) {
        this.peRecStudentsForFlagNoexamStatus = peRecStudentsForFlagNoexamStatus;
    }

    public Set getPeRecStudentsForFlagPublish() {
        return this.peRecStudentsForFlagPublish;
    }
    
    public void setPeRecStudentsForFlagPublish(Set peRecStudentsForFlagPublish) {
        this.peRecStudentsForFlagPublish = peRecStudentsForFlagPublish;
    }

    public Set getPeMajorsForFlagIsEducation() {
        return this.peMajorsForFlagIsEducation;
    }
    
    public void setPeMajorsForFlagIsEducation(Set peMajorsForFlagIsEducation) {
        this.peMajorsForFlagIsEducation = peMajorsForFlagIsEducation;
    }

    public Set getPeInfoNewsesForFlagIsactive() {
        return this.peInfoNewsesForFlagIsactive;
    }
    
    public void setPeInfoNewsesForFlagIsactive(Set peInfoNewsesForFlagIsactive) {
        this.peInfoNewsesForFlagIsactive = peInfoNewsesForFlagIsactive;
    }

    public Set getPeExamPatrolsForFlagIsJiankao() {
        return this.peExamPatrolsForFlagIsJiankao;
    }
    
    public void setPeExamPatrolsForFlagIsJiankao(Set peExamPatrolsForFlagIsJiankao) {
        this.peExamPatrolsForFlagIsJiankao = peExamPatrolsForFlagIsJiankao;
    }

    public Set getPeSitemanagersForGender() {
        return this.peSitemanagersForGender;
    }
    
    public void setPeSitemanagersForGender(Set peSitemanagersForGender) {
        this.peSitemanagersForGender = peSitemanagersForGender;
    }

    public Set getPeBzzTchCoursewaresForFlagIsvalid() {
        return this.peBzzTchCoursewaresForFlagIsvalid;
    }
    
    public void setPeBzzTchCoursewaresForFlagIsvalid(Set peBzzTchCoursewaresForFlagIsvalid) {
        this.peBzzTchCoursewaresForFlagIsvalid = peBzzTchCoursewaresForFlagIsvalid;
    }

    public Set getPeTeachersForGender() {
        return this.peTeachersForGender;
    }
    
    public void setPeTeachersForGender(Set peTeachersForGender) {
        this.peTeachersForGender = peTeachersForGender;
    }

    public Set getPrTchStuPapersForFlagDraftALastUpdate() {
        return this.prTchStuPapersForFlagDraftALastUpdate;
    }
    
    public void setPrTchStuPapersForFlagDraftALastUpdate(Set prTchStuPapersForFlagDraftALastUpdate) {
        this.prTchStuPapersForFlagDraftALastUpdate = prTchStuPapersForFlagDraftALastUpdate;
    }

    public Set getPePcTeachersForFlagTeacherType() {
        return this.pePcTeachersForFlagTeacherType;
    }
    
    public void setPePcTeachersForFlagTeacherType(Set pePcTeachersForFlagTeacherType) {
        this.pePcTeachersForFlagTeacherType = pePcTeachersForFlagTeacherType;
    }

    public Set getPeTeachersForFlagMaxXueli() {
        return this.peTeachersForFlagMaxXueli;
    }
    
    public void setPeTeachersForFlagMaxXueli(Set peTeachersForFlagMaxXueli) {
        this.peTeachersForFlagMaxXueli = peTeachersForFlagMaxXueli;
    }

    public Set getPeSmsSystempointsForFlagIsauto() {
        return this.peSmsSystempointsForFlagIsauto;
    }
    
    public void setPeSmsSystempointsForFlagIsauto(Set peSmsSystempointsForFlagIsauto) {
        this.peSmsSystempointsForFlagIsauto = peSmsSystempointsForFlagIsauto;
    }

    public Set getPrPcElectivesForFlagEnrol() {
        return this.prPcElectivesForFlagEnrol;
    }
    
    public void setPrPcElectivesForFlagEnrol(Set prPcElectivesForFlagEnrol) {
        this.prPcElectivesForFlagEnrol = prPcElectivesForFlagEnrol;
    }

    public Set getPeTchCoursesForFlagIsvalid() {
        return this.peTchCoursesForFlagIsvalid;
    }
    
    public void setPeTchCoursesForFlagIsvalid(Set peTchCoursesForFlagIsvalid) {
        this.peTchCoursesForFlagIsvalid = peTchCoursesForFlagIsvalid;
    }

    public Set getSystemAppliesForFlagApplyStatus() {
        return this.systemAppliesForFlagApplyStatus;
    }
    
    public void setSystemAppliesForFlagApplyStatus(Set systemAppliesForFlagApplyStatus) {
        this.systemAppliesForFlagApplyStatus = systemAppliesForFlagApplyStatus;
    }

    public Set getPeTchCoursewaresForFlagBak() {
        return this.peTchCoursewaresForFlagBak;
    }
    
    public void setPeTchCoursewaresForFlagBak(Set peTchCoursewaresForFlagBak) {
        this.peTchCoursewaresForFlagBak = peTchCoursewaresForFlagBak;
    }

    public Set getPeTeachersForFlagMaxXuewei() {
        return this.peTeachersForFlagMaxXuewei;
    }
    
    public void setPeTeachersForFlagMaxXuewei(Set peTeachersForFlagMaxXuewei) {
        this.peTeachersForFlagMaxXuewei = peTeachersForFlagMaxXuewei;
    }

    public Set getPeTeachersForFlagZhicheng() {
        return this.peTeachersForFlagZhicheng;
    }
    
    public void setPeTeachersForFlagZhicheng(Set peTeachersForFlagZhicheng) {
        this.peTeachersForFlagZhicheng = peTeachersForFlagZhicheng;
    }

    public Set getPeInfoNewsesForFlagNewsStatus() {
        return this.peInfoNewsesForFlagNewsStatus;
    }
    
    public void setPeInfoNewsesForFlagNewsStatus(Set peInfoNewsesForFlagNewsStatus) {
        this.peInfoNewsesForFlagNewsStatus = peInfoNewsesForFlagNewsStatus;
    }

    public Set getPePcTeachersForFlagBak() {
        return this.pePcTeachersForFlagBak;
    }
    
    public void setPePcTeachersForFlagBak(Set pePcTeachersForFlagBak) {
        this.pePcTeachersForFlagBak = pePcTeachersForFlagBak;
    }

    public Set getPeDocumentsForFlagBak() {
        return this.peDocumentsForFlagBak;
    }
    
    public void setPeDocumentsForFlagBak(Set peDocumentsForFlagBak) {
        this.peDocumentsForFlagBak = peDocumentsForFlagBak;
    }

    public Set getPrTchPaperContentsForFlagPaperSection() {
        return this.prTchPaperContentsForFlagPaperSection;
    }
    
    public void setPrTchPaperContentsForFlagPaperSection(Set prTchPaperContentsForFlagPaperSection) {
        this.prTchPaperContentsForFlagPaperSection = prTchPaperContentsForFlagPaperSection;
    }

    public Set getPeDocumentsForFlagDel() {
        return this.peDocumentsForFlagDel;
    }
    
    public void setPeDocumentsForFlagDel(Set peDocumentsForFlagDel) {
        this.peDocumentsForFlagDel = peDocumentsForFlagDel;
    }

    public Set getPeFeeLevelsForFlagBak() {
        return this.peFeeLevelsForFlagBak;
    }
    
    public void setPeFeeLevelsForFlagBak(Set peFeeLevelsForFlagBak) {
        this.peFeeLevelsForFlagBak = peFeeLevelsForFlagBak;
    }

    public Set getPrExamBookingsForFlagScoreStatusa() {
        return this.prExamBookingsForFlagScoreStatusa;
    }
    
    public void setPrExamBookingsForFlagScoreStatusa(Set prExamBookingsForFlagScoreStatusa) {
        this.prExamBookingsForFlagScoreStatusa = prExamBookingsForFlagScoreStatusa;
    }

    public Set getPrTchProgramCoursesForFlagBak() {
        return this.prTchProgramCoursesForFlagBak;
    }
    
    public void setPrTchProgramCoursesForFlagBak(Set prTchProgramCoursesForFlagBak) {
        this.prTchProgramCoursesForFlagBak = prTchProgramCoursesForFlagBak;
    }

    public Set getPrExamBookingsForFlagScoreStatus() {
        return this.prExamBookingsForFlagScoreStatus;
    }
    
    public void setPrExamBookingsForFlagScoreStatus(Set prExamBookingsForFlagScoreStatus) {
        this.prExamBookingsForFlagScoreStatus = prExamBookingsForFlagScoreStatus;
    }

    public Set getPrTchProgramCoursesForFlagIsMainCourse() {
        return this.prTchProgramCoursesForFlagIsMainCourse;
    }
    
    public void setPrTchProgramCoursesForFlagIsMainCourse(Set prTchProgramCoursesForFlagIsMainCourse) {
        this.prTchProgramCoursesForFlagIsMainCourse = prTchProgramCoursesForFlagIsMainCourse;
    }

    public Set getPrCourseArrangesForFlagCourseSection() {
        return this.prCourseArrangesForFlagCourseSection;
    }
    
    public void setPrCourseArrangesForFlagCourseSection(Set prCourseArrangesForFlagCourseSection) {
        this.prCourseArrangesForFlagCourseSection = prCourseArrangesForFlagCourseSection;
    }

    public Set getHomeworkHistoriesForFlagIscheck() {
        return this.homeworkHistoriesForFlagIscheck;
    }
    
    public void setHomeworkHistoriesForFlagIscheck(Set homeworkHistoriesForFlagIscheck) {
        this.homeworkHistoriesForFlagIscheck = homeworkHistoriesForFlagIscheck;
    }

    public Set getHomeworkInfosForFlagBak() {
        return this.homeworkInfosForFlagBak;
    }
    
    public void setHomeworkInfosForFlagBak(Set homeworkInfosForFlagBak) {
        this.homeworkInfosForFlagBak = homeworkInfosForFlagBak;
    }

    public Set getHomeworkHistoriesForFlagBak() {
        return this.homeworkHistoriesForFlagBak;
    }
    
    public void setHomeworkHistoriesForFlagBak(Set homeworkHistoriesForFlagBak) {
        this.homeworkHistoriesForFlagBak = homeworkHistoriesForFlagBak;
    }

    public Set getPrExamBookingsForFlagScoreStatusb() {
        return this.prExamBookingsForFlagScoreStatusb;
    }
    
    public void setPrExamBookingsForFlagScoreStatusb(Set prExamBookingsForFlagScoreStatusb) {
        this.prExamBookingsForFlagScoreStatusb = prExamBookingsForFlagScoreStatusb;
    }

    public Set getPeBzzTchCoursesForFlagCoursetype() {
        return this.peBzzTchCoursesForFlagCoursetype;
    }
    
    public void setPeBzzTchCoursesForFlagCoursetype(Set peBzzTchCoursesForFlagCoursetype) {
        this.peBzzTchCoursesForFlagCoursetype = peBzzTchCoursesForFlagCoursetype;
    }

    public Set getPeBzzTchCoursesForFlagIsvalid() {
        return this.peBzzTchCoursesForFlagIsvalid;
    }
    
    public void setPeBzzTchCoursesForFlagIsvalid(Set peBzzTchCoursesForFlagIsvalid) {
        this.peBzzTchCoursesForFlagIsvalid = peBzzTchCoursesForFlagIsvalid;
    }

    public Set getPeFeeLevelsForFlagDefault() {
        return this.peFeeLevelsForFlagDefault;
    }
    
    public void setPeFeeLevelsForFlagDefault(Set peFeeLevelsForFlagDefault) {
        this.peFeeLevelsForFlagDefault = peFeeLevelsForFlagDefault;
    }

    public Set getPeTchCoursesForFlagIspubliccourse() {
        return this.peTchCoursesForFlagIspubliccourse;
    }
    
    public void setPeTchCoursesForFlagIspubliccourse(Set peTchCoursesForFlagIspubliccourse) {
        this.peTchCoursesForFlagIspubliccourse = peTchCoursesForFlagIspubliccourse;
    }

    public Set getPeTchProgramsForFlagUniteA() {
        return this.peTchProgramsForFlagUniteA;
    }
    
    public void setPeTchProgramsForFlagUniteA(Set peTchProgramsForFlagUniteA) {
        this.peTchProgramsForFlagUniteA = peTchProgramsForFlagUniteA;
    }

    public Set getPeTchProgramsForFlagUniteB() {
        return this.peTchProgramsForFlagUniteB;
    }
    
    public void setPeTchProgramsForFlagUniteB(Set peTchProgramsForFlagUniteB) {
        this.peTchProgramsForFlagUniteB = peTchProgramsForFlagUniteB;
    }

    public Set getPeTchProgramsForFlagMajorType() {
        return this.peTchProgramsForFlagMajorType;
    }
    
    public void setPeTchProgramsForFlagMajorType(Set peTchProgramsForFlagMajorType) {
        this.peTchProgramsForFlagMajorType = peTchProgramsForFlagMajorType;
    }

    public Set getPeEnterpriseManagersForGender() {
        return this.peEnterpriseManagersForGender;
    }
    
    public void setPeEnterpriseManagersForGender(Set peEnterpriseManagersForGender) {
        this.peEnterpriseManagersForGender = peEnterpriseManagersForGender;
    }

    public Set getPrTchPaperContentsForFlagActionUser() {
        return this.prTchPaperContentsForFlagActionUser;
    }
    
    public void setPrTchPaperContentsForFlagActionUser(Set prTchPaperContentsForFlagActionUser) {
        this.prTchPaperContentsForFlagActionUser = prTchPaperContentsForFlagActionUser;
    }

    public Set getPePriRolesForFlagBak() {
        return this.pePriRolesForFlagBak;
    }
    
    public void setPePriRolesForFlagBak(Set pePriRolesForFlagBak) {
        this.pePriRolesForFlagBak = pePriRolesForFlagBak;
    }

    public Set getHomeworkInfosForFlagIsvalid() {
        return this.homeworkInfosForFlagIsvalid;
    }
    
    public void setHomeworkInfosForFlagIsvalid(Set homeworkInfosForFlagIsvalid) {
        this.homeworkInfosForFlagIsvalid = homeworkInfosForFlagIsvalid;
    }

    public Set getPeSmsInfosForFlagSmsType() {
        return this.peSmsInfosForFlagSmsType;
    }
    
    public void setPeSmsInfosForFlagSmsType(Set peSmsInfosForFlagSmsType) {
        this.peSmsInfosForFlagSmsType = peSmsInfosForFlagSmsType;
    }

    public Set getPeBulletinsForFlagIstop() {
        return this.peBulletinsForFlagIstop;
    }
    
    public void setPeBulletinsForFlagIstop(Set peBulletinsForFlagIstop) {
        this.peBulletinsForFlagIstop = peBulletinsForFlagIstop;
    }

    public Set getPrDocumentsForFlagDel() {
        return this.prDocumentsForFlagDel;
    }
    
    public void setPrDocumentsForFlagDel(Set prDocumentsForFlagDel) {
        this.prDocumentsForFlagDel = prDocumentsForFlagDel;
    }

    public Set getPrTchOpencoursesForFlagExamCourse() {
        return this.prTchOpencoursesForFlagExamCourse;
    }
    
    public void setPrTchOpencoursesForFlagExamCourse(Set prTchOpencoursesForFlagExamCourse) {
        this.prTchOpencoursesForFlagExamCourse = prTchOpencoursesForFlagExamCourse;
    }

    public Set getPrTchStuPapersForFlagTitleAdmission() {
        return this.prTchStuPapersForFlagTitleAdmission;
    }
    
    public void setPrTchStuPapersForFlagTitleAdmission(Set prTchStuPapersForFlagTitleAdmission) {
        this.prTchStuPapersForFlagTitleAdmission = prTchStuPapersForFlagTitleAdmission;
    }

    public Set getPrTchStuPapersForFlagPaperRejoin() {
        return this.prTchStuPapersForFlagPaperRejoin;
    }
    
    public void setPrTchStuPapersForFlagPaperRejoin(Set prTchStuPapersForFlagPaperRejoin) {
        this.prTchStuPapersForFlagPaperRejoin = prTchStuPapersForFlagPaperRejoin;
    }

    public Set getPrTchCourseTeachersForFlagTeacherType() {
        return this.prTchCourseTeachersForFlagTeacherType;
    }
    
    public void setPrTchCourseTeachersForFlagTeacherType(Set prTchCourseTeachersForFlagTeacherType) {
        this.prTchCourseTeachersForFlagTeacherType = prTchCourseTeachersForFlagTeacherType;
    }

    public Set getPeVotePapersForFlagCanSuggest() {
        return this.peVotePapersForFlagCanSuggest;
    }
    
    public void setPeVotePapersForFlagCanSuggest(Set peVotePapersForFlagCanSuggest) {
        this.peVotePapersForFlagCanSuggest = peVotePapersForFlagCanSuggest;
    }

	public Set getPeBzzTchCourseForFlagCourseCategory() {
		return peBzzTchCourseForFlagCourseCategory;
	}

	public void setPeBzzTchCourseForFlagCourseCategory(
			Set peBzzTchCourseForFlagCourseCategory) {
		this.peBzzTchCourseForFlagCourseCategory = peBzzTchCourseForFlagCourseCategory;
	}

	public Set getPeBzzFaxInfoForFlagFpMailState() {
		return peBzzFaxInfoForFlagFpMailState;
	}

	public void setPeBzzFaxInfoForFlagFpMailState(Set peBzzFaxInfoForFlagFpMailState) {
		this.peBzzFaxInfoForFlagFpMailState = peBzzFaxInfoForFlagFpMailState;
	}

	public Set getPeBzzFaxInfoForFlagFpOpenState() {
		return peBzzFaxInfoForFlagFpOpenState;
	}

	public void setPeBzzFaxInfoForFlagFpOpenState(Set peBzzFaxInfoForFlagFpOpenState) {
		this.peBzzFaxInfoForFlagFpOpenState = peBzzFaxInfoForFlagFpOpenState;
	}
   

	public Set getPeBzzMailInfoForFlagMailSendState() {
		return peBzzMailInfoForFlagMailSendState;
	}

	public void setPeBzzMailInfoForFlagMailSendState(
			Set peBzzMailInfoForFlagMailSendState) {
		this.peBzzMailInfoForFlagMailSendState = peBzzMailInfoForFlagMailSendState;
	}

	public Set getPeBzzMailInfoForFlatContainInvoiceState() {
		return peBzzMailInfoForFlatContainInvoiceState;
	}

	public void setPeBzzMailInfoForFlatContainInvoiceState(
			Set peBzzMailInfoForFlatContainInvoiceState) {
		this.peBzzMailInfoForFlatContainInvoiceState = peBzzMailInfoForFlatContainInvoiceState;
	}

	public Set getPeBzzRecruitForFlagRegistState() {
		return peBzzRecruitForFlagRegistState;
	}

	public void setPeBzzRecruitForFlagRegistState(Set peBzzRecruitForFlagRegistState) {
		this.peBzzRecruitForFlagRegistState = peBzzRecruitForFlagRegistState;
	}

	public Set getPeBzzStudentForFlagRankState() {
		return peBzzStudentForFlagRankState;
	}

	public void setPeBzzStudentForFlagRankState(Set peBzzStudentForFlagRankState) {
		this.peBzzStudentForFlagRankState = peBzzStudentForFlagRankState;
	}

	public Set getPeEnterpriseForFlagElective() {
		return peEnterpriseForFlagElective;
	}

	public void setPeEnterpriseForFlagElective(Set peEnterpriseForFlagElective) {
		this.peEnterpriseForFlagElective = peEnterpriseForFlagElective;
	}

	public Set getPeBzzGoodStuForFlaggoodState() {
		return peBzzGoodStuForFlaggoodState;
	}

	public void setPeBzzGoodStuForFlaggoodState(Set peBzzGoodStuForFlaggoodState) {
		this.peBzzGoodStuForFlaggoodState = peBzzGoodStuForFlaggoodState;
	}

	public Set getPeBzzGoodMagForFlaggoodState() {
		return peBzzGoodMagForFlaggoodState;
	}

	public void setPeBzzGoodMagForFlaggoodState(Set peBzzGoodMagForFlaggoodState) {
		this.peBzzGoodMagForFlaggoodState = peBzzGoodMagForFlaggoodState;
	}

	public Set getPeBzzPartyForFlagPartyState() {
		return peBzzPartyForFlagPartyState;
	}

	public void setPeBzzPartyForFlagPartyState(Set peBzzPartyForFlagPartyState) {
		this.peBzzPartyForFlagPartyState = peBzzPartyForFlagPartyState;
	}

	public Set getPeGradeForFlagIsvalid() {
		return peGradeForFlagIsvalid;
	}

	public void setPeGradeForFlagIsvalid(Set peGradeForFlagIsvalid) {
		this.peGradeForFlagIsvalid = peGradeForFlagIsvalid;
	}

	public Set getPeBzzBatchs() {
		return peBzzBatchs;
	}

	public void setPeBzzBatchs(Set peBzzBatchs) {
		this.peBzzBatchs = peBzzBatchs;
	}

	public Set getPeBzzOrderInfoFlagOrderType() {
		return peBzzOrderInfoFlagOrderType;
	}

	public void setPeBzzOrderInfoFlagOrderType(Set peBzzOrderInfoFlagOrderType) {
		this.peBzzOrderInfoFlagOrderType = peBzzOrderInfoFlagOrderType;
	}
	public Set getPrBzzTchStuElectiveFlagElectivePayStatus() {
		return prBzzTchStuElectiveFlagElectivePayStatus;
	}

	public void setPrBzzTchStuElectiveFlagElectivePayStatus(
			Set prBzzTchStuElectiveFlagElectivePayStatus) {
		prBzzTchStuElectiveFlagElectivePayStatus = prBzzTchStuElectiveFlagElectivePayStatus;
	}
	public Set getPeBzzOrderInfoRefundState() {
		return peBzzOrderInfoRefundState;
	}

	public void setPeBzzOrderInfoRefundState(Set peBzzOrderInfoRefundState) {
		this.peBzzOrderInfoRefundState = peBzzOrderInfoRefundState;
	}

	public Set getPeBzzTchCoursesForFlagIsvisitAfterPass() {
		return peBzzTchCoursesForFlagIsvisitAfterPass;
	}

	public void setPeBzzTchCoursesForFlagIsvisitAfterPass(
			Set peBzzTchCoursesForFlagIsvisitAfterPass) {
		this.peBzzTchCoursesForFlagIsvisitAfterPass = peBzzTchCoursesForFlagIsvisitAfterPass;
	}

	public Set getPeBzzTchCoursesForFlagIsFree() {
		return peBzzTchCoursesForFlagIsFree;
	}

	public void setPeBzzTchCoursesForFlagIsFree(Set peBzzTchCoursesForFlagIsFree) {
		this.peBzzTchCoursesForFlagIsFree = peBzzTchCoursesForFlagIsFree;
	}

	public Set getPeBzzTchCoursesForFlagIsRecommend() {
		return peBzzTchCoursesForFlagIsRecommend;
	}

	public void setPeBzzTchCoursesForFlagIsRecommend(
			Set peBzzTchCoursesForFlagIsRecommend) {
		this.peBzzTchCoursesForFlagIsRecommend = peBzzTchCoursesForFlagIsRecommend;
	}

	public Set getPeElectiveCoursePeriodFlagElePeriodPayStatus() {
		return peElectiveCoursePeriodFlagElePeriodPayStatus;
	}

	public void setPeElectiveCoursePeriodFlagElePeriodPayStatus(
			Set peElectiveCoursePeriodFlagElePeriodPayStatus) {
		this.peElectiveCoursePeriodFlagElePeriodPayStatus = peElectiveCoursePeriodFlagElePeriodPayStatus;
	}

	public Set getStuBatchFlagBatchPayStates() {
		return stuBatchFlagBatchPayStates;
	}

	public void setStuBatchFlagBatchPayStates(Set stuBatchFlagBatchPayStates) {
		this.stuBatchFlagBatchPayStates = stuBatchFlagBatchPayStates;
	}

	public Set getPeBzzTchCoursFlagCanJoinBatch() {
		return peBzzTchCoursFlagCanJoinBatch;
	}

	public void setPeBzzTchCoursFlagCanJoinBatch(Set peBzzTchCoursFlagCanJoinBatch) {
		this.peBzzTchCoursFlagCanJoinBatch = peBzzTchCoursFlagCanJoinBatch;
	}

	public Set getPeBzzInvoiceFlagPrint() {
		return peBzzInvoiceFlagPrint;
	}

	public void setPeBzzInvoiceFlagPrint(Set peBzzInvoiceFlagPrint) {
		this.peBzzInvoiceFlagPrint = peBzzInvoiceFlagPrint;
	}
}