package com.whaty.platform.entity.bean;


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;



/**
 * PeBzzTchCourse generated by MyEclipse - Hibernate Tools
 */

public class PeBalanceHistory extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {


    // Fields    

     private String id;
     private SsoUser ssoUser;
     private PeBzzOrderInfo peBzzOrderInfo;
     private Double classHour;
     private Double amountNum;
     private Date operateDate;
     private String note;
     private String note2;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public SsoUser getSsoUser() {
		return ssoUser;
	}
	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}
	public PeBzzOrderInfo getPeBzzOrderInfo() {
		return peBzzOrderInfo;
	}
	public void setPeBzzOrderInfo(PeBzzOrderInfo peBzzOrderInfo) {
		this.peBzzOrderInfo = peBzzOrderInfo;
	}
	public Double getClassHour() {
		return classHour;
	}
	public void setClassHour(Double classHour) {
		this.classHour = classHour;
	}
	public Double getAmountNum() {
		return amountNum;
	}
	public void setAmountNum(Double amountNum) {
		this.amountNum = amountNum;
	}
	public Date getOperateDate() {
		return operateDate;
	}
	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public String getNote2() {
		return note2;
	}
	public void setNote2(String note2) {
		this.note2 = note2;
	}
	
}