package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PeBulletin generated by MyEclipse Persistence Tools
 */

public class PeBulletin extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields
	/*主键 ID*/
	private String id;
	/*是否有效*/
	private EnumConst enumConstByFlagIsvalid;
	/*是否置顶*/
	private EnumConst enumConstByFlagIstop;
	/*协会管理员表*/
	private PeManager peManager;
	/*开发库中表没有数据，不知道做什么用*/
	private PeSitemanager peSitemanager;
	/*机构表 管理员*/
	private PeEnterpriseManager enterpriseManager;
	/*通知标题*/
 	private String title;
 	/*发布日期*/
	private Date publishDate;
	/*修改日期*/
	private Date updateDate;
	/*公告内容*/
	private String note;
	/*发布范围*/
	private String scopeString;
	/*发布人*/
	private String publisher;   //后来添加
	/*公告是否为最新*/
	private EnumConst enumConstByFlagIsNew;
	/*机构表*/
	private PeEnterprise peSite;

	// Constructors

	/** default constructor */
	public PeBulletin() {
	}

	/** minimal constructor */
	public PeBulletin(String title) {
		this.title = title;
	}

	/** full constructor */
	public PeBulletin(EnumConst enumConstByFlagIsvalid,
			EnumConst enumConstByFlagIstop, PeManager peManager,PeEnterpriseManager enterpriseManager,PeSitemanager peSitemanager,String title,
			Date publishDate, Date updateDate, String note, String scopeString) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.enumConstByFlagIstop = enumConstByFlagIstop;
		this.peManager = peManager;
		this.peSitemanager =peSitemanager;
		this.enterpriseManager=enterpriseManager;
		this.title = title;
		this.publishDate = publishDate;
		this.updateDate = updateDate;
		this.note = note;
		this.scopeString = scopeString;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public EnumConst getEnumConstByFlagIstop() {
		return this.enumConstByFlagIstop;
	}

	public void setEnumConstByFlagIstop(EnumConst enumConstByFlagIstop) {
		this.enumConstByFlagIstop = enumConstByFlagIstop;
	}

	public PeManager getPeManager() {
		return this.peManager;
	}

	public void setPeManager(PeManager peManager) {
		this.peManager = peManager;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getScopeString() {
		return this.scopeString;
	}

	public void setScopeString(String scopeString) {
		this.scopeString = scopeString;
	}

	public PeSitemanager getPeSitemanager() {
		return peSitemanager;
	}

	public void setPeSitemanager(PeSitemanager peSitemanager) {
		this.peSitemanager = peSitemanager;
	}

	public PeEnterpriseManager getEnterpriseManager() {
		return enterpriseManager;
	}

	public void setEnterpriseManager(PeEnterpriseManager enterpriseManager) {
		this.enterpriseManager = enterpriseManager;
	}

	public EnumConst getEnumConstByFlagIsNew() {
		return enumConstByFlagIsNew;
	}

	public void setEnumConstByFlagIsNew(EnumConst enumConstByFlagIsNew) {
		this.enumConstByFlagIsNew = enumConstByFlagIsNew;
	}

	public PeEnterprise getPeSite() {
		return peSite;
	}

	public void setPeSite(PeEnterprise peSite) {
		this.peSite = peSite;
	}

	public String getPublisher() {
		return publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}
}