package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeBzzMailInfo extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private PeEnterprise peEnterprise; // 邮寄单位
	private String num; // 件数
	private EnumConst enumConstByFlagMailSendState; // 收发确认
	private String expressNo; // 快递单号
	private EnumConst enumConstByFlagContainInvoiceState; // 是否含发票

	private String bz; // 备注
	private Date luruDate;  //操作时间
	private String luruPeople; // 操作人
	
	private PeBzzBatch peBzzBatch; // 所在批次
	

	// Constructors

	/** default constructor */
	public PeBzzMailInfo() {
	}
	

	public PeBzzMailInfo(String id, PeEnterprise peEnterprise, String num,
			EnumConst enumConstByFlagMailSendState, String expressNo,
			EnumConst enumConstByFlagContainInvoiceState, String bz,
			Date luruDate, String luruPeople, PeBzzBatch peBzzBatch) {
		super();
		this.id = id;
		this.peEnterprise = peEnterprise;
		this.num = num;
		this.enumConstByFlagMailSendState = enumConstByFlagMailSendState;
		this.expressNo = expressNo;
		this.enumConstByFlagContainInvoiceState = enumConstByFlagContainInvoiceState;
		this.bz = bz;
		this.luruDate = luruDate;
		this.luruPeople = luruPeople;
		this.peBzzBatch = peBzzBatch;
	}





	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public PeEnterprise getPeEnterprise() {
		return peEnterprise;
	}


	public void setPeEnterprise(PeEnterprise peEnterprise) {
		this.peEnterprise = peEnterprise;
	}


	public String getNum() {
		return num;
	}


	public void setNum(String num) {
		this.num = num;
	}

	public String getExpressNo() {
		return expressNo;
	}


	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	public EnumConst getEnumConstByFlagMailSendState() {
		return enumConstByFlagMailSendState;
	}

	public void setEnumConstByFlagMailSendState(
			EnumConst enumConstByFlagMailSendState) {
		this.enumConstByFlagMailSendState = enumConstByFlagMailSendState;
	}


	public String getBz() {
		return bz;
	}


	public void setBz(String bz) {
		this.bz = bz;
	}


	public Date getLuruDate() {
		return luruDate;
	}


	public void setLuruDate(Date luruDate) {
		this.luruDate = luruDate;
	}


	public String getLuruPeople() {
		return luruPeople;
	}


	public void setLuruPeople(String luruPeople) {
		this.luruPeople = luruPeople;
	}


	public EnumConst getEnumConstByFlagContainInvoiceState() {
		return enumConstByFlagContainInvoiceState;
	}


	public void setEnumConstByFlagContainInvoiceState(
			EnumConst enumConstByFlagContainInvoiceState) {
		this.enumConstByFlagContainInvoiceState = enumConstByFlagContainInvoiceState;
	}


	public PeBzzBatch getPeBzzBatch() {
		return peBzzBatch;
	}


	public void setPeBzzBatch(PeBzzBatch peBzzBatch) {
		this.peBzzBatch = peBzzBatch;
	}
	
	

	
}