package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeBzzGoodStu extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields
	
	//  id  peBzzStudent  peBzzParty  work_age  duty  professional  work_space  advanced_story  photo_one  photo_two  certificate  enumConstByFlaggoodState  regard_num
	//  peManager  record_date
	private String id;
	private PeBzzStudent peBzzStudent; //fk_studentId 学员信息
	private PeBzzParty peBzzParty;//fk_partyId 政治面貌
	private String work_age;//工龄
	private String duty;//职务与工种
	private String professional;//职称
	private String work_space;//工作单位
	private String advanced_story;//type:clob先进事迹
	private String photo_one;//相片1
	private String photo_two;//相片2
	private String certificate;//所获奖项
	private EnumConst enumConstByFlaggoodState;//submit_status 审核状态
	private int regard_num;//关注度
	private PeManager peManager;//fk_record_userId 录入人信息
	private Date record_date;//录入时间
	private String feeling_words;//个人感言

	public String getFeeling_words() {
		return feeling_words;
	}

	public void setFeeling_words(String feeling_words) {
		this.feeling_words = feeling_words;
	}

	/** default constructor */
	public PeBzzGoodStu() {
	}

//  id  student  party  work_age  duty  professional  work_space  advanced_story  photo_one  photo_two  certificate  enumConstByFlaggoodState  regard_num
	//  manager  record_date  feeling_words
	
	/** full constructor */
	public PeBzzGoodStu(String id, PeBzzStudent peBzzStudent, PeBzzParty peBzzParty, String work_age, String duty, String professional, String work_space, 
			String advanced_story, String photo_one, String photo_two, String certificate, int regard_num, PeManager peManager, Date record_date , String feeling_words) {
		this.id = id ;
		this.peBzzStudent = peBzzStudent ;
		this.peBzzParty = peBzzParty ;
		this.work_age = work_age ;
		this.duty = duty ;
		this.professional = professional ;
		this.work_space = work_space ;
		this.advanced_story = advanced_story ;
		this.photo_one = photo_one ;
		this.photo_two = photo_two ;
		this.certificate = certificate ;
		this.regard_num = regard_num ;
		this.peManager = peManager ;
		this.record_date = record_date ;
		this.feeling_words = feeling_words ;
	}

	// Property accessors
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeBzzParty getPeBzzParty() {
		return peBzzParty;
	}

	public void setPeBzzParty(PeBzzParty peBzzParty) {
		this.peBzzParty = peBzzParty;
	}

	public String getWork_age() {
		return work_age;
	}

	public void setWork_age(String work_age) {
		this.work_age = work_age;
	}

	public String getDuty() {
		return duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getProfessional() {
		return professional;
	}

	public void setProfessional(String professional) {
		this.professional = professional;
	}

	public String getWork_space() {
		return work_space;
	}

	public void setWork_space(String work_space) {
		this.work_space = work_space;
	}

	public String getAdvanced_story() {
		return advanced_story;
	}

	public void setAdvanced_story(String advanced_story) {
		this.advanced_story = advanced_story;
	}

	public String getPhoto_one() {
		return photo_one;
	}

	public void setPhoto_one(String photo_one) {
		this.photo_one = photo_one;
	}

	public String getPhoto_two() {
		return photo_two;
	}

	public void setPhoto_two(String photo_two) {
		this.photo_two = photo_two;
	}

	public String getCertificate() {
		return certificate;
	}

	public void setCertificate(String certificate) {
		this.certificate = certificate;
	}

	public EnumConst getEnumConstByFlaggoodState() {
		return enumConstByFlaggoodState;
	}

	public void setEnumConstByFlaggoodState(EnumConst enumConstByFlaggoodState) {
		this.enumConstByFlaggoodState = enumConstByFlaggoodState;
	}

	public int getRegard_num() {
		return regard_num;
	}

	public void setRegard_num(int regard_num) {
		this.regard_num = regard_num;
	}
	
	public PeManager getPeManager() {
		return peManager;
	}

	public void setPeManager(PeManager peManager) {
		this.peManager = peManager;
	}

	public Date getRecord_date() {
		return record_date;
	}

	public void setRecord_date(Date record_date) {
		this.record_date = record_date;
	}

	public PeBzzStudent getPeBzzStudent() {
		return peBzzStudent;
	}

	public void setPeBzzStudent(PeBzzStudent peBzzStudent) {
		this.peBzzStudent = peBzzStudent;
	}

}