package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeBzzCommInfo extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private String regNo; // 学号
	private Date commDate;  //沟通时间
	private String finishTime; // 沟通时已完成学时
	private String bz; // 备注
	private Date luruDate;  //录入时间
	private String luruPeople; // 录入人
	
	private PeEnterprise peSite;	//管理员所在的企业
	
	// Constructors

	/** default constructor */
	public PeBzzCommInfo() {
	}

	/** full constructor */
	public PeBzzCommInfo(String id, String regNo, Date commDate,
			String finishTime, String bz, Date luruDate, String luruPeople) {
		this.id = id;
		this.regNo = regNo;
		this.commDate = commDate;
		this.finishTime = finishTime;
		this.bz = bz;
		this.luruDate = luruDate;
		this.luruPeople = luruPeople;
	}
	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBz() {
		return bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}


	public Date getLuruDate() {
		return luruDate;
	}

	public void setLuruDate(Date luruDate) {
		this.luruDate = luruDate;
	}

	public String getLuruPeople() {
		return luruPeople;
	}

	public void setLuruPeople(String luruPeople) {
		this.luruPeople = luruPeople;
	}

	public String getRegNo() {
		return regNo;
	}

	public void setRegNo(String regNo) {
		this.regNo = regNo;
	}

	public Date getCommDate() {
		return commDate;
	}

	public void setCommDate(Date commDate) {
		this.commDate = commDate;
	}

	public String getFinishTime() {
		return finishTime;
	}

	public void setFinishTime(String finishTime) {
		this.finishTime = finishTime;
	}

	public PeEnterprise getPeSite() {
		return peSite;
	}

	public void setPeSite(PeEnterprise peSite) {
		this.peSite = peSite;
	}
}