package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzTchCourse generated by MyEclipse - Hibernate Tools
 */

public class PeBzzTchCourse extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {

	// Fields
	/* 主键 */
	private String id;
	/* 课程编号 */
	private String code;
	/* 课程名称 */
	private String name;
	/* 是否有效 */
	private EnumConst enumConstByFlagIsvalid;
	/* 是否下线 */
	private EnumConst enumConstByFlagOffline;
	/* 课程性质 */
	private EnumConst enumConstByFlagCourseType;
	/* 业务分类 */
	private EnumConst enumConstByFlagCourseCategory;
	/* 内容属性分类 */
	private EnumConst enumConstByFlagContentProperty;
	/* 通过后能否继续访问 */
	private EnumConst enumConstByFlagIsvisitAfterPass;
	/* 课程收费状态 */
	private EnumConst enumConstByFlagIsFree;
	/* 课程推荐状态 */
	private EnumConst enumConstByFlagIsRecommend;
	/* 是否加入到专项 */
	private EnumConst enumConstByFlagCanJoinBatch;
	/* 大纲分类 */
	private EnumConst enumConstByFlagCourseItemType;
	/* 是否考试 */
	private EnumConst enumConstByFlagIsExam;
	/* 课程审核状态 */
	private EnumConst enumConstByFlagCheckStatus;
	/* COURSEAREA */
	private EnumConst enumConstByFlagCoursearea;
	/* 建议学习人群PE_BZZ_TCH_COURSE_SUGGEST(课程建议人群表)外键 */
	private String fkSuggestId;
	private EnumConst enumConstByFlagSuggest;
	/* 学时(其他课程)-实际学时数(在线直播) */
	private String time;
	/* 主讲人 */
	private String teacher;
	/* 主讲人简介 */
	private String teacherNote;
	/* 备注 */
	private String note;
	private Integer suqNum;

	// 新增字段---开始
	/* 金额 */
	private String price;
	/* 学习期限（天） */
	private String studyDates;
	/* 停用日期 */
	private Date endDate;
	/* 答疑开始时间 */
	private Date answerBeginDate;
	/* 答疑结束时间 */
	private Date answerEndDate;
	/* 通过规则 */
	private String passRole;
	/* 考试限制次数 */
	private String examTimesAllow;
	/* 通过规则描述 */
	private String passRoleNote;
	/* 学习建议 */
	private String suggestion;
	/* 课程图片地址 */
	private String photoLink;
	/* 创建时间 */
	private Date createDate;
	/* 编辑时间 */
	private Date editDate;
	/* 课件地址 */
	private String coursewareUrl;
	/* 发布日期 */
	private Date announceDate;
	/* 公司编号（一级集体账号）-公司内训课程 */
	private String comCode;
	/* 课程时长(其他)-累计时长(在线直播) */
	private String courseLen;
	/* 图片状态 */
	private EnumConst enumConstFlagImg;
	/* 主讲人照片地址 */
	private String teaImg;
	/* 主讲人照片状态 */
	private EnumConst enumConstFlagTeaimg;
	/* 发布状态 */
	private EnumConst enumConstFlagAnnounce;
	/* 主讲人描述 */
	private String teaNote;
	/* 满意度是否必填 */
	private EnumConst enumConstFlagSatisfaction;
	/* 创建人 */
	private String creater;
	/* 编辑人 */
	private String editor;
	/* 下线日期 */
	private Date offlineDate;
	/* 是否添加了考试 */
	private EnumConst enumConstFlagExam;
	/* 是否添加了课件 */
	private EnumConst enumConstFlagCourseware;
	/* 是否设置了建议学习人群 */
	private EnumConst enumConstFlagSuggestset;
	// 新增字段---结束
	private PeEnterprise peSite; // 管理员所在的企业

	private Set prBzzTchOpencourses = new HashSet(0);
	/* 满意度ID */
	private String satisfactionId;
	/* 操作日志 */
	private String operationLogs;

	// Constructors

	// 在线直播相关属性-start
	/* 报名开始时间 */
	private Date signStartDatetime;
	/* 报名结束时间 */
	private Date signEndDatetime;
	/* 预计学时数 */
	private String estimateTime;
	/* 直播通过规则 */
	private EnumConst enumConstByFlagLivePassRole;
	/* 预计直播开始时间 */
	private Date estimateStartDatetime;
	/* 预计直播结束时间 */
	private Date estimateEndDatetime;
	/* 直播链接(WEB) */
	private String liveUrl;
	/* 直播链接(CLIENT) */
	private String liveUrlClient;
	/* 课程简介 */
	private String liveDesc;
	/* 直播ID(可在直播链接中截取) */
	private String liveId;
	/* 是否采集过数据 ENUM_CONST(码表)外键 */
	private EnumConst enumConstByFlagLiveData;
	/* 是否分配完学时 ENUM_CONST(码表)外键 */
	private EnumConst enumConstByFlagLiveTime;
	/* 直播密码 */
	private String liveStuPwd;
	/* 报名人数上限 */
	private String maxStus;
	/* 报名限制-开放报名、不开放报名 */
	private EnumConst enumConstByFlagSignType;
	/* 讲师 */
	private TeacherInfo teacherId;
	/* 直播封版状态 */
	private EnumConst enumConstByFlagFreeze;

	/*课前测试*/
	private EnumConst enumConstByFlagPreTest;
	// 在线直播相关属性-end

	public String getMaxStus() {
		return maxStus;
	}

	public void setMaxStus(String maxStus) {
		this.maxStus = maxStus;
	}

	public String getOperationLogs() {
		return operationLogs;
	}

	public void setOperationLogs(String operationLogs) {
		this.operationLogs = operationLogs;
	}

	/** default constructor */
	public PeBzzTchCourse() {
	}

	/** minimal constructor */
	public PeBzzTchCourse(String name, String code) {
		this.name = name;
		this.code = code;
	}

	/** full constructor */
	public PeBzzTchCourse(String name, String code, Integer suqNum, EnumConst enumConstByFlagIsvalid, EnumConst enumConstByFlagCourseCategory, EnumConst enumConstByFlagContentProperty,
			EnumConst enumConstByFlagCourseType, EnumConst enumConstByFlagIsvisitAfterPass, String time, String teacher, EnumConst enumConstByFlagIsRecommend, String teacherNote, String note,
			Set prBzzTchOpencourses, String price, String studyDates, Date endDate, Date answerBeginDate, Date answerEndDate, String passRole, String examTimesAllow, String passRoleNote,
			String suggestion, EnumConst enumConstByFlagCourseItemType, String operationLogs) {
		this.name = name;
		this.code = code;
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.enumConstByFlagCourseType = enumConstByFlagCourseType;
		this.time = time;
		this.teacher = teacher;
		this.teacherNote = teacherNote;
		this.note = note;
		this.prBzzTchOpencourses = prBzzTchOpencourses;
		this.enumConstByFlagCourseCategory = enumConstByFlagCourseCategory;
		this.enumConstByFlagContentProperty = enumConstByFlagContentProperty;
		this.enumConstByFlagIsvisitAfterPass = enumConstByFlagIsvisitAfterPass;
		this.enumConstByFlagIsRecommend = enumConstByFlagIsRecommend;
		this.suqNum = suqNum;
		this.price = price;
		this.studyDates = studyDates;
		this.endDate = endDate;
		this.answerBeginDate = answerBeginDate;
		this.answerEndDate = answerEndDate;
		this.passRole = passRole;
		this.examTimesAllow = examTimesAllow;
		this.passRoleNote = passRoleNote;
		this.suggestion = suggestion;
		this.enumConstByFlagCourseItemType = enumConstByFlagCourseItemType;
		this.operationLogs = operationLogs;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public EnumConst getEnumConstByFlagCourseType() {
		return this.enumConstByFlagCourseType;
	}

	public void setEnumConstByFlagCourseType(EnumConst enumConstByFlagCourseType) {
		this.enumConstByFlagCourseType = enumConstByFlagCourseType;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public String getTeacherNote() {
		return this.teacherNote;
	}

	public void setTeacherNote(String teacherNote) {
		this.teacherNote = teacherNote;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPrBzzTchOpencourses() {
		return prBzzTchOpencourses;
	}

	public void setPrBzzTchOpencourses(Set prBzzTchOpencourses) {
		this.prBzzTchOpencourses = prBzzTchOpencourses;
	}

	public EnumConst getEnumConstByFlagCourseCategory() {
		return enumConstByFlagCourseCategory;
	}

	public void setEnumConstByFlagCourseCategory(EnumConst enumConstByFlagCourseCategory) {
		this.enumConstByFlagCourseCategory = enumConstByFlagCourseCategory;
	}

	public Integer getSuqNum() {
		return suqNum;
	}

	public void setSuqNum(Integer suqNum) {
		this.suqNum = suqNum;
	}

	public PeEnterprise getPeSite() {
		return peSite;
	}

	public void setPeSite(PeEnterprise peSite) {
		this.peSite = peSite;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getStudyDates() {
		return studyDates;
	}

	public void setStudyDates(String studyDates) {
		this.studyDates = studyDates;
	}

	public Date getAnswerBeginDate() {
		return answerBeginDate;
	}

	public void setAnswerBeginDate(Date answerBeginDate) {
		this.answerBeginDate = answerBeginDate;
	}

	public Date getAnswerEndDate() {
		return answerEndDate;
	}

	public void setAnswerEndDate(Date answerEndDate) {
		this.answerEndDate = answerEndDate;
	}

	public String getPassRole() {
		return passRole;
	}

	public void setPassRole(String passRole) {
		this.passRole = passRole;
	}

	public String getExamTimesAllow() {
		return examTimesAllow;
	}

	public void setExamTimesAllow(String examTimesAllow) {
		this.examTimesAllow = examTimesAllow;
	}

	public String getPassRoleNote() {
		return passRoleNote;
	}

	public void setPassRoleNote(String passRoleNote) {
		this.passRoleNote = passRoleNote;
	}

	public String getSuggestion() {
		return suggestion;
	}

	public void setSuggestion(String suggestion) {
		this.suggestion = suggestion;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getSatisfactionId() {
		return satisfactionId;
	}

	public void setSatisfactionId(String satisfactionId) {
		this.satisfactionId = satisfactionId;
	}

	public EnumConst getEnumConstByFlagIsvisitAfterPass() {
		return enumConstByFlagIsvisitAfterPass;
	}

	public void setEnumConstByFlagIsvisitAfterPass(EnumConst enumConstByFlagIsvisitAfterPass) {
		this.enumConstByFlagIsvisitAfterPass = enumConstByFlagIsvisitAfterPass;
	}

	public EnumConst getEnumConstByFlagIsFree() {
		return enumConstByFlagIsFree;
	}

	public void setEnumConstByFlagIsFree(EnumConst enumConstByFlagIsFree) {
		this.enumConstByFlagIsFree = enumConstByFlagIsFree;
	}

	public EnumConst getEnumConstByFlagIsRecommend() {
		return enumConstByFlagIsRecommend;
	}

	public void setEnumConstByFlagIsRecommend(EnumConst enumConstByFlagIsRecommend) {
		this.enumConstByFlagIsRecommend = enumConstByFlagIsRecommend;
	}

	public String getPhotoLink() {
		return photoLink;
	}

	public void setPhotoLink(String photoLink) {
		this.photoLink = photoLink;
	}

	public EnumConst getEnumConstByFlagCanJoinBatch() {
		return enumConstByFlagCanJoinBatch;
	}

	public void setEnumConstByFlagCanJoinBatch(EnumConst enumConstByFlagCanJoinBatch) {
		this.enumConstByFlagCanJoinBatch = enumConstByFlagCanJoinBatch;
	}

	public EnumConst getEnumConstByFlagCourseItemType() {
		return enumConstByFlagCourseItemType;
	}

	public void setEnumConstByFlagCourseItemType(EnumConst enumConstByFlagCourseItemType) {
		this.enumConstByFlagCourseItemType = enumConstByFlagCourseItemType;
	}

	public EnumConst getEnumConstByFlagIsExam() {
		return enumConstByFlagIsExam;
	}

	public void setEnumConstByFlagIsExam(EnumConst enumConstByFlagIsExam) {
		this.enumConstByFlagIsExam = enumConstByFlagIsExam;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getEditDate() {
		return editDate;
	}

	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}

	public Date getAnnounceDate() {
		return announceDate;
	}

	public void setAnnounceDate(Date announceDate) {
		this.announceDate = announceDate;
	}

	public EnumConst getEnumConstByFlagCheckStatus() {
		return enumConstByFlagCheckStatus;
	}

	public void setEnumConstByFlagCheckStatus(EnumConst enumConstByFlagCheckStatus) {
		this.enumConstByFlagCheckStatus = enumConstByFlagCheckStatus;
	}

	public EnumConst getEnumConstByFlagOffline() {
		return enumConstByFlagOffline;
	}

	public void setEnumConstByFlagOffline(EnumConst enumConstByFlagOffline) {
		this.enumConstByFlagOffline = enumConstByFlagOffline;
	}

	public EnumConst getEnumConstByFlagContentProperty() {
		return enumConstByFlagContentProperty;
	}

	public void setEnumConstByFlagContentProperty(EnumConst enumConstByFlagContentProperty) {
		this.enumConstByFlagContentProperty = enumConstByFlagContentProperty;
	}

	public EnumConst getEnumConstByFlagCoursearea() {
		return enumConstByFlagCoursearea;
	}

	public void setEnumConstByFlagCoursearea(EnumConst enumConstByFlagCoursearea) {
		this.enumConstByFlagCoursearea = enumConstByFlagCoursearea;
	}

	public EnumConst getEnumConstByFlagSuggest() {
		return enumConstByFlagSuggest;
	}

	public void setEnumConstByFlagSuggest(EnumConst enumConstByFlagSuggest) {
		this.enumConstByFlagSuggest = enumConstByFlagSuggest;
	}

	public String getCoursewareUrl() {
		return coursewareUrl;
	}

	public void setCoursewareUrl(String coursewareUrl) {
		this.coursewareUrl = coursewareUrl;
	}

	public String getFkSuggestId() {
		return fkSuggestId;
	}

	public void setFkSuggestId(String fkSuggestId) {
		this.fkSuggestId = fkSuggestId;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getCourseLen() {
		return courseLen;
	}

	public void setCourseLen(String courseLen) {
		this.courseLen = courseLen;
	}

	public EnumConst getEnumConstFlagImg() {
		return enumConstFlagImg;
	}

	public void setEnumConstFlagImg(EnumConst enumConstFlagImg) {
		this.enumConstFlagImg = enumConstFlagImg;
	}

	public String getTeaImg() {
		return teaImg;
	}

	public void setTeaImg(String teaImg) {
		this.teaImg = teaImg;
	}

	public EnumConst getEnumConstFlagTeaimg() {
		return enumConstFlagTeaimg;
	}

	public void setEnumConstFlagTeaimg(EnumConst enumConstFlagTeaimg) {
		this.enumConstFlagTeaimg = enumConstFlagTeaimg;
	}

	public EnumConst getEnumConstFlagAnnounce() {
		return enumConstFlagAnnounce;
	}

	public void setEnumConstFlagAnnounce(EnumConst enumConstFlagAnnounce) {
		this.enumConstFlagAnnounce = enumConstFlagAnnounce;
	}

	public String getTeaNote() {
		return teaNote;
	}

	public void setTeaNote(String teaNote) {
		this.teaNote = teaNote;
	}

	public EnumConst getEnumConstFlagSatisfaction() {
		return enumConstFlagSatisfaction;
	}

	public void setEnumConstFlagSatisfaction(EnumConst enumConstFlagSatisfaction) {
		this.enumConstFlagSatisfaction = enumConstFlagSatisfaction;
	}

	public String getCreater() {
		return creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public String getEditor() {
		return editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	public Date getOfflineDate() {
		return offlineDate;
	}

	public void setOfflineDate(Date offlineDate) {
		this.offlineDate = offlineDate;
	}

	public EnumConst getEnumConstFlagExam() {
		return enumConstFlagExam;
	}

	public void setEnumConstFlagExam(EnumConst enumConstFlagExam) {
		this.enumConstFlagExam = enumConstFlagExam;
	}

	public EnumConst getEnumConstFlagCourseware() {
		return enumConstFlagCourseware;
	}

	public void setEnumConstFlagCourseware(EnumConst enumConstFlagCourseware) {
		this.enumConstFlagCourseware = enumConstFlagCourseware;
	}

	public EnumConst getEnumConstFlagSuggestset() {
		return enumConstFlagSuggestset;
	}

	public void setEnumConstFlagSuggestset(EnumConst enumConstFlagSuggestset) {
		this.enumConstFlagSuggestset = enumConstFlagSuggestset;
	}

	public String getEstimateTime() {
		return estimateTime;
	}

	public void setEstimateTime(String estimateTime) {
		this.estimateTime = estimateTime;
	}

	public String getLiveUrl() {
		return liveUrl;
	}

	public void setLiveUrl(String liveUrl) {
		this.liveUrl = liveUrl;
	}

	public String getLiveDesc() {
		return liveDesc;
	}

	public void setLiveDesc(String liveDesc) {
		this.liveDesc = liveDesc;
	}

	public String getLiveId() {
		return liveId;
	}

	public void setLiveId(String liveId) {
		this.liveId = liveId;
	}

	public EnumConst getEnumConstByFlagLiveData() {
		return enumConstByFlagLiveData;
	}

	public void setEnumConstByFlagLiveData(EnumConst enumConstByFlagLiveData) {
		this.enumConstByFlagLiveData = enumConstByFlagLiveData;
	}

	public EnumConst getEnumConstByFlagLiveTime() {
		return enumConstByFlagLiveTime;
	}

	public void setEnumConstByFlagLiveTime(EnumConst enumConstByFlagLiveTime) {
		this.enumConstByFlagLiveTime = enumConstByFlagLiveTime;
	}

	public String getLiveStuPwd() {
		return liveStuPwd;
	}

	public void setLiveStuPwd(String liveStuPwd) {
		this.liveStuPwd = liveStuPwd;
	}

	public EnumConst getEnumConstByFlagLivePassRole() {
		return enumConstByFlagLivePassRole;
	}

	public void setEnumConstByFlagLivePassRole(EnumConst enumConstByFlagLivePassRole) {
		this.enumConstByFlagLivePassRole = enumConstByFlagLivePassRole;
	}

	public Date getEstimateStartDatetime() {
		return estimateStartDatetime;
	}

	public void setEstimateStartDatetime(Date estimateStartDatetime) {
		this.estimateStartDatetime = estimateStartDatetime;
	}

	public Date getEstimateEndDatetime() {
		return estimateEndDatetime;
	}

	public void setEstimateEndDatetime(Date estimateEndDatetime) {
		this.estimateEndDatetime = estimateEndDatetime;
	}

	public EnumConst getEnumConstByFlagSignType() {
		return enumConstByFlagSignType;
	}

	public void setEnumConstByFlagSignType(EnumConst enumConstByFlagSignType) {
		this.enumConstByFlagSignType = enumConstByFlagSignType;
	}

	public Date getSignStartDatetime() {
		return signStartDatetime;
	}

	public void setSignStartDatetime(Date signStartDatetime) {
		this.signStartDatetime = signStartDatetime;
	}

	public Date getSignEndDatetime() {
		return signEndDatetime;
	}

	public void setSignEndDatetime(Date signEndDatetime) {
		this.signEndDatetime = signEndDatetime;
	}

	public TeacherInfo getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(TeacherInfo teacherId) {
		this.teacherId = teacherId;
	}

	public EnumConst getEnumConstByFlagFreeze() {
		return enumConstByFlagFreeze;
	}

	public void setEnumConstByFlagFreeze(EnumConst enumConstByFlagFreeze) {
		this.enumConstByFlagFreeze = enumConstByFlagFreeze;
	}

	public String getLiveUrlClient() {
		return liveUrlClient;
	}

	public void setLiveUrlClient(String liveUrlClient) {
		this.liveUrlClient = liveUrlClient;
	}

	public EnumConst getEnumConstByFlagPreTest() {
		return enumConstByFlagPreTest;
	}

	public void setEnumConstByFlagPreTest(EnumConst enumConstByFlagPreTest) {
		this.enumConstByFlagPreTest = enumConstByFlagPreTest;
	}
}