package com.whaty.platform.entity.bean;



/**
 * PeBzzTchCourseware generated by MyEclipse - Hibernate Tools
 */

public class PeBzzTchCourseware extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {


    // Fields    

     private String id;
     private EnumConst enumConstByFlagBak;
     private EnumConst enumConstByFlagIsvalid;
     private PeBzzTchCourse peBzzTchCourse;
     private String name;
     private String code;
     private String author;
     private String publisher;
     private String note;
     private String link;
     
//     private PeEnterprise peSite;	//管理员所在的企业


    // Constructors

    /** default constructor */
    public PeBzzTchCourseware() {
    }

	/** minimal constructor */
    public PeBzzTchCourseware(String name) {
        this.name = name;
    }
    
    /** full constructor */
    public PeBzzTchCourseware(EnumConst enumConstByFlagBak, EnumConst enumConstByFlagIsvalid, PeBzzTchCourse peBzzTchCourse, String name, String code, String author, String publisher, String note, String link) {
        this.enumConstByFlagBak = enumConstByFlagBak;
        this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
        this.peBzzTchCourse = peBzzTchCourse;
        this.name = name;
        this.code = code;
        this.author = author;
        this.publisher = publisher;
        this.note = note;
        this.link = link;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public EnumConst getEnumConstByFlagBak() {
        return this.enumConstByFlagBak;
    }
    
    public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
        this.enumConstByFlagBak = enumConstByFlagBak;
    }

    public EnumConst getEnumConstByFlagIsvalid() {
        return this.enumConstByFlagIsvalid;
    }
    
    public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
        this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
    }

    public PeBzzTchCourse getPeBzzTchCourse() {
        return this.peBzzTchCourse;
    }
    
    public void setPeBzzTchCourse(PeBzzTchCourse peBzzTchCourse) {
        this.peBzzTchCourse = peBzzTchCourse;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    public String getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }

//	public PeEnterprise getPeSite() {
//		return peSite;
//	}
//
//	public void setPeSite(PeEnterprise peSite) {
//		this.peSite = peSite;
//	}
   








}