package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeBzzRecruitBefore extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private PeBzzBatch peBzzBatch; // 所在批次
	private PeEnterprise peEnterprise; // 所在企业
	private String signUpNum; // 预报人数
	private String communicateRecord;//沟通记录
	private String note;//备注
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public PeBzzBatch getPeBzzBatch() {
		return peBzzBatch;
	}
	public void setPeBzzBatch(PeBzzBatch peBzzBatch) {
		this.peBzzBatch = peBzzBatch;
	}
	public PeEnterprise getPeEnterprise() {
		return peEnterprise;
	}
	public void setPeEnterprise(PeEnterprise peEnterprise) {
		this.peEnterprise = peEnterprise;
	}
	public String getSignUpNum() {
		return signUpNum;
	}
	public void setSignUpNum(String signUpNum) {
		this.signUpNum = signUpNum;
	}
	public String getCommunicateRecord() {
		return communicateRecord;
	}
	public void setCommunicateRecord(String communicateRecord) {
		this.communicateRecord = communicateRecord;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	
	
	
}