package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeBzzCerficateMailInfo extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// Fields

	private String id;
	private PeEnterprise peEnterprise; // 邮寄单位
	private String num; // 件数
	private EnumConst enumConstByFlagMailSendStatus; // 收发确认
	private String expressNo; // 快递单号

	private String bz; // 备注
	private Date luruDate;  //操作时间
	private String luruPeople; // 操作人
	
	private PeBzzExamBatch peBzzExamBatch; // 所在考试批次
	

	// Constructors

	/** default constructor */
	public PeBzzCerficateMailInfo() {
	}
	

	public PeBzzCerficateMailInfo(String id, PeEnterprise peEnterprise, String num,
			EnumConst enumConstByFlagMailSendStatus, String expressNo,String bz,
			Date luruDate, String luruPeople, PeBzzExamBatch peBzzExamBatch) {
		super();
		this.id = id;
		this.peEnterprise = peEnterprise;
		this.num = num;
		this.enumConstByFlagMailSendStatus = enumConstByFlagMailSendStatus;
		this.expressNo = expressNo;
		this.bz = bz;
		this.luruDate = luruDate;
		this.luruPeople = luruPeople;
		this.peBzzExamBatch = peBzzExamBatch;
	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public PeEnterprise getPeEnterprise() {
		return peEnterprise;
	}


	public void setPeEnterprise(PeEnterprise peEnterprise) {
		this.peEnterprise = peEnterprise;
	}


	public String getNum() {
		return num;
	}


	public void setNum(String num) {
		this.num = num;
	}


	public EnumConst getEnumConstByFlagMailSendStatus() {
		return enumConstByFlagMailSendStatus;
	}


	public void setEnumConstByFlagMailSendStatus(
			EnumConst enumConstByFlagMailSendStatus) {
		this.enumConstByFlagMailSendStatus = enumConstByFlagMailSendStatus;
	}


	public String getExpressNo() {
		return expressNo;
	}


	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}


	public String getBz() {
		return bz;
	}


	public void setBz(String bz) {
		this.bz = bz;
	}


	public Date getLuruDate() {
		return luruDate;
	}


	public void setLuruDate(Date luruDate) {
		this.luruDate = luruDate;
	}


	public String getLuruPeople() {
		return luruPeople;
	}


	public void setLuruPeople(String luruPeople) {
		this.luruPeople = luruPeople;
	}


	public PeBzzExamBatch getPeBzzExamBatch() {
		return peBzzExamBatch;
	}


	public void setPeBzzExamBatch(PeBzzExamBatch peBzzExamBatch) {
		this.peBzzExamBatch = peBzzExamBatch;
	}
}