package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *  generated by MyEclipse Persistence Tools
 */

public class PeElectiveCoursePeriod extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private String name;
	private Date beginDatetime;
	
	private Date endDatetime;
	
	private String stuTime;
	
	private EnumConst enumConstByFlagElePeriodPayStatus;
	
	private SsoUser ssoUser;
	
	private String compulsoryhour; //必修学时下限 20140624
	
	private String totalhour;//总学时下限 20140624
	
	private String amountuplimit;//金额上限 20140624
	
	private Set periodStudent = new HashSet(0);
	
	private Set prBzzTchStuElectiveBack = new HashSet(0);

	// Constructors

	public Set getPrBzzTchStuElectiveBack() {
		return prBzzTchStuElectiveBack;
	}

	public void setPrBzzTchStuElectiveBack(Set prBzzTchStuElectiveBack) {
		this.prBzzTchStuElectiveBack = prBzzTchStuElectiveBack;
	}

	/** default constructor */
	public PeElectiveCoursePeriod() {
	}

	/** minimal constructor */
	public PeElectiveCoursePeriod(String name) {
		this.name = name;
	}

	/** full constructor */

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public PeElectiveCoursePeriod(String id, String name, Date beginDatetime,
			Date endDatetime, String stuTime,
			EnumConst enumConstByFlagElePeriodPayStatus, SsoUser ssoUser,
			String compulsoryhour, String totalhour, String amountuplimit,
			Set periodStudent, Set prBzzTchStuElectiveBack) {
		super();
		this.id = id;
		this.name = name;
		this.beginDatetime = beginDatetime;
		this.endDatetime = endDatetime;
		this.stuTime = stuTime;
		this.enumConstByFlagElePeriodPayStatus = enumConstByFlagElePeriodPayStatus;
		this.ssoUser = ssoUser;
		this.compulsoryhour = compulsoryhour;
		this.totalhour = totalhour;
		this.amountuplimit = amountuplimit;
		this.periodStudent = periodStudent;
		this.prBzzTchStuElectiveBack = prBzzTchStuElectiveBack;
	}

	public Date getBeginDatetime() {
		return beginDatetime;
	}

	public void setBeginDatetime(Date beginDatetime) {
		this.beginDatetime = beginDatetime;
	}

	public Date getEndDatetime() {
		return endDatetime;
	}

	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	public String getStuTime() {
		return stuTime;
	}

	public void setStuTime(String stuTime) {
		this.stuTime = stuTime;
	}

	public Set getPeriodStudent() {
		return periodStudent;
	}

	public void setPeriodStudent(Set periodStudent) {
		this.periodStudent = periodStudent;
	}

	public EnumConst getEnumConstByFlagElePeriodPayStatus() {
		return enumConstByFlagElePeriodPayStatus;
	}

	public void setEnumConstByFlagElePeriodPayStatus(
			EnumConst enumConstByFlagElePeriodPayStatus) {
		this.enumConstByFlagElePeriodPayStatus = enumConstByFlagElePeriodPayStatus;
	}

	public SsoUser getSsoUser() {
		return ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public String getCompulsoryhour() {
		return compulsoryhour;
	}

	public void setCompulsoryhour(String compulsoryhour) {
		this.compulsoryhour = compulsoryhour;
	}

	public String getTotalhour() {
		return totalhour;
	}

	public void setTotalhour(String totalhour) {
		this.totalhour = totalhour;
	}

	public String getAmountuplimit() {
		return amountuplimit;
	}

	public void setAmountuplimit(String amountuplimit) {
		this.amountuplimit = amountuplimit;
	}

}