package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeEnterprise generated by MyEclipse - Hibernate Tools
 */

public class PeEnterprise extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private PeEnterprise peEnterprise; // 父类
	private String name;
	private String code;
	private String industry;
	private String address;
	private String zipcode;
	private String fax;
	private String fzrName;
	private String fzrXb;
	private String fzrDepart;
	private String fzrPosition;
	private String fzrPhone;
	private String fzrMobile;
	private String fzrEmail;
	private String fzrAddress;
	private String lxrName;
	private String lxrXb;
	private String lxrDepart;
	private String lxrPosition;
	private String lxrPhone;
	private String lxrMobile;
	private String lxrEmail;
	private String lxrAddress;
	private String status;
	private String bz;
	private String num;
	private String infoSheng;
	private String infoShi;
	private String infoJiedao;
	private String enrolAddress;
	private String netAddress;

	// 2010.3.30 gaoyuan add
	private String parentName;
	private String shortName;
	private String fzrAreacode;
	private String lxrAreacode;

	private String hkType;
	private String hkFullname;
	private String receiverSheng;
	private String receiverShi;
	private String receiverAddress;
	private String receiverZipcode;
	private String receiverUsername;
	private String receiverPhone;
	private String receiverMobile;

	private Set prBzzPriManagerEnterprises = new HashSet(0);
	private Set peBzzStudents = new HashSet(0);
	private Set peEnterpriseManagers = new HashSet(0);
	private Set peEnterprises = new HashSet(0); // 子类
	private Set peBulletins = new HashSet(0);

	private Set peBzzRecruits = new HashSet(0);

	// sunjicheng add
	private Date luruDate; // 操作时间
	private String luruPeople; // 操作人
	private EnumConst enumConstByFlagEnterpriseState; // 企业状态（只对二级企业有效）
	private EnumConst enumConstByFlagEnterpriseType;  //机构类别

	private PeEnterprise peSite; // 管理员所在的企业

	private PeBzzBatch peBzzBatch;

	private String subName;
	
	/** default constructor */
	public PeEnterprise() {
	}

	/** minimal constructor */
	public PeEnterprise(String name, String code) {
		this.name = name;
		this.code = code;
	}

	/** full constructor */
	public PeEnterprise(String id, PeEnterprise peEnterprise, String name,
			String code, String industry, String address, String zipcode,
			String fax, String fzrName, String fzrXb, String fzrDepart,
			String fzrPosition, String fzrPhone, String fzrMobile,
			String fzrEmail, String fzrAddress, String lxrName, String lxrXb,
			String lxrDepart, String lxrPosition, String lxrPhone,
			String lxrMobile, String lxrEmail, String lxrAddress,
			String status, String bz, String num, String infoSheng,
			String infoShi, String infoJiedao, String parentName,
			String shortName, String fzrAreacode, String lxrAreacode,
			String hkType, String hkFullname, String receiverSheng,
			String enrolAddress,String netAddress,
			String receiverShi, String receiverAddress, String receiverZipcode,
			String receiverUsername, String receiverPhone,
			String receiverMobile, Set prBzzPriManagerEnterprises,
			Set peBzzStudents, Set peEnterpriseManagers, Set peEnterprises,
			Set peBulletins, Set peBzzRecruits,EnumConst enumConstByFlagEnterpriseState
			) {
		super();
		this.id = id;
		this.peEnterprise = peEnterprise;
		this.name = name;
		this.code = code;
		this.industry = industry;
		this.address = address;
		this.zipcode = zipcode;
		this.fax = fax;
		this.fzrName = fzrName;
		this.fzrXb = fzrXb;
		this.fzrDepart = fzrDepart;
		this.fzrPosition = fzrPosition;
		this.fzrPhone = fzrPhone;
		this.fzrMobile = fzrMobile;
		this.fzrEmail = fzrEmail;
		this.fzrAddress = fzrAddress;
		this.lxrName = lxrName;
		this.lxrXb = lxrXb;
		this.lxrDepart = lxrDepart;
		this.lxrPosition = lxrPosition;
		this.lxrPhone = lxrPhone;
		this.lxrMobile = lxrMobile;
		this.lxrEmail = lxrEmail;
		this.lxrAddress = lxrAddress;
		this.status = status;
		this.bz = bz;
		this.num = num;
		this.infoSheng = infoSheng;
		this.infoShi = infoShi;
		this.infoJiedao = infoJiedao;
		this.parentName = parentName;
		this.shortName = shortName;
		this.fzrAreacode = fzrAreacode;
		this.lxrAreacode = lxrAreacode;
		this.hkType = hkType;
		this.hkFullname = hkFullname;
		this.enrolAddress = enrolAddress;
		this.netAddress = netAddress;
		this.receiverSheng = receiverSheng;
		this.receiverShi = receiverShi;
		this.receiverAddress = receiverAddress;
		this.receiverZipcode = receiverZipcode;
		this.receiverUsername = receiverUsername;
		this.receiverPhone = receiverPhone;
		this.receiverMobile = receiverMobile;
		this.prBzzPriManagerEnterprises = prBzzPriManagerEnterprises;
		this.peBzzStudents = peBzzStudents;
		this.peEnterpriseManagers = peEnterpriseManagers;
		this.peEnterprises = peEnterprises;
		this.peBulletins = peBulletins;
		this.peBzzRecruits = peBzzRecruits;
		this.enumConstByFlagEnterpriseState = enumConstByFlagEnterpriseState;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeEnterprise getPeEnterprise() {
		return this.peEnterprise;
	}

	public void setPeEnterprise(PeEnterprise peEnterprise) {
		this.peEnterprise = peEnterprise;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getFzrName() {
		return this.fzrName;
	}

	public void setFzrName(String fzrName) {
		this.fzrName = fzrName;
	}

	public String getFzrXb() {
		return this.fzrXb;
	}

	public void setFzrXb(String fzrXb) {
		this.fzrXb = fzrXb;
	}

	public String getFzrPosition() {
		return this.fzrPosition;
	}

	public void setFzrPosition(String fzrPosition) {
		this.fzrPosition = fzrPosition;
	}

	public String getFzrPhone() {
		return this.fzrPhone;
	}

	public void setFzrPhone(String fzrPhone) {
		this.fzrPhone = fzrPhone;
	}

	public String getFzrMobile() {
		return this.fzrMobile;
	}

	public void setFzrMobile(String fzrMobile) {
		this.fzrMobile = fzrMobile;
	}

	public String getFzrEmail() {
		return this.fzrEmail;
	}

	public void setFzrEmail(String fzrEmail) {
		this.fzrEmail = fzrEmail;
	}

	public String getFzrAddress() {
		return this.fzrAddress;
	}

	public void setFzrAddress(String fzrAddress) {
		this.fzrAddress = fzrAddress;
	}

	public String getLxrName() {
		return this.lxrName;
	}

	public void setLxrName(String lxrName) {
		this.lxrName = lxrName;
	}

	public String getLxrXb() {
		return this.lxrXb;
	}

	public void setLxrXb(String lxrXb) {
		this.lxrXb = lxrXb;
	}

	public String getLxrPosition() {
		return this.lxrPosition;
	}

	public void setLxrPosition(String lxrPosition) {
		this.lxrPosition = lxrPosition;
	}

	public String getLxrPhone() {
		return this.lxrPhone;
	}

	public void setLxrPhone(String lxrPhone) {
		this.lxrPhone = lxrPhone;
	}

	public String getLxrMobile() {
		return this.lxrMobile;
	}

	public void setLxrMobile(String lxrMobile) {
		this.lxrMobile = lxrMobile;
	}

	public String getLxrEmail() {
		return this.lxrEmail;
	}

	public void setLxrEmail(String lxrEmail) {
		this.lxrEmail = lxrEmail;
	}

	public String getLxrAddress() {
		return this.lxrAddress;
	}

	public void setLxrAddress(String lxrAddress) {
		this.lxrAddress = lxrAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBz() {
		return this.bz;
	}

	public void setBz(String bz) {
		this.bz = bz;
	}

	public Set getPrBzzPriManagerEnterprises() {
		return this.prBzzPriManagerEnterprises;
	}

	public void setPrBzzPriManagerEnterprises(Set prBzzPriManagerEnterprises) {
		this.prBzzPriManagerEnterprises = prBzzPriManagerEnterprises;
	}

	public Set getPeBzzStudents() {
		return this.peBzzStudents;
	}

	public void setPeBzzStudents(Set peBzzStudents) {
		this.peBzzStudents = peBzzStudents;
	}

	public Set getPeEnterpriseManagers() {
		return this.peEnterpriseManagers;
	}

	public void setPeEnterpriseManagers(Set peEnterpriseManagers) {
		this.peEnterpriseManagers = peEnterpriseManagers;
	}

	public Set getPeEnterprises() {
		return this.peEnterprises;
	}

	public void setPeEnterprises(Set peEnterprises) {
		this.peEnterprises = peEnterprises;
	}

	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public Set getPeBulletins() {
		return peBulletins;
	}

	public void setPeBulletins(Set peBulletins) {
		this.peBulletins = peBulletins;
	}

	public String getFzrDepart() {
		return fzrDepart;
	}

	public String getLxrDepart() {
		return lxrDepart;
	}

	public void setFzrDepart(String fzrDepart) {
		this.fzrDepart = fzrDepart;
	}

	public void setLxrDepart(String lxrDepart) {
		this.lxrDepart = lxrDepart;
	}

	public String getInfoSheng() {
		return infoSheng;
	}

	public void setInfoSheng(String infoSheng) {
		this.infoSheng = infoSheng;
	}

	public String getInfoShi() {
		return infoShi;
	}

	public void setInfoShi(String infoShi) {
		this.infoShi = infoShi;
	}

	public String getInfoJiedao() {
		return infoJiedao;
	}

	public void setInfoJiedao(String infoJiedao) {
		this.infoJiedao = infoJiedao;
	}

	public String getFzrAreacode() {
		return fzrAreacode;
	}

	public void setFzrAreacode(String fzrAreacode) {
		this.fzrAreacode = fzrAreacode;
	}

	public String getLxrAreacode() {
		return lxrAreacode;
	}

	public void setLxrAreacode(String lxrAreacode) {
		this.lxrAreacode = lxrAreacode;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public Set getPeBzzRecruits() {
		return peBzzRecruits;
	}

	public void setPeBzzRecruits(Set peBzzRecruits) {
		this.peBzzRecruits = peBzzRecruits;
	}

	public String getHkFullname() {
		return hkFullname;
	}

	public void setHkFullname(String hkFullname) {
		this.hkFullname = hkFullname;
	}

	public String getHkType() {
		return hkType;
	}

	public void setHkType(String hkType) {
		this.hkType = hkType;
	}

	public String getReceiverAddress() {
		return receiverAddress;
	}

	public void setReceiverAddress(String receiverAddress) {
		this.receiverAddress = receiverAddress;
	}

	public String getReceiverMobile() {
		return receiverMobile;
	}

	public void setReceiverMobile(String receiverMobile) {
		this.receiverMobile = receiverMobile;
	}

	public String getReceiverPhone() {
		return receiverPhone;
	}

	public void setReceiverPhone(String receiverPhone) {
		this.receiverPhone = receiverPhone;
	}

	public String getReceiverSheng() {
		return receiverSheng;
	}

	public void setReceiverSheng(String receiverSheng) {
		this.receiverSheng = receiverSheng;
	}

	public String getReceiverShi() {
		return receiverShi;
	}

	public void setReceiverShi(String receiverShi) {
		this.receiverShi = receiverShi;
	}

	public String getReceiverUsername() {
		return receiverUsername;
	}

	public void setReceiverUsername(String receiverUsername) {
		this.receiverUsername = receiverUsername;
	}

	public String getReceiverZipcode() {
		return receiverZipcode;
	}

	public void setReceiverZipcode(String receiverZipcode) {
		this.receiverZipcode = receiverZipcode;
	}

	public Date getLuruDate() {
		return luruDate;
	}

	public void setLuruDate(Date luruDate) {
		this.luruDate = luruDate;
	}

	public String getLuruPeople() {
		return luruPeople;
	}

	public void setLuruPeople(String luruPeople) {
		this.luruPeople = luruPeople;
	}


	public PeBzzBatch getPeBzzBatch() {
		return peBzzBatch;
	}

	public void setPeBzzBatch(PeBzzBatch peBzzBatch) {
		this.peBzzBatch = peBzzBatch;
	}

	public PeEnterprise getPeSite() {
		return peSite;
	}

	public void setPeSite(PeEnterprise peSite) {
		this.peSite = peSite;
	}

	public EnumConst getEnumConstByFlagEnterpriseState() {
		return enumConstByFlagEnterpriseState;
	}

	public void setEnumConstByFlagEnterpriseState(
			EnumConst enumConstByFlagEnterpriseState) {
		this.enumConstByFlagEnterpriseState = enumConstByFlagEnterpriseState;
	}

	public String getEnrolAddress() {
		return enrolAddress;
	}

	public void setEnrolAddress(String enrolAddress) {
		this.enrolAddress = enrolAddress;
	}

	public String getNetAddress() {
		return netAddress;
	}

	public void setNetAddress(String netAddress) {
		this.netAddress = netAddress;
	}

	public String getSubName() {
		return subName;
	}

	public void setSubName(String subName) {
		this.subName = subName;
	}

	public EnumConst getEnumConstByFlagEnterpriseType() {
		return enumConstByFlagEnterpriseType;
	}

	public void setEnumConstByFlagEnterpriseType(
			EnumConst enumConstByFlagEnterpriseType) {
		this.enumConstByFlagEnterpriseType = enumConstByFlagEnterpriseType;
	}
	
}