package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeExamPatrol generated by MyEclipse Persistence Tools
 */

public class PeExamPatrol extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByGender;

	private EnumConst enumConstByFlagIsJiankao;

	private EnumConst enumConstByFlagIsXunkao;

	private PeSite peSite;

	private String name;

	private String code;

	private String cardNum;

	private Date birthday;

	private String hometown;

	private String workplace;

	private String occupation;

	private String photoLink;

	private String mobileGuangzhou;

	private String mobileAway;

	private String phoneOffice;

	private String phoneHome;

	private Set prRecPatrolSettings = new HashSet(0);

	private Set prExamPatrolSettings = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeExamPatrol() {
	}

	/** minimal constructor */
	public PeExamPatrol(EnumConst enumConstByFlagIsJiankao,
			EnumConst enumConstByFlagIsXunkao, String name, String code,
			String cardNum) {
		this.enumConstByFlagIsJiankao = enumConstByFlagIsJiankao;
		this.enumConstByFlagIsXunkao = enumConstByFlagIsXunkao;
		this.name = name;
		this.code = code;
		this.cardNum = cardNum;
	}

	/** full constructor */
	public PeExamPatrol(EnumConst enumConstByGender,
			EnumConst enumConstByFlagIsJiankao,
			EnumConst enumConstByFlagIsXunkao, PeSite peSite, String name,
			String code, String cardNum, Date birthday, String hometown,
			String workplace, String occupation, String photoLink,
			String mobileGuangzhou, String mobileAway, String phoneOffice,
			String phoneHome, Set prRecPatrolSettings, Set prExamPatrolSettings) {
		this.enumConstByGender = enumConstByGender;
		this.enumConstByFlagIsJiankao = enumConstByFlagIsJiankao;
		this.enumConstByFlagIsXunkao = enumConstByFlagIsXunkao;
		this.peSite = peSite;
		this.name = name;
		this.code = code;
		this.cardNum = cardNum;
		this.birthday = birthday;
		this.hometown = hometown;
		this.workplace = workplace;
		this.occupation = occupation;
		this.photoLink = photoLink;
		this.mobileGuangzhou = mobileGuangzhou;
		this.mobileAway = mobileAway;
		this.phoneOffice = phoneOffice;
		this.phoneHome = phoneHome;
		this.prRecPatrolSettings = prRecPatrolSettings;
		this.prExamPatrolSettings = prExamPatrolSettings;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByGender() {
		return this.enumConstByGender;
	}

	public void setEnumConstByGender(EnumConst enumConstByGender) {
		this.enumConstByGender = enumConstByGender;
	}

	public EnumConst getEnumConstByFlagIsJiankao() {
		return this.enumConstByFlagIsJiankao;
	}

	public void setEnumConstByFlagIsJiankao(EnumConst enumConstByFlagIsJiankao) {
		this.enumConstByFlagIsJiankao = enumConstByFlagIsJiankao;
	}

	public EnumConst getEnumConstByFlagIsXunkao() {
		return this.enumConstByFlagIsXunkao;
	}

	public void setEnumConstByFlagIsXunkao(EnumConst enumConstByFlagIsXunkao) {
		this.enumConstByFlagIsXunkao = enumConstByFlagIsXunkao;
	}

	public PeSite getPeSite() {
		return this.peSite;
	}

	public void setPeSite(PeSite peSite) {
		this.peSite = peSite;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getCardNum() {
		return this.cardNum;
	}

	public void setCardNum(String cardNum) {
		this.cardNum = cardNum;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getHometown() {
		return this.hometown;
	}

	public void setHometown(String hometown) {
		this.hometown = hometown;
	}

	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getPhotoLink() {
		return this.photoLink;
	}

	public void setPhotoLink(String photoLink) {
		this.photoLink = photoLink;
	}

	public String getMobileGuangzhou() {
		return this.mobileGuangzhou;
	}

	public void setMobileGuangzhou(String mobileGuangzhou) {
		this.mobileGuangzhou = mobileGuangzhou;
	}

	public String getMobileAway() {
		return this.mobileAway;
	}

	public void setMobileAway(String mobileAway) {
		this.mobileAway = mobileAway;
	}

	public String getPhoneOffice() {
		return this.phoneOffice;
	}

	public void setPhoneOffice(String phoneOffice) {
		this.phoneOffice = phoneOffice;
	}

	public String getPhoneHome() {
		return this.phoneHome;
	}

	public void setPhoneHome(String phoneHome) {
		this.phoneHome = phoneHome;
	}

	public Set getPrRecPatrolSettings() {
		return this.prRecPatrolSettings;
	}

	public void setPrRecPatrolSettings(Set prRecPatrolSettings) {
		this.prRecPatrolSettings = prRecPatrolSettings;
	}

	public Set getPrExamPatrolSettings() {
		return this.prExamPatrolSettings;
	}

	public void setPrExamPatrolSettings(Set prExamPatrolSettings) {
		this.prExamPatrolSettings = prExamPatrolSettings;
	}

}