package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PeExamScoreInputUser generated by MyEclipse Persistence Tools
 */

public class PeExamScoreInputUser extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;
	private String name;
	private String password;
	private Set peTchCoursesForFkExamScoreInputUseraId = new HashSet(0);
	private Set peTchCoursesForFkExamScoreInputUserbId = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeExamScoreInputUser() {
	}

	/** minimal constructor */
	public PeExamScoreInputUser(String name, String password) {
		this.name = name;
		this.password = password;
	}

	/** full constructor */
	public PeExamScoreInputUser(String name, String password,
			Set peTchCoursesForFkExamScoreInputUseraId,
			Set peTchCoursesForFkExamScoreInputUserbId) {
		this.name = name;
		this.password = password;
		this.peTchCoursesForFkExamScoreInputUseraId = peTchCoursesForFkExamScoreInputUseraId;
		this.peTchCoursesForFkExamScoreInputUserbId = peTchCoursesForFkExamScoreInputUserbId;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getPeTchCoursesForFkExamScoreInputUseraId() {
		return this.peTchCoursesForFkExamScoreInputUseraId;
	}

	public void setPeTchCoursesForFkExamScoreInputUseraId(
			Set peTchCoursesForFkExamScoreInputUseraId) {
		this.peTchCoursesForFkExamScoreInputUseraId = peTchCoursesForFkExamScoreInputUseraId;
	}

	public Set getPeTchCoursesForFkExamScoreInputUserbId() {
		return this.peTchCoursesForFkExamScoreInputUserbId;
	}

	public void setPeTchCoursesForFkExamScoreInputUserbId(
			Set peTchCoursesForFkExamScoreInputUserbId) {
		this.peTchCoursesForFkExamScoreInputUserbId = peTchCoursesForFkExamScoreInputUserbId;
	}

}