package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeBzzStudent generated by MyEclipse - Hibernate Tools
 */

public class PeExamOnline extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields
	private String id;
	private String name; // 政治面貌名称
	private EnumConst enumConstByFlagPartyState; // status 状态：有效 无效
	
	private Date beginDate;
	
	private Date endDate;
	
	private String remark;
	
	// Constructors

	/** default constructor */
	public PeExamOnline() {
	}

	/** full constructor */
	public PeExamOnline(String id, String name,Date beginDate,Date endDate, String remark,EnumConst enumConstByFlagPartyState) {
		this.id = id ;
		this.name = name ;
		this.beginDate = beginDate ;
		this.endDate = endDate ;
		this.remark = remark;
		this.enumConstByFlagPartyState = enumConstByFlagPartyState;
	}

	// Property accessors
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public EnumConst getEnumConstByFlagPartyState() {
		return enumConstByFlagPartyState;
	}

	public void setEnumConstByFlagPartyState(EnumConst enumConstByFlagPartyState) {
		this.enumConstByFlagPartyState = enumConstByFlagPartyState;
	}

	public Date getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	
}