package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PeFeeLevel generated by MyEclipse Persistence Tools
 */

public class PeFeeLevel extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagBak;

	private EnumConst enumConstByFlagDefault;

	private String name;

	private Double feePercredit;

	private Double oweFeeLimit;

	private String note;

	private Set peStudents = new HashSet(0);

	private Set prEduMajorSiteFeeLevels = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeFeeLevel() {
	}

	/** minimal constructor */
	public PeFeeLevel(String name) {
		this.name = name;
	}

	/** full constructor */
	public PeFeeLevel(EnumConst enumConstByFlagBak,
			EnumConst enumConstByFlagDefault, String name, Double feePercredit,
			Double oweFeeLimit, String note, Set peStudents,
			Set prEduMajorSiteFeeLevels) {
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.enumConstByFlagDefault = enumConstByFlagDefault;
		this.name = name;
		this.feePercredit = feePercredit;
		this.oweFeeLimit = oweFeeLimit;
		this.note = note;
		this.peStudents = peStudents;
		this.prEduMajorSiteFeeLevels = prEduMajorSiteFeeLevels;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public EnumConst getEnumConstByFlagDefault() {
		return this.enumConstByFlagDefault;
	}

	public void setEnumConstByFlagDefault(EnumConst enumConstByFlagDefault) {
		this.enumConstByFlagDefault = enumConstByFlagDefault;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getFeePercredit() {
		return this.feePercredit;
	}

	public void setFeePercredit(Double feePercredit) {
		this.feePercredit = feePercredit;
	}

	public Double getOweFeeLimit() {
		return this.oweFeeLimit;
	}

	public void setOweFeeLimit(Double oweFeeLimit) {
		this.oweFeeLimit = oweFeeLimit;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPeStudents() {
		return this.peStudents;
	}

	public void setPeStudents(Set peStudents) {
		this.peStudents = peStudents;
	}

	public Set getPrEduMajorSiteFeeLevels() {
		return this.prEduMajorSiteFeeLevels;
	}

	public void setPrEduMajorSiteFeeLevels(Set prEduMajorSiteFeeLevels) {
		this.prEduMajorSiteFeeLevels = prEduMajorSiteFeeLevels;
	}

}