package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PeInfoNews generated by MyEclipse Persistence Tools
 */

public class PeInfoNews extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagIsactive;

	private PeInfoNewsType peInfoNewsType;

	private EnumConst enumConstByFlagNewsStatus;

	private PeManager peManager;

	private String title;

	private Date reportDate;

	private Date submitDate;

	private String confirmManagerId;

	private Long readCount;

	private String note;
	
	private String pictrue;
	
	private String isNew ;
	private String summary ;
	
	private PeEnterprise peSite;	//管理员所在的企业

	// Constructors


	public String getIsNew() {
		return isNew;
	}

	public void setIsNew(String isNew) {
		this.isNew = isNew;
	}

	/** default constructor */
	public PeInfoNews() {
	}

	/** minimal constructor */
	public PeInfoNews(String title) {
		this.title = title;
	}
	
	public String getPictrue() {
		return pictrue;
	}

	public void setPictrue(String pictrue) {
		this.pictrue = pictrue;
	}

	/** full constructor */
	public PeInfoNews(EnumConst enumConstByFlagIsactive,
			PeInfoNewsType peInfoNewsType, EnumConst enumConstByFlagNewsStatus,
			PeManager peManager, String title, Date reportDate,
			Date submitDate, String confirmManagerId, Long readCount,
			String note,String pictrue,String isNew,String summary) {
		this.enumConstByFlagIsactive = enumConstByFlagIsactive;
		this.peInfoNewsType = peInfoNewsType;
		this.enumConstByFlagNewsStatus = enumConstByFlagNewsStatus;
		this.peManager = peManager;
		this.title = title;
		this.reportDate = reportDate;
		this.submitDate = submitDate;
		this.confirmManagerId = confirmManagerId;
		this.readCount = readCount;
		this.note = note;
		this.pictrue = pictrue;
		this.isNew = isNew;
		this.summary = summary;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsactive() {
		return this.enumConstByFlagIsactive;
	}

	public void setEnumConstByFlagIsactive(EnumConst enumConstByFlagIsactive) {
		this.enumConstByFlagIsactive = enumConstByFlagIsactive;
	}

	public PeInfoNewsType getPeInfoNewsType() {
		return this.peInfoNewsType;
	}

	public void setPeInfoNewsType(PeInfoNewsType peInfoNewsType) {
		this.peInfoNewsType = peInfoNewsType;
	}

	public EnumConst getEnumConstByFlagNewsStatus() {
		return this.enumConstByFlagNewsStatus;
	}

	public void setEnumConstByFlagNewsStatus(EnumConst enumConstByFlagNewsStatus) {
		this.enumConstByFlagNewsStatus = enumConstByFlagNewsStatus;
	}

	public PeManager getPeManager() {
		return this.peManager;
	}

	public void setPeManager(PeManager peManager) {
		this.peManager = peManager;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public Date getSubmitDate() {
		return this.submitDate;
	}

	public void setSubmitDate(Date submitDate) {
		this.submitDate = submitDate;
	}

	public String getConfirmManagerId() {
		return this.confirmManagerId;
	}

	public void setConfirmManagerId(String confirmManagerId) {
		this.confirmManagerId = confirmManagerId;
	}

	public Long getReadCount() {
		return this.readCount;
	}

	public void setReadCount(Long readCount) {
		this.readCount = readCount;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public PeEnterprise getPeSite() {
		return peSite;
	}

	public void setPeSite(PeEnterprise peSite) {
		this.peSite = peSite;
	}
}