package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PeJianzhang generated by MyEclipse Persistence Tools
 */

public class PeJianzhang extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private Date creatDate;

	private String flagActive;

	private String jianzhang;

	// Constructors

	/** default constructor */
	public PeJianzhang() {
	}

	/** minimal constructor */
	public PeJianzhang(String name) {
		this.name = name;
	}

	/** full constructor */
	public PeJianzhang(String name, Date creatDate, String flagActive,
			String jianzhang) {
		this.name = name;
		this.creatDate = creatDate;
		this.flagActive = flagActive;
		this.jianzhang = jianzhang;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public String getFlagActive() {
		return this.flagActive;
	}

	public void setFlagActive(String flagActive) {
		this.flagActive = flagActive;
	}

	public String getJianzhang() {
		return this.jianzhang;
	}

	public void setJianzhang(String jianzhang) {
		this.jianzhang = jianzhang;
	}

}