package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeManager generated by MyEclipse Persistence Tools
 */

public class PeManager extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByGender;

	private EnumConst enumConstByFlagIsvalid;

	private SsoUser ssoUser;

	private String name;

	private String trueName;

	private String mobilePhone;

	private String phone;

	private String idCard;

	private String email;

	private String graduationInfo;

	private Date graduationDate;

	private String address;

	private String zhiCheng;
	
	private String position;

	private String workTime;

	private String loginId;

	private Set peInfoNewses = new HashSet(0);

	private Set peBulletins = new HashSet(0);
	
	private PePriRole pePriRole;
	
	private PeEnterprise peEnterprise;

	// Constructors

	public PePriRole getPePriRole() {
		if(this.pePriRole != null)
			return pePriRole;
		if(ssoUser != null)
			return this.ssoUser.getPePriRole();
		return null;
	}

	public void setPePriRole(PePriRole pePriRole) {
		this.pePriRole = pePriRole;
	}

	/** default constructor */
	public PeManager() {
	}

	/** minimal constructor */
	public PeManager(String name, String trueName) {
		this.name = name;
		this.trueName = trueName;
	}

	/** full constructor */
	public PeManager(EnumConst enumConstByGender,
			EnumConst enumConstByFlagIsvalid, SsoUser ssoUser, String name,
			String trueName, String mobilePhone, String phone, String idCard,
			String email, String graduationInfo, Date graduationDate,
			String address, String zhiCheng, String workTime, String loginId,
			Set peInfoNewses, Set peBulletins,PeEnterprise peEnterprise) {
		this.enumConstByGender = enumConstByGender;
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.ssoUser = ssoUser;
		this.name = name;
		this.trueName = trueName;
		this.mobilePhone = mobilePhone;
		this.phone = phone;
		this.idCard = idCard;
		this.email = email;
		this.graduationInfo = graduationInfo;
		this.graduationDate = graduationDate;
		this.address = address;
		this.zhiCheng = zhiCheng;
		this.workTime = workTime;
		this.loginId = loginId;
		this.peInfoNewses = peInfoNewses;
		this.peBulletins = peBulletins;
		this.peEnterprise = peEnterprise;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByGender() {
		return this.enumConstByGender;
	}

	public void setEnumConstByGender(EnumConst enumConstByGender) {
		this.enumConstByGender = enumConstByGender;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public SsoUser getSsoUser() {
		return this.ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTrueName() {
		return this.trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getGraduationInfo() {
		return this.graduationInfo;
	}

	public void setGraduationInfo(String graduationInfo) {
		this.graduationInfo = graduationInfo;
	}

	public Date getGraduationDate() {
		return this.graduationDate;
	}

	public void setGraduationDate(Date graduationDate) {
		this.graduationDate = graduationDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZhiCheng() {
		return this.zhiCheng;
	}

	public void setZhiCheng(String zhiCheng) {
		this.zhiCheng = zhiCheng;
	}

	public String getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(String workTime) {
		this.workTime = workTime;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public Set getPeInfoNewses() {
		return this.peInfoNewses;
	}

	public void setPeInfoNewses(Set peInfoNewses) {
		this.peInfoNewses = peInfoNewses;
	}

	public Set getPeBulletins() {
		return this.peBulletins;
	}

	public void setPeBulletins(Set peBulletins) {
		this.peBulletins = peBulletins;
	}

	public PeEnterprise getPeEnterprise() {
		return peEnterprise;
	}

	public void setPeEnterprise(PeEnterprise peEnterprise) {
		this.peEnterprise = peEnterprise;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	
	

}