package com.whaty.platform.entity.bean;

/**
 * PeSmsSystempoint generated by MyEclipse Persistence Tools
 */

public class PeSmsSystempoint extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagIsauto;

	private EnumConst enumConstByFlagSmsStatus;

	private String code;

	private String name;

	private String note;

	private String sqlNote;

	// Constructors

	/** default constructor */
	public PeSmsSystempoint() {
	}

	/** minimal constructor */
	public PeSmsSystempoint(String code, String name) {
		this.code = code;
		this.name = name;
	}

	/** full constructor */
	public PeSmsSystempoint(EnumConst enumConstByFlagIsauto,
			EnumConst enumConstByFlagSmsStatus, String code, String name,
			String note, String sqlNote) {
		this.enumConstByFlagIsauto = enumConstByFlagIsauto;
		this.enumConstByFlagSmsStatus = enumConstByFlagSmsStatus;
		this.code = code;
		this.name = name;
		this.note = note;
		this.sqlNote = sqlNote;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsauto() {
		return this.enumConstByFlagIsauto;
	}

	public void setEnumConstByFlagIsauto(EnumConst enumConstByFlagIsauto) {
		this.enumConstByFlagIsauto = enumConstByFlagIsauto;
	}

	public EnumConst getEnumConstByFlagSmsStatus() {
		return this.enumConstByFlagSmsStatus;
	}

	public void setEnumConstByFlagSmsStatus(EnumConst enumConstByFlagSmsStatus) {
		this.enumConstByFlagSmsStatus = enumConstByFlagSmsStatus;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getSqlNote() {
		return this.sqlNote;
	}

	public void setSqlNote(String sqlNote) {
		this.sqlNote = sqlNote;
	}

}