package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeSmsInfo generated by MyEclipse Persistence Tools
 */

public class PeSmsInfo extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagSmsStatus;

	private EnumConst enumConstByFlagSmsType;

	private PeSite peSite;

	private Date creatDate;

	private Date bookingDate;

	private Date sendDate;

	private String returnReason;

	private String senderName;

	private String senderLoginInId;

	private String note;

	private Set prSmsSendStatuses = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeSmsInfo() {
	}

	/** full constructor */
	public PeSmsInfo(EnumConst enumConstByFlagSmsStatus,
			EnumConst enumConstByFlagSmsType, PeSite peSite, Date creatDate,
			Date bookingDate, Date sendDate, String returnReason,
			String senderName, String senderLoginInId, String note,
			Set prSmsSendStatuses) {
		this.enumConstByFlagSmsStatus = enumConstByFlagSmsStatus;
		this.enumConstByFlagSmsType = enumConstByFlagSmsType;
		this.peSite = peSite;
		this.creatDate = creatDate;
		this.bookingDate = bookingDate;
		this.sendDate = sendDate;
		this.returnReason = returnReason;
		this.senderName = senderName;
		this.senderLoginInId = senderLoginInId;
		this.note = note;
		this.prSmsSendStatuses = prSmsSendStatuses;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagSmsStatus() {
		return this.enumConstByFlagSmsStatus;
	}

	public void setEnumConstByFlagSmsStatus(EnumConst enumConstByFlagSmsStatus) {
		this.enumConstByFlagSmsStatus = enumConstByFlagSmsStatus;
	}

	public EnumConst getEnumConstByFlagSmsType() {
		return this.enumConstByFlagSmsType;
	}

	public void setEnumConstByFlagSmsType(EnumConst enumConstByFlagSmsType) {
		this.enumConstByFlagSmsType = enumConstByFlagSmsType;
	}

	public PeSite getPeSite() {
		return this.peSite;
	}

	public void setPeSite(PeSite peSite) {
		this.peSite = peSite;
	}

	public Date getCreatDate() {
		return this.creatDate;
	}

	public void setCreatDate(Date creatDate) {
		this.creatDate = creatDate;
	}

	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getReturnReason() {
		return this.returnReason;
	}

	public void setReturnReason(String returnReason) {
		this.returnReason = returnReason;
	}

	public String getSenderName() {
		return this.senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	public String getSenderLoginInId() {
		return this.senderLoginInId;
	}

	public void setSenderLoginInId(String senderLoginInId) {
		this.senderLoginInId = senderLoginInId;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPrSmsSendStatuses() {
		return this.prSmsSendStatuses;
	}

	public void setPrSmsSendStatuses(Set prSmsSendStatuses) {
		this.prSmsSendStatuses = prSmsSendStatuses;
	}

}