package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PeTchCourseware generated by MyEclipse Persistence Tools
 */

public class PeTchCourseware extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagIsvalid;

	private EnumConst enumConstByFlagBak;

	private PeTchCourse peTchCourse;

	private String name;

	private String code;

	private String author;

	private String publisher;

	private String note;

	private String link;

	private Set prTchOpencourseCoursewares = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeTchCourseware() {
	}

	/** minimal constructor */
	public PeTchCourseware(String name) {
		this.name = name;
	}

	/** full constructor */
	public PeTchCourseware(EnumConst enumConstByFlagIsvalid,
			EnumConst enumConstByFlagBak, PeTchCourse peTchCourse, String name,
			String code, String author, String publisher, String note,
			String link, Set prTchOpencourseCoursewares) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.peTchCourse = peTchCourse;
		this.name = name;
		this.code = code;
		this.author = author;
		this.publisher = publisher;
		this.note = note;
		this.link = link;
		this.prTchOpencourseCoursewares = prTchOpencourseCoursewares;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public PeTchCourse getPeTchCourse() {
		return this.peTchCourse;
	}

	public void setPeTchCourse(PeTchCourse peTchCourse) {
		this.peTchCourse = peTchCourse;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Set getPrTchOpencourseCoursewares() {
		return this.prTchOpencourseCoursewares;
	}

	public void setPrTchOpencourseCoursewares(Set prTchOpencourseCoursewares) {
		this.prTchOpencourseCoursewares = prTchOpencourseCoursewares;
	}

}