package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PeTchCourse generated by MyEclipse Persistence Tools
 */

public class PeTchCourse extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagIsvalid; //是否有效

	private PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUseraId;

	private EnumConst enumConstByFlagIspubliccourse;

	private PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUserbId;

	private String name;

	private String code;

	private Double credit;

	private Double scoreSystemRate;

	private Double scoreHomeworkRate;

	private Double scoreExamRate;

	private Double scoreUsualRate;

	private String note;

	private Set peTchBooks = new HashSet(0);

	private Set prTchProgramCourses = new HashSet(0);

	private Set prExamOpenMaincourses = new HashSet(0);

	private Set prTchCourseTeachers = new HashSet(0);

	private Set prTchOpencourses = new HashSet(0);

	private Set peTchCoursewares = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeTchCourse() {
	}

	/** minimal constructor */
	public PeTchCourse(String name, String code) {
		this.name = name;
		this.code = code;
	}

	/** full constructor */
	public PeTchCourse(EnumConst enumConstByFlagIsvalid,
			PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUseraId,
			EnumConst enumConstByFlagIspubliccourse,
			PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUserbId,
			String name, String code, Double credit, Double scoreSystemRate,
			Double scoreHomeworkRate, Double scoreExamRate,
			Double scoreUsualRate, String note,
			Set peTchBooks, Set prTchProgramCourses, Set prExamOpenMaincourses,
			Set prTchCourseTeachers, Set prTchOpencourses, Set peTchCoursewares) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.peExamScoreInputUserByFkExamScoreInputUseraId = peExamScoreInputUserByFkExamScoreInputUseraId;
		this.enumConstByFlagIspubliccourse = enumConstByFlagIspubliccourse;
		this.peExamScoreInputUserByFkExamScoreInputUserbId = peExamScoreInputUserByFkExamScoreInputUserbId;
		this.name = name;
		this.code = code;
		this.credit = credit;
		this.scoreSystemRate = scoreSystemRate;
		this.scoreHomeworkRate = scoreHomeworkRate;
		this.scoreExamRate = scoreExamRate;
		this.scoreUsualRate = scoreUsualRate;
		this.note = note;
		this.peTchBooks = peTchBooks;
		this.prTchProgramCourses = prTchProgramCourses;
		this.prExamOpenMaincourses = prExamOpenMaincourses;
		this.prTchCourseTeachers = prTchCourseTeachers;
		this.prTchOpencourses = prTchOpencourses;
		this.peTchCoursewares = peTchCoursewares;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public PeExamScoreInputUser getPeExamScoreInputUserByFkExamScoreInputUseraId() {
		return this.peExamScoreInputUserByFkExamScoreInputUseraId;
	}

	public void setPeExamScoreInputUserByFkExamScoreInputUseraId(
			PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUseraId) {
		this.peExamScoreInputUserByFkExamScoreInputUseraId = peExamScoreInputUserByFkExamScoreInputUseraId;
	}

	public EnumConst getEnumConstByFlagIspubliccourse() {
		return this.enumConstByFlagIspubliccourse;
	}

	public void setEnumConstByFlagIspubliccourse(
			EnumConst enumConstByFlagIspubliccourse) {
		this.enumConstByFlagIspubliccourse = enumConstByFlagIspubliccourse;
	}

	public PeExamScoreInputUser getPeExamScoreInputUserByFkExamScoreInputUserbId() {
		return this.peExamScoreInputUserByFkExamScoreInputUserbId;
	}

	public void setPeExamScoreInputUserByFkExamScoreInputUserbId(
			PeExamScoreInputUser peExamScoreInputUserByFkExamScoreInputUserbId) {
		this.peExamScoreInputUserByFkExamScoreInputUserbId = peExamScoreInputUserByFkExamScoreInputUserbId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Double getCredit() {
		return this.credit;
	}

	public void setCredit(Double credit) {
		this.credit = credit;
	}

	public Double getScoreSystemRate() {
		return this.scoreSystemRate;
	}

	public void setScoreSystemRate(Double scoreSystemRate) {
		this.scoreSystemRate = scoreSystemRate;
	}

	public Double getScoreHomeworkRate() {
		return this.scoreHomeworkRate;
	}

	public void setScoreHomeworkRate(Double scoreHomeworkRate) {
		this.scoreHomeworkRate = scoreHomeworkRate;
	}

	public Double getScoreExamRate() {
		return this.scoreExamRate;
	}

	public void setScoreExamRate(Double scoreExamRate) {
		this.scoreExamRate = scoreExamRate;
	}

	public Double getScoreUsualRate() {
		return this.scoreUsualRate;
	}

	public void setScoreUsualRate(Double scoreUsualRate) {
		this.scoreUsualRate = scoreUsualRate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPeTchBooks() {
		return this.peTchBooks;
	}

	public void setPeTchBooks(Set peTchBooks) {
		this.peTchBooks = peTchBooks;
	}

	public Set getPrTchProgramCourses() {
		return this.prTchProgramCourses;
	}

	public void setPrTchProgramCourses(Set prTchProgramCourses) {
		this.prTchProgramCourses = prTchProgramCourses;
	}

	public Set getPrExamOpenMaincourses() {
		return this.prExamOpenMaincourses;
	}

	public void setPrExamOpenMaincourses(Set prExamOpenMaincourses) {
		this.prExamOpenMaincourses = prExamOpenMaincourses;
	}

	public Set getPrTchCourseTeachers() {
		return this.prTchCourseTeachers;
	}

	public void setPrTchCourseTeachers(Set prTchCourseTeachers) {
		this.prTchCourseTeachers = prTchCourseTeachers;
	}

	public Set getPrTchOpencourses() {
		return this.prTchOpencourses;
	}

	public void setPrTchOpencourses(Set prTchOpencourses) {
		this.prTchOpencourses = prTchOpencourses;
	}

	public Set getPeTchCoursewares() {
		return this.peTchCoursewares;
	}

	public void setPeTchCoursewares(Set peTchCoursewares) {
		this.peTchCoursewares = peTchCoursewares;
	}

}