package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PeTeacher generated by MyEclipse Persistence Tools
 */

public class PeTeacher extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagActive;

	private SsoUser ssoUser;

	private EnumConst enumConstByFlagMaxXueli;

	private EnumConst enumConstByFlagPaper;

	private EnumConst enumConstByGender;

	private PeMajor peMajor;

	private EnumConst enumConstByFlagZhicheng;

	private EnumConst enumConstByFlagMaxXuewei;

	private String loginId;

	private String name;

	private String trueName;

	private String idCard;

	private Date birthday;

	private String graduateSchool;

	private String graduateMajor;

	private String phoneOffice;

	private String phoneHome;

	private String mobilephone;

	private String email;

	private String workplace;

	private Long stuCountLimit;

	private String note;

	private Set prTchOpencourseTeachers = new HashSet(0);

	private Set prTchCourseTeachers = new HashSet(0);

	private Set homeworkInfos = new HashSet(0);

	private Set prTchPaperTitles = new HashSet(0);

	// Constructors

	/** default constructor */
	public PeTeacher() {
	}

	/** minimal constructor */
	public PeTeacher(EnumConst enumConstByFlagActive,
			EnumConst enumConstByFlagMaxXueli, EnumConst enumConstByFlagPaper,
			EnumConst enumConstByFlagZhicheng, String name, String trueName,
			String idCard, String mobilephone, String email) {
		this.enumConstByFlagActive = enumConstByFlagActive;
		this.enumConstByFlagMaxXueli = enumConstByFlagMaxXueli;
		this.enumConstByFlagPaper = enumConstByFlagPaper;
		this.enumConstByFlagZhicheng = enumConstByFlagZhicheng;
		this.name = name;
		this.trueName = trueName;
		this.idCard = idCard;
		this.mobilephone = mobilephone;
		this.email = email;
	}

	/** full constructor */
	public PeTeacher(EnumConst enumConstByFlagActive, SsoUser ssoUser,
			EnumConst enumConstByFlagMaxXueli, EnumConst enumConstByFlagPaper,
			EnumConst enumConstByGender, PeMajor peMajor,
			EnumConst enumConstByFlagZhicheng,
			EnumConst enumConstByFlagMaxXuewei, String loginId, String name,
			String trueName, String idCard, Date birthday,
			String graduateSchool, String graduateMajor, String phoneOffice,
			String phoneHome, String mobilephone, String email,
			String workplace, Long stuCountLimit, String note,
			Set prTchOpencourseTeachers, Set prTchCourseTeachers,
			Set homeworkInfos, Set prTchPaperTitles) {
		this.enumConstByFlagActive = enumConstByFlagActive;
		this.ssoUser = ssoUser;
		this.enumConstByFlagMaxXueli = enumConstByFlagMaxXueli;
		this.enumConstByFlagPaper = enumConstByFlagPaper;
		this.enumConstByGender = enumConstByGender;
		this.peMajor = peMajor;
		this.enumConstByFlagZhicheng = enumConstByFlagZhicheng;
		this.enumConstByFlagMaxXuewei = enumConstByFlagMaxXuewei;
		this.loginId = loginId;
		this.name = name;
		this.trueName = trueName;
		this.idCard = idCard;
		this.birthday = birthday;
		this.graduateSchool = graduateSchool;
		this.graduateMajor = graduateMajor;
		this.phoneOffice = phoneOffice;
		this.phoneHome = phoneHome;
		this.mobilephone = mobilephone;
		this.email = email;
		this.workplace = workplace;
		this.stuCountLimit = stuCountLimit;
		this.note = note;
		this.prTchOpencourseTeachers = prTchOpencourseTeachers;
		this.prTchCourseTeachers = prTchCourseTeachers;
		this.homeworkInfos = homeworkInfos;
		this.prTchPaperTitles = prTchPaperTitles;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagActive() {
		return this.enumConstByFlagActive;
	}

	public void setEnumConstByFlagActive(EnumConst enumConstByFlagActive) {
		this.enumConstByFlagActive = enumConstByFlagActive;
	}

	public SsoUser getSsoUser() {
		return this.ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public EnumConst getEnumConstByFlagMaxXueli() {
		return this.enumConstByFlagMaxXueli;
	}

	public void setEnumConstByFlagMaxXueli(EnumConst enumConstByFlagMaxXueli) {
		this.enumConstByFlagMaxXueli = enumConstByFlagMaxXueli;
	}

	public EnumConst getEnumConstByFlagPaper() {
		return this.enumConstByFlagPaper;
	}

	public void setEnumConstByFlagPaper(EnumConst enumConstByFlagPaper) {
		this.enumConstByFlagPaper = enumConstByFlagPaper;
	}

	public EnumConst getEnumConstByGender() {
		return this.enumConstByGender;
	}

	public void setEnumConstByGender(EnumConst enumConstByGender) {
		this.enumConstByGender = enumConstByGender;
	}

	public PeMajor getPeMajor() {
		return this.peMajor;
	}

	public void setPeMajor(PeMajor peMajor) {
		this.peMajor = peMajor;
	}

	public EnumConst getEnumConstByFlagZhicheng() {
		return this.enumConstByFlagZhicheng;
	}

	public void setEnumConstByFlagZhicheng(EnumConst enumConstByFlagZhicheng) {
		this.enumConstByFlagZhicheng = enumConstByFlagZhicheng;
	}

	public EnumConst getEnumConstByFlagMaxXuewei() {
		return this.enumConstByFlagMaxXuewei;
	}

	public void setEnumConstByFlagMaxXuewei(EnumConst enumConstByFlagMaxXuewei) {
		this.enumConstByFlagMaxXuewei = enumConstByFlagMaxXuewei;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTrueName() {
		return this.trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getGraduateSchool() {
		return this.graduateSchool;
	}

	public void setGraduateSchool(String graduateSchool) {
		this.graduateSchool = graduateSchool;
	}

	public String getGraduateMajor() {
		return this.graduateMajor;
	}

	public void setGraduateMajor(String graduateMajor) {
		this.graduateMajor = graduateMajor;
	}

	public String getPhoneOffice() {
		return this.phoneOffice;
	}

	public void setPhoneOffice(String phoneOffice) {
		this.phoneOffice = phoneOffice;
	}

	public String getPhoneHome() {
		return this.phoneHome;
	}

	public void setPhoneHome(String phoneHome) {
		this.phoneHome = phoneHome;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWorkplace() {
		return this.workplace;
	}

	public void setWorkplace(String workplace) {
		this.workplace = workplace;
	}

	public Long getStuCountLimit() {
		return this.stuCountLimit;
	}

	public void setStuCountLimit(Long stuCountLimit) {
		this.stuCountLimit = stuCountLimit;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPrTchOpencourseTeachers() {
		return this.prTchOpencourseTeachers;
	}

	public void setPrTchOpencourseTeachers(Set prTchOpencourseTeachers) {
		this.prTchOpencourseTeachers = prTchOpencourseTeachers;
	}

	public Set getPrTchCourseTeachers() {
		return this.prTchCourseTeachers;
	}

	public void setPrTchCourseTeachers(Set prTchCourseTeachers) {
		this.prTchCourseTeachers = prTchCourseTeachers;
	}

	public Set getHomeworkInfos() {
		return this.homeworkInfos;
	}

	public void setHomeworkInfos(Set homeworkInfos) {
		this.homeworkInfos = homeworkInfos;
	}

	public Set getPrTchPaperTitles() {
		return this.prTchPaperTitles;
	}

	public void setPrTchPaperTitles(Set prTchPaperTitles) {
		this.prTchPaperTitles = prTchPaperTitles;
	}

}