package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * PrBzzTchOpencourse generated by MyEclipse - Hibernate Tools
 */

public class PrBzzTchOpencourse extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {


    // Fields    

     private String id;
     private PeBzzBatch peBzzBatch;
     private EnumConst enumConstByFlagCourseType;
     private PeBzzTchCourse peBzzTchCourse;
     private String flagBak;
     private Integer roomId;
     private Set prBzzTchStuElectives = new HashSet(0);
     private Set trainingCourseStudents=new HashSet(0);
     private Set prBzzTchStuElectiveBack = new HashSet(0);
     private EnumConst enumConstByFlagIsvalid;  //开课表中新添加一个是否有效字段  20120405 gaoyuan
     private EnumConst enumConstByFlagChoose;  //开课表中新添加一个是否有效字段  20120405 gaoyuan
     private EnumConst enumConstByFlagCourseItemType;
     
    // Constructors

    public EnumConst getEnumConstByFlagIsvalid() {
		return enumConstByFlagIsvalid;
	}


	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}


	/** default constructor */
    public PrBzzTchOpencourse() {
    }

    
    /** full constructor */
    public PrBzzTchOpencourse(Integer roomId,PeBzzBatch peBzzBatch, EnumConst enumConstByFlagCourseType, PeBzzTchCourse peBzzTchCourse, String flagBak, Set prBzzTchStuElectives,Set trainingCourseStudents) {
        this.peBzzBatch = peBzzBatch;
        this.enumConstByFlagCourseType = enumConstByFlagCourseType;
        this.peBzzTchCourse = peBzzTchCourse;
        this.flagBak = flagBak;
        this.prBzzTchStuElectives = prBzzTchStuElectives;
        this.trainingCourseStudents=trainingCourseStudents;
        this.roomId = roomId;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public PeBzzBatch getPeBzzBatch() {
        return this.peBzzBatch;
    }
    
    public void setPeBzzBatch(PeBzzBatch peBzzBatch) {
        this.peBzzBatch = peBzzBatch;
    }


    public EnumConst getEnumConstByFlagCourseType() {
		return enumConstByFlagCourseType;
	}


	public void setEnumConstByFlagCourseType(EnumConst enumConstByFlagCourseType) {
		this.enumConstByFlagCourseType = enumConstByFlagCourseType;
	}


	public PeBzzTchCourse getPeBzzTchCourse() {
        return this.peBzzTchCourse;
    }
    
    public void setPeBzzTchCourse(PeBzzTchCourse peBzzTchCourse) {
        this.peBzzTchCourse = peBzzTchCourse;
    }

    public String getFlagBak() {
        return this.flagBak;
    }
    
    public void setFlagBak(String flagBak) {
        this.flagBak = flagBak;
    }

    public Set getPrBzzTchStuElectives() {
        return this.prBzzTchStuElectives;
    }
    
    public void setPrBzzTchStuElectives(Set prBzzTchStuElectives) {
        this.prBzzTchStuElectives = prBzzTchStuElectives;
    }
   
    public Set getTrainingCourseStudents(){
    	return this.trainingCourseStudents;
    }
    
    public void setTrainingCourseStudents(Set trainingCourseStudents){
    	this.trainingCourseStudents=trainingCourseStudents;
    }


	public Integer getRoomId() {
		return roomId;
	}


	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}


	public Set getPrBzzTchStuElectiveBack() {
		return prBzzTchStuElectiveBack;
	}


	public void setPrBzzTchStuElectiveBack(Set prBzzTchStuElectiveBack) {
		this.prBzzTchStuElectiveBack = prBzzTchStuElectiveBack;
	}


	public EnumConst getEnumConstByFlagCourseItemType() {
		return enumConstByFlagCourseItemType;
	}


	public void setEnumConstByFlagCourseItemType(
			EnumConst enumConstByFlagCourseItemType) {
		this.enumConstByFlagCourseItemType = enumConstByFlagCourseItemType;
	}


	public EnumConst getEnumConstByFlagChoose() {
		return enumConstByFlagChoose;
	}


	public void setEnumConstByFlagChoose(EnumConst enumConstByFlagChoose) {
		this.enumConstByFlagChoose = enumConstByFlagChoose;
	}


}