package com.whaty.platform.entity.bean;



/**
 * PrBzzPriManagerEnterprise generated by MyEclipse - Hibernate Tools
 */

public class PrBzzPriManagerEnterprise extends com.whaty.platform.entity.bean.AbstractBean implements java.io.Serializable {


    // Fields    

     private String id;
     private SsoUser ssoUser;
     private PeEnterprise peEnterprise;


    // Constructors

    /** default constructor */
    public PrBzzPriManagerEnterprise() {
    }

    
    /** full constructor */
    public PrBzzPriManagerEnterprise(SsoUser ssoUser, PeEnterprise peEnterprise) {
        this.ssoUser = ssoUser;
        this.peEnterprise = peEnterprise;
    }

   
    // Property accessors

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    public SsoUser getSsoUser() {
        return this.ssoUser;
    }
    
    public void setSsoUser(SsoUser ssoUser) {
        this.ssoUser = ssoUser;
    }

    public PeEnterprise getPeEnterprise() {
        return this.peEnterprise;
    }
    
    public void setPeEnterprise(PeEnterprise peEnterprise) {
        this.peEnterprise = peEnterprise;
    }
   








}