package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PrExamOpenMaincourse generated by MyEclipse Persistence Tools
 */

public class PrExamOpenMaincourse extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private PeExamMaincourseNo peExamMaincourseNo;

	private PeTchCourse peTchCourse;

	private Set prExamStuMaincourses = new HashSet(0);

	private Set peExamMaincourseRooms = new HashSet(0);

	// Constructors

	/** default constructor */
	public PrExamOpenMaincourse() {
	}

	/** full constructor */
	public PrExamOpenMaincourse(PeExamMaincourseNo peExamMaincourseNo,
			PeTchCourse peTchCourse, Set prExamStuMaincourses,
			Set peExamMaincourseRooms) {
		this.peExamMaincourseNo = peExamMaincourseNo;
		this.peTchCourse = peTchCourse;
		this.prExamStuMaincourses = prExamStuMaincourses;
		this.peExamMaincourseRooms = peExamMaincourseRooms;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeExamMaincourseNo getPeExamMaincourseNo() {
		return this.peExamMaincourseNo;
	}

	public void setPeExamMaincourseNo(PeExamMaincourseNo peExamMaincourseNo) {
		this.peExamMaincourseNo = peExamMaincourseNo;
	}

	public PeTchCourse getPeTchCourse() {
		return this.peTchCourse;
	}

	public void setPeTchCourse(PeTchCourse peTchCourse) {
		this.peTchCourse = peTchCourse;
	}

	public Set getPrExamStuMaincourses() {
		return this.prExamStuMaincourses;
	}

	public void setPrExamStuMaincourses(Set prExamStuMaincourses) {
		this.prExamStuMaincourses = prExamStuMaincourses;
	}

	public Set getPeExamMaincourseRooms() {
		return this.peExamMaincourseRooms;
	}

	public void setPeExamMaincourseRooms(Set peExamMaincourseRooms) {
		this.peExamMaincourseRooms = peExamMaincourseRooms;
	}

}