package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PrFeeDetail generated by MyEclipse Persistence Tools
 */

public class PrFeeDetail extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private PeStudent peStudent;

	private PeFeeBatch peFeeBatch;

	private EnumConst enumConstByFlagFeeType;

	private EnumConst enumConstByFlagFeeCheck;

	private Double feeAmount;

	private Double creditAmount;

	private Date inputDate;

	private String note;

	private String invoiceNo;

	// Constructors

	/** default constructor */
	public PrFeeDetail() {
	}

	/** full constructor */
	public PrFeeDetail(PeStudent peStudent, PeFeeBatch peFeeBatch,
			EnumConst enumConstByFlagFeeType,
			EnumConst enumConstByFlagFeeCheck, Double feeAmount,
			Double creditAmount, Date inputDate, String note, String invoiceNo) {
		this.peStudent = peStudent;
		this.peFeeBatch = peFeeBatch;
		this.enumConstByFlagFeeType = enumConstByFlagFeeType;
		this.enumConstByFlagFeeCheck = enumConstByFlagFeeCheck;
		this.feeAmount = feeAmount;
		this.creditAmount = creditAmount;
		this.inputDate = inputDate;
		this.note = note;
		this.invoiceNo = invoiceNo;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeStudent getPeStudent() {
		return this.peStudent;
	}

	public void setPeStudent(PeStudent peStudent) {
		this.peStudent = peStudent;
	}

	public PeFeeBatch getPeFeeBatch() {
		return this.peFeeBatch;
	}

	public void setPeFeeBatch(PeFeeBatch peFeeBatch) {
		this.peFeeBatch = peFeeBatch;
	}

	public EnumConst getEnumConstByFlagFeeType() {
		return this.enumConstByFlagFeeType;
	}

	public void setEnumConstByFlagFeeType(EnumConst enumConstByFlagFeeType) {
		this.enumConstByFlagFeeType = enumConstByFlagFeeType;
	}

	public EnumConst getEnumConstByFlagFeeCheck() {
		return this.enumConstByFlagFeeCheck;
	}

	public void setEnumConstByFlagFeeCheck(EnumConst enumConstByFlagFeeCheck) {
		this.enumConstByFlagFeeCheck = enumConstByFlagFeeCheck;
	}

	public Double getFeeAmount() {
		return this.feeAmount;
	}

	public void setFeeAmount(Double feeAmount) {
		this.feeAmount = feeAmount;
	}

	public Double getCreditAmount() {
		return this.creditAmount;
	}

	public void setCreditAmount(Double creditAmount) {
		this.creditAmount = creditAmount;
	}

	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

}