package com.whaty.platform.entity.bean;

/**
 * PrPriManagerMajor generated by MyEclipse Persistence Tools
 */

public class PrPriManagerMajor extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private SsoUser ssoUser;

	private PeMajor peMajor;

	// Constructors

	/** default constructor */
	public PrPriManagerMajor() {
	}

	/** full constructor */
	public PrPriManagerMajor(SsoUser ssoUser, PeMajor peMajor) {
		this.ssoUser = ssoUser;
		this.peMajor = peMajor;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public SsoUser getSsoUser() {
		return this.ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public PeMajor getPeMajor() {
		return this.peMajor;
	}

	public void setPeMajor(PeMajor peMajor) {
		this.peMajor = peMajor;
	}

}