package com.whaty.platform.entity.bean;

/**
 * PrRecPatrolSetting generated by MyEclipse Persistence Tools
 */

public class PrRecPatrolSetting extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private PeExamPatrol peExamPatrol;

	private PeRecruitplan peRecruitplan;

	private PeSite peSite;

	// Constructors

	/** default constructor */
	public PrRecPatrolSetting() {
	}

	/** full constructor */
	public PrRecPatrolSetting(PeExamPatrol peExamPatrol,
			PeRecruitplan peRecruitplan, PeSite peSite) {
		this.peExamPatrol = peExamPatrol;
		this.peRecruitplan = peRecruitplan;
		this.peSite = peSite;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeExamPatrol getPeExamPatrol() {
		return this.peExamPatrol;
	}

	public void setPeExamPatrol(PeExamPatrol peExamPatrol) {
		this.peExamPatrol = peExamPatrol;
	}

	public PeRecruitplan getPeRecruitplan() {
		return this.peRecruitplan;
	}

	public void setPeRecruitplan(PeRecruitplan peRecruitplan) {
		this.peRecruitplan = peRecruitplan;
	}

	public PeSite getPeSite() {
		return this.peSite;
	}

	public void setPeSite(PeSite peSite) {
		this.peSite = peSite;
	}

}