package com.whaty.platform.entity.bean;

/**
 * PrTchOpencourseCourseware generated by MyEclipse Persistence Tools
 */

public class PrTchOpencourseCourseware extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private PrTchOpencourse prTchOpencourse;

	private PeTchCourseware peTchCourseware;

	// Constructors

	/** default constructor */
	public PrTchOpencourseCourseware() {
	}

	/** full constructor */
	public PrTchOpencourseCourseware(PrTchOpencourse prTchOpencourse,
			PeTchCourseware peTchCourseware) {
		this.prTchOpencourse = prTchOpencourse;
		this.peTchCourseware = peTchCourseware;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PrTchOpencourse getPrTchOpencourse() {
		return this.prTchOpencourse;
	}

	public void setPrTchOpencourse(PrTchOpencourse prTchOpencourse) {
		this.prTchOpencourse = prTchOpencourse;
	}

	public PeTchCourseware getPeTchCourseware() {
		return this.peTchCourseware;
	}

	public void setPeTchCourseware(PeTchCourseware peTchCourseware) {
		this.peTchCourseware = peTchCourseware;
	}

}