package com.whaty.platform.entity.bean;

/**
 * PrTchCourseTeacher generated by MyEclipse Persistence Tools
 */

public class PrTchCourseTeacher extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagTeacherType;

	private EnumConst enumConstByFlagBak;

	private PeTeacher peTeacher;

	private PeTchCourse peTchCourse;

	// Constructors

	/** default constructor */
	public PrTchCourseTeacher() {
	}

	/** full constructor */
	public PrTchCourseTeacher(EnumConst enumConstByFlagTeacherType,
			EnumConst enumConstByFlagBak, PeTeacher peTeacher,
			PeTchCourse peTchCourse) {
		this.enumConstByFlagTeacherType = enumConstByFlagTeacherType;
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.peTeacher = peTeacher;
		this.peTchCourse = peTchCourse;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagTeacherType() {
		return this.enumConstByFlagTeacherType;
	}

	public void setEnumConstByFlagTeacherType(
			EnumConst enumConstByFlagTeacherType) {
		this.enumConstByFlagTeacherType = enumConstByFlagTeacherType;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public PeTeacher getPeTeacher() {
		return this.peTeacher;
	}

	public void setPeTeacher(PeTeacher peTeacher) {
		this.peTeacher = peTeacher;
	}

	public PeTchCourse getPeTchCourse() {
		return this.peTchCourse;
	}

	public void setPeTchCourse(PeTchCourse peTchCourse) {
		this.peTchCourse = peTchCourse;
	}

}