package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrTchStuElective generated by MyEclipse Persistence Tools
 */

public class PrTchStuElective extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagScorePub;

	private SsoUser ssoUser;

	private EnumConst enumConstByFlagScoreStatus;

	private PrTchOpencourse prTchOpencourse;

	private PrTchProgramCourse prTchProgramCourse;

	private PeStudent peStudent;

	private EnumConst enumConstByFlagElectiveAdmission;

	private Date electiveDate;

	private String pri;

	private Double scoreSystem;

	private Double scoreUsual;

	private Double scoreHomework;

	private Double scoreExam;

	private Double scoreTotal;

	private String onlineTime;

	private Long enterTimes;

	private Set prTchElectiveBooks = new HashSet(0);

	private Set prExamBookings = new HashSet(0);

	// Constructors

	/** default constructor */
	public PrTchStuElective() {
	}

	/** minimal constructor */
	public PrTchStuElective(Date electiveDate) {
		this.electiveDate = electiveDate;
	}

	/** full constructor */
	public PrTchStuElective(EnumConst enumConstByFlagScorePub, SsoUser ssoUser,
			EnumConst enumConstByFlagScoreStatus,
			PrTchOpencourse prTchOpencourse,
			PrTchProgramCourse prTchProgramCourse, PeStudent peStudent,
			EnumConst enumConstByFlagElectiveAdmission, Date electiveDate,
			String pri, Double scoreSystem, Double scoreUsual,
			Double scoreHomework, Double scoreExam, Double scoreTotal,
			String onlineTime, Long enterTimes, Set prTchElectiveBooks,
			Set prExamBookings) {
		this.enumConstByFlagScorePub = enumConstByFlagScorePub;
		this.ssoUser = ssoUser;
		this.enumConstByFlagScoreStatus = enumConstByFlagScoreStatus;
		this.prTchOpencourse = prTchOpencourse;
		this.prTchProgramCourse = prTchProgramCourse;
		this.peStudent = peStudent;
		this.enumConstByFlagElectiveAdmission = enumConstByFlagElectiveAdmission;
		this.electiveDate = electiveDate;
		this.pri = pri;
		this.scoreSystem = scoreSystem;
		this.scoreUsual = scoreUsual;
		this.scoreHomework = scoreHomework;
		this.scoreExam = scoreExam;
		this.scoreTotal = scoreTotal;
		this.onlineTime = onlineTime;
		this.enterTimes = enterTimes;
		this.prTchElectiveBooks = prTchElectiveBooks;
		this.prExamBookings = prExamBookings;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagScorePub() {
		return this.enumConstByFlagScorePub;
	}

	public void setEnumConstByFlagScorePub(EnumConst enumConstByFlagScorePub) {
		this.enumConstByFlagScorePub = enumConstByFlagScorePub;
	}

	public SsoUser getSsoUser() {
		return this.ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public EnumConst getEnumConstByFlagScoreStatus() {
		return this.enumConstByFlagScoreStatus;
	}

	public void setEnumConstByFlagScoreStatus(
			EnumConst enumConstByFlagScoreStatus) {
		this.enumConstByFlagScoreStatus = enumConstByFlagScoreStatus;
	}

	public PrTchOpencourse getPrTchOpencourse() {
		return this.prTchOpencourse;
	}

	public void setPrTchOpencourse(PrTchOpencourse prTchOpencourse) {
		this.prTchOpencourse = prTchOpencourse;
	}

	public PrTchProgramCourse getPrTchProgramCourse() {
		return this.prTchProgramCourse;
	}

	public void setPrTchProgramCourse(PrTchProgramCourse prTchProgramCourse) {
		this.prTchProgramCourse = prTchProgramCourse;
	}

	public PeStudent getPeStudent() {
		return this.peStudent;
	}

	public void setPeStudent(PeStudent peStudent) {
		this.peStudent = peStudent;
	}

	public EnumConst getEnumConstByFlagElectiveAdmission() {
		return this.enumConstByFlagElectiveAdmission;
	}

	public void setEnumConstByFlagElectiveAdmission(
			EnumConst enumConstByFlagElectiveAdmission) {
		this.enumConstByFlagElectiveAdmission = enumConstByFlagElectiveAdmission;
	}

	public Date getElectiveDate() {
		return this.electiveDate;
	}

	public void setElectiveDate(Date electiveDate) {
		this.electiveDate = electiveDate;
	}

	public String getPri() {
		return this.pri;
	}

	public void setPri(String pri) {
		this.pri = pri;
	}

	public Double getScoreSystem() {
		return this.scoreSystem;
	}

	public void setScoreSystem(Double scoreSystem) {
		this.scoreSystem = scoreSystem;
	}

	public Double getScoreUsual() {
		return this.scoreUsual;
	}

	public void setScoreUsual(Double scoreUsual) {
		this.scoreUsual = scoreUsual;
	}

	public Double getScoreHomework() {
		return this.scoreHomework;
	}

	public void setScoreHomework(Double scoreHomework) {
		this.scoreHomework = scoreHomework;
	}

	public Double getScoreExam() {
		return this.scoreExam;
	}

	public void setScoreExam(Double scoreExam) {
		this.scoreExam = scoreExam;
	}

	public Double getScoreTotal() {
		return this.scoreTotal;
	}

	public void setScoreTotal(Double scoreTotal) {
		this.scoreTotal = scoreTotal;
	}

	public String getOnlineTime() {
		return this.onlineTime;
	}

	public void setOnlineTime(String onlineTime) {
		this.onlineTime = onlineTime;
	}

	public Long getEnterTimes() {
		return this.enterTimes;
	}

	public void setEnterTimes(Long enterTimes) {
		this.enterTimes = enterTimes;
	}

	public Set getPrTchElectiveBooks() {
		return this.prTchElectiveBooks;
	}

	public void setPrTchElectiveBooks(Set prTchElectiveBooks) {
		this.prTchElectiveBooks = prTchElectiveBooks;
	}

	public Set getPrExamBookings() {
		return this.prExamBookings;
	}

	public void setPrExamBookings(Set prExamBookings) {
		this.prExamBookings = prExamBookings;
	}

}