package com.whaty.platform.entity.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * PrTchPaperTitle generated by MyEclipse Persistence Tools
 */

public class PrTchPaperTitle extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private PeTeacher peTeacher;

	private PeSemester peSemester;

	private String title;

	private String titleMemo;

	private Long stuCountLimit;
	
	private Long titleAlreadySelect;
	
	private String isCurrentTitle;

	private Set prTchStuPapers = new HashSet(0);

	// Constructors

	/** default constructor */
	public PrTchPaperTitle() {
	}

	/** minimal constructor */
	public PrTchPaperTitle(String title) {
		this.title = title;
	}

	/** full constructor */
	public PrTchPaperTitle(PeTeacher peTeacher, PeSemester peSemester,
			String title, String titleMemo, Long stuCountLimit,
			Set prTchStuPapers) {
		this.peTeacher = peTeacher;
		this.peSemester = peSemester;
		this.title = title;
		this.titleMemo = titleMemo;
		this.stuCountLimit = stuCountLimit;
		this.prTchStuPapers = prTchStuPapers;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeTeacher getPeTeacher() {
		return this.peTeacher;
	}

	public void setPeTeacher(PeTeacher peTeacher) {
		this.peTeacher = peTeacher;
	}

	public PeSemester getPeSemester() {
		return this.peSemester;
	}

	public void setPeSemester(PeSemester peSemester) {
		this.peSemester = peSemester;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleMemo() {
		return this.titleMemo;
	}

	public void setTitleMemo(String titleMemo) {
		this.titleMemo = titleMemo;
	}

	public Long getStuCountLimit() {
		return this.stuCountLimit;
	}

	public void setStuCountLimit(Long stuCountLimit) {
		this.stuCountLimit = stuCountLimit;
	}

	public Set getPrTchStuPapers() {
		return this.prTchStuPapers;
	}

	public void setPrTchStuPapers(Set prTchStuPapers) {
		this.prTchStuPapers = prTchStuPapers;
	}

	public String getIsCurrentTitle() {
		return isCurrentTitle;
	}

	public void setIsCurrentTitle(String isCurrentTitle) {
		this.isCurrentTitle = isCurrentTitle;
	}

	public Long getTitleAlreadySelect() {
		return titleAlreadySelect;
	}

	public void setTitleAlreadySelect(Long titleAlreadySelect) {
		this.titleAlreadySelect = titleAlreadySelect;
	}

}