package com.whaty.platform.entity.bean;

/**
 * PrTchOpencourseTeacher generated by MyEclipse Persistence Tools
 */

public class PrTchOpencourseTeacher extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private PrTchOpencourse prTchOpencourse;

	private PeTeacher peTeacher;

	// Constructors

	/** default constructor */
	public PrTchOpencourseTeacher() {
	}

	/** full constructor */
	public PrTchOpencourseTeacher(PrTchOpencourse prTchOpencourse,
			PeTeacher peTeacher) {
		this.prTchOpencourse = prTchOpencourse;
		this.peTeacher = peTeacher;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PrTchOpencourse getPrTchOpencourse() {
		return this.prTchOpencourse;
	}

	public void setPrTchOpencourse(PrTchOpencourse prTchOpencourse) {
		this.prTchOpencourse = prTchOpencourse;
	}

	public PeTeacher getPeTeacher() {
		return this.peTeacher;
	}

	public void setPeTeacher(PeTeacher peTeacher) {
		this.peTeacher = peTeacher;
	}

}