package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrTchStuPaper generated by MyEclipse Persistence Tools
 */

public class PrTchStuPaper extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;

	private PeStudent peStudent;

	private EnumConst enumConstByFlagPaperRejoin;

	private EnumConst enumConstByFlagTitleAdmission;

	private PeTchRejoinSection peTchRejoinSection;

	private PrTchPaperTitle prTchPaperTitle;

	private EnumConst enumConstByFlagFinalLastUpdate;

	private PeTchRejoinRoom peTchRejoinRoom;

	private EnumConst enumConstByFlagSyllabusLastUpdate;

	private EnumConst enumConstByFlagDraftALastUpdate;

	private Date titleDate;

	private Double finalScore;

	private Date finalScoreDate;

	private Double rejoinScore;

	private Double scoreTotal;

	private Set prTchPaperContents = new HashSet(0);

	// Constructors

	/** default constructor */
	public PrTchStuPaper() {
	}

	/** full constructor */
	public PrTchStuPaper(PeStudent peStudent,
			EnumConst enumConstByFlagPaperRejoin,
			EnumConst enumConstByFlagTitleAdmission,
			PeTchRejoinSection peTchRejoinSection,
			PrTchPaperTitle prTchPaperTitle,
			EnumConst enumConstByFlagFinalLastUpdate,
			PeTchRejoinRoom peTchRejoinRoom,
			EnumConst enumConstByFlagSyllabusLastUpdate,
			EnumConst enumConstByFlagDraftALastUpdate, Date titleDate,
			Double finalScore, Date finalScoreDate, Double rejoinScore,
			Double scoreTotal, Set prTchPaperContents) {
		this.peStudent = peStudent;
		this.enumConstByFlagPaperRejoin = enumConstByFlagPaperRejoin;
		this.enumConstByFlagTitleAdmission = enumConstByFlagTitleAdmission;
		this.peTchRejoinSection = peTchRejoinSection;
		this.prTchPaperTitle = prTchPaperTitle;
		this.enumConstByFlagFinalLastUpdate = enumConstByFlagFinalLastUpdate;
		this.peTchRejoinRoom = peTchRejoinRoom;
		this.enumConstByFlagSyllabusLastUpdate = enumConstByFlagSyllabusLastUpdate;
		this.enumConstByFlagDraftALastUpdate = enumConstByFlagDraftALastUpdate;
		this.titleDate = titleDate;
		this.finalScore = finalScore;
		this.finalScoreDate = finalScoreDate;
		this.rejoinScore = rejoinScore;
		this.scoreTotal = scoreTotal;
		this.prTchPaperContents = prTchPaperContents;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeStudent getPeStudent() {
		return this.peStudent;
	}

	public void setPeStudent(PeStudent peStudent) {
		this.peStudent = peStudent;
	}

	public EnumConst getEnumConstByFlagPaperRejoin() {
		return this.enumConstByFlagPaperRejoin;
	}

	public void setEnumConstByFlagPaperRejoin(
			EnumConst enumConstByFlagPaperRejoin) {
		this.enumConstByFlagPaperRejoin = enumConstByFlagPaperRejoin;
	}

	public EnumConst getEnumConstByFlagTitleAdmission() {
		return this.enumConstByFlagTitleAdmission;
	}

	public void setEnumConstByFlagTitleAdmission(
			EnumConst enumConstByFlagTitleAdmission) {
		this.enumConstByFlagTitleAdmission = enumConstByFlagTitleAdmission;
	}

	public PeTchRejoinSection getPeTchRejoinSection() {
		return this.peTchRejoinSection;
	}

	public void setPeTchRejoinSection(PeTchRejoinSection peTchRejoinSection) {
		this.peTchRejoinSection = peTchRejoinSection;
	}

	public PrTchPaperTitle getPrTchPaperTitle() {
		return this.prTchPaperTitle;
	}

	public void setPrTchPaperTitle(PrTchPaperTitle prTchPaperTitle) {
		this.prTchPaperTitle = prTchPaperTitle;
	}

	public EnumConst getEnumConstByFlagFinalLastUpdate() {
		return this.enumConstByFlagFinalLastUpdate;
	}

	public void setEnumConstByFlagFinalLastUpdate(
			EnumConst enumConstByFlagFinalLastUpdate) {
		this.enumConstByFlagFinalLastUpdate = enumConstByFlagFinalLastUpdate;
	}

	public PeTchRejoinRoom getPeTchRejoinRoom() {
		return this.peTchRejoinRoom;
	}

	public void setPeTchRejoinRoom(PeTchRejoinRoom peTchRejoinRoom) {
		this.peTchRejoinRoom = peTchRejoinRoom;
	}

	public EnumConst getEnumConstByFlagSyllabusLastUpdate() {
		return this.enumConstByFlagSyllabusLastUpdate;
	}

	public void setEnumConstByFlagSyllabusLastUpdate(
			EnumConst enumConstByFlagSyllabusLastUpdate) {
		this.enumConstByFlagSyllabusLastUpdate = enumConstByFlagSyllabusLastUpdate;
	}

	public EnumConst getEnumConstByFlagDraftALastUpdate() {
		return this.enumConstByFlagDraftALastUpdate;
	}

	public void setEnumConstByFlagDraftALastUpdate(
			EnumConst enumConstByFlagDraftALastUpdate) {
		this.enumConstByFlagDraftALastUpdate = enumConstByFlagDraftALastUpdate;
	}

	public Date getTitleDate() {
		return this.titleDate;
	}

	public void setTitleDate(Date titleDate) {
		this.titleDate = titleDate;
	}

	public Double getFinalScore() {
		return this.finalScore;
	}

	public void setFinalScore(Double finalScore) {
		this.finalScore = finalScore;
	}

	public Date getFinalScoreDate() {
		return this.finalScoreDate;
	}

	public void setFinalScoreDate(Date finalScoreDate) {
		this.finalScoreDate = finalScoreDate;
	}

	public Double getRejoinScore() {
		return this.rejoinScore;
	}

	public void setRejoinScore(Double rejoinScore) {
		this.rejoinScore = rejoinScore;
	}

	public Double getScoreTotal() {
		return this.scoreTotal;
	}

	public void setScoreTotal(Double scoreTotal) {
		this.scoreTotal = scoreTotal;
	}

	public Set getPrTchPaperContents() {
		return this.prTchPaperContents;
	}

	public void setPrTchPaperContents(Set prTchPaperContents) {
		this.prTchPaperContents = prTchPaperContents;
	}

}