package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PrTchPaperContent generated by MyEclipse Persistence Tools
 */

public class PrTchPaperContent extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagPaperSection;

	private PrTchStuPaper prTchStuPaper;

	private EnumConst enumConstByFlagActionUser;

	private String url;

	private String note;

	private Date actionDate;

	// Constructors

	/** default constructor */
	public PrTchPaperContent() {
	}

	/** minimal constructor */
	public PrTchPaperContent(EnumConst enumConstByFlagPaperSection,
			PrTchStuPaper prTchStuPaper, EnumConst enumConstByFlagActionUser,
			Date actionDate) {
		this.enumConstByFlagPaperSection = enumConstByFlagPaperSection;
		this.prTchStuPaper = prTchStuPaper;
		this.enumConstByFlagActionUser = enumConstByFlagActionUser;
		this.actionDate = actionDate;
	}

	/** full constructor */
	public PrTchPaperContent(EnumConst enumConstByFlagPaperSection,
			PrTchStuPaper prTchStuPaper, EnumConst enumConstByFlagActionUser,
			String url, String note, Date actionDate) {
		this.enumConstByFlagPaperSection = enumConstByFlagPaperSection;
		this.prTchStuPaper = prTchStuPaper;
		this.enumConstByFlagActionUser = enumConstByFlagActionUser;
		this.url = url;
		this.note = note;
		this.actionDate = actionDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagPaperSection() {
		return this.enumConstByFlagPaperSection;
	}

	public void setEnumConstByFlagPaperSection(
			EnumConst enumConstByFlagPaperSection) {
		this.enumConstByFlagPaperSection = enumConstByFlagPaperSection;
	}

	public PrTchStuPaper getPrTchStuPaper() {
		return this.prTchStuPaper;
	}

	public void setPrTchStuPaper(PrTchStuPaper prTchStuPaper) {
		this.prTchStuPaper = prTchStuPaper;
	}

	public EnumConst getEnumConstByFlagActionUser() {
		return this.enumConstByFlagActionUser;
	}

	public void setEnumConstByFlagActionUser(EnumConst enumConstByFlagActionUser) {
		this.enumConstByFlagActionUser = enumConstByFlagActionUser;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

}