package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PrVoteSuggest generated by MyEclipse Persistence Tools
 */

public class PrVoteSuggest extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private EnumConst enumConstByFlagBak;
	private EnumConst enumConstByFlagCheck;
	private PeVotePaper peVotePaper;
	private String ip;
	private Date foundDate;
	private String note;

	// Constructors

	/** default constructor */
	public PrVoteSuggest() {
	}

	/** full constructor */
	public PrVoteSuggest(EnumConst enumConstByFlagBak,
			EnumConst enumConstByFlagCheck, PeVotePaper peVotePaper, String ip,
			Date foundDate, String note) {
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.enumConstByFlagCheck = enumConstByFlagCheck;
		this.peVotePaper = peVotePaper;
		this.ip = ip;
		this.foundDate = foundDate;
		this.note = note;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public EnumConst getEnumConstByFlagCheck() {
		return this.enumConstByFlagCheck;
	}

	public void setEnumConstByFlagCheck(EnumConst enumConstByFlagCheck) {
		this.enumConstByFlagCheck = enumConstByFlagCheck;
	}

	public PeVotePaper getPeVotePaper() {
		return this.peVotePaper;
	}

	public void setPeVotePaper(PeVotePaper peVotePaper) {
		this.peVotePaper = peVotePaper;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getFoundDate() {
		return this.foundDate;
	}

	public void setFoundDate(Date foundDate) {
		this.foundDate = foundDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}