package com.whaty.platform.entity.bean;

import java.util.Date;

/**
 * PrVoteRecord generated by MyEclipse Persistence Tools
 */

public class PrVoteRecord extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private PeVotePaper peVotePaper;
	private String ip;
	private String userSession;
	private Date voteDate;
	private String ssoId;

	// Constructors

	/** default constructor */
	public PrVoteRecord() {
	}

	/** full constructor */
	public PrVoteRecord(PeVotePaper peVotePaper, String ip, String userSession,
			Date voteDate) {
		this.peVotePaper = peVotePaper;
		this.ip = ip;
		this.userSession = userSession;
		this.voteDate = voteDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public PeVotePaper getPeVotePaper() {
		return this.peVotePaper;
	}

	public void setPeVotePaper(PeVotePaper peVotePaper) {
		this.peVotePaper = peVotePaper;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getUserSession() {
		return this.userSession;
	}

	public void setUserSession(String userSession) {
		this.userSession = userSession;
	}

	public Date getVoteDate() {
		return this.voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

	public String getSsoId() {
		return ssoId;
	}

	public void setSsoId(String ssoId) {
		this.ssoId = ssoId;
	}



}