package com.whaty.platform.entity.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrVoteQuestion generated by MyEclipse Persistence Tools
 */

public class PrVoteQuestion extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields

	private String id;
	private EnumConst enumConstByFlagBak;
	private EnumConst enumConstByFlagQuestionType;
	private PeVotePaper peVotePaper;
	private String questionNote;
	private Long itemNum;
	private Long totalItemResult;//总票数
	private String item1;
	private Long itemResult1;
	private Long itemScore1;//分值
	private String item2;
	private Long itemResult2;
	private Long itemScore2;
	private String item3;
	private Long itemResult3;
	private Long itemScore3;
	private String item4;
	private Long itemResult4;
	private Long itemScore4;
	private String item5;
	private Long itemResult5;
	private Long itemScore5;
	private String item6;
	private Long itemResult6;  
	private Long itemScore6;
	private String item7;
	private Long itemResult7;
	private Long itemScore7;
	private String item8;
	private Long itemResult8;
	private Long itemScore8;
	private String item9;
	private Long itemResult9;
	private Long itemScore9;
	private String item10;
	private Long itemResult10;
	private Long itemScore10;
	private String item11;
	private Long itemResult11;
	private Long itemScore11;
	private String item12;
	private Long itemResult12;
	private Long itemScore12;
	private String item13;
	private Long itemResult13;
	private Long itemScore13;
	private String item14;
	private Long itemResult14;
	private Long itemScore14;
	private String item15;
	private Long itemResult15;
	private Long itemScore15;
	private String weight;
	private Long score;
	private Long isRequirde;
	private Long isCustom;
	
	private Date createDate = new Date();
	private SsoUser ssoUser;
	private String itemContent;
	private Set<PrVoteSubQuestion> prVoteSubQuestions=new HashSet<PrVoteSubQuestion>(0);
	private Set<PrVoteUserQuestion> prVoteUserQuestions=new HashSet<PrVoteUserQuestion>(0);
	private String result;//辅助字段用于页面显示答案
	// Constructors
	private double avgScore;//辅助字段用于球平均分
    private Long questionOrder;
    private String fkParentId;
  

	public String getFkParentId() {
		return fkParentId;
	}

	public void setFkParentId(String fkParentId) {
		this.fkParentId = fkParentId;
	}

	public Long getQuestionOrder() {
		return questionOrder;
	}

	public void setQuestionOrder(Long questionOrder) {
		this.questionOrder = questionOrder;
	}

	public SsoUser getSsoUser() {
		return ssoUser;
	}

	public void setSsoUser(SsoUser ssoUser) {
		this.ssoUser = ssoUser;
	}

	public String getItemContent() {
		return itemContent;
	}

	public void setItemContent(String itemContent) {
		this.itemContent = itemContent;
	}

	public void setTotalItemResult(Long totalItemResult) {
		this.totalItemResult = totalItemResult;
	}

	/** default constructor */
	public PrVoteQuestion() {
	}

	/** full constructor */
	public PrVoteQuestion(EnumConst enumConstByFlagBak,
			EnumConst enumConstByFlagQuestionType, PeVotePaper peVotePaper,
			String questionNote, Long itemNum, String item1, Long itemResult1,
			String item2, Long itemResult2, String item3, Long itemResult3,
			String item4, Long itemResult4, String item5, Long itemResult5,
			String item6, Long itemResult6, String item7, Long itemResult7,
			String item8, Long itemResult8, String item9, Long itemResult9,
			String item10, Long itemResult10, String item11, Long itemResult11,
			String item12, Long itemResult12, String item13, Long itemResult13,
			String item14, Long itemResult14, String item15, Long itemResult15,Long questionOrder, Long isRequirde) {
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.enumConstByFlagQuestionType = enumConstByFlagQuestionType;
		this.peVotePaper = peVotePaper;
		this.questionNote = questionNote;
		this.itemNum = itemNum;
		this.item1 = item1;
		this.itemResult1 = itemResult1;
		this.item2 = item2;
		this.itemResult2 = itemResult2;
		this.item3 = item3;
		this.itemResult3 = itemResult3;
		this.item4 = item4;
		this.itemResult4 = itemResult4;
		this.item5 = item5;
		this.itemResult5 = itemResult5;
		this.item6 = item6;
		this.itemResult6 = itemResult6;
		this.item7 = item7;
		this.itemResult7 = itemResult7;
		this.item8 = item8;
		this.itemResult8 = itemResult8;
		this.item9 = item9;
		this.itemResult9 = itemResult9;
		this.item10 = item10;
		this.itemResult10 = itemResult10;
		this.item11 = item11;
		this.itemResult11 = itemResult11;
		this.item12 = item12;
		this.itemResult12 = itemResult12;
		this.item13 = item13;
		this.itemResult13 = itemResult13;
		this.item14 = item14;
		this.itemResult14 = itemResult14;
		this.item15 = item15;
		this.itemResult15 = itemResult15;
		this.questionOrder=questionOrder;
		this.isRequirde = isRequirde;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public EnumConst getEnumConstByFlagQuestionType() {
		return this.enumConstByFlagQuestionType;
	}

	public void setEnumConstByFlagQuestionType(
			EnumConst enumConstByFlagQuestionType) {
		this.enumConstByFlagQuestionType = enumConstByFlagQuestionType;
	}

	public PeVotePaper getPeVotePaper() {
		return this.peVotePaper;
	}

	public void setPeVotePaper(PeVotePaper peVotePaper) {
		this.peVotePaper = peVotePaper;
	}

	public String getQuestionNote() {
		return this.questionNote;
	}

	public void setQuestionNote(String questionNote) {
		this.questionNote = questionNote;
	}

	public Long getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(Long itemNum) {
		this.itemNum = itemNum;
	}

	public String getItem1() {
		return this.item1;
	}

	public void setItem1(String item1) {
		this.item1 = item1;
	}

	public Long getItemResult1() {
		return this.itemResult1;
	}

	public void setItemResult1(Long itemResult1) {
		this.itemResult1 = itemResult1;
	}

	public String getItem2() {
		return this.item2;
	}

	public void setItem2(String item2) {
		this.item2 = item2;
	}

	public Long getItemResult2() {
		return this.itemResult2;
	}

	public void setItemResult2(Long itemResult2) {
		this.itemResult2 = itemResult2;
	}

	public String getItem3() {
		return this.item3;
	}

	public void setItem3(String item3) {
		this.item3 = item3;
	}

	public Long getItemResult3() {
		return this.itemResult3;
	}

	public void setItemResult3(Long itemResult3) {
		this.itemResult3 = itemResult3;
	}

	public String getItem4() {
		return this.item4;
	}

	public void setItem4(String item4) {
		this.item4 = item4;
	}

	public Long getItemResult4() {
		return this.itemResult4;
	}

	public void setItemResult4(Long itemResult4) {
		this.itemResult4 = itemResult4;
	}

	public String getItem5() {
		return this.item5;
	}

	public void setItem5(String item5) {
		this.item5 = item5;
	}

	public Long getItemResult5() {
		return this.itemResult5;
	}

	public void setItemResult5(Long itemResult5) {
		this.itemResult5 = itemResult5;
	}

	public String getItem6() {
		return this.item6;
	}

	public void setItem6(String item6) {
		this.item6 = item6;
	}

	public Long getItemResult6() {
		return this.itemResult6;
	}

	public void setItemResult6(Long itemResult6) {
		this.itemResult6 = itemResult6;
	}

	public String getItem7() {
		return this.item7;
	}

	public void setItem7(String item7) {
		this.item7 = item7;
	}

	public Long getItemResult7() {
		return this.itemResult7;
	}

	public void setItemResult7(Long itemResult7) {
		this.itemResult7 = itemResult7;
	}

	public String getItem8() {
		return this.item8;
	}

	public void setItem8(String item8) {
		this.item8 = item8;
	}

	public Long getItemResult8() {
		return this.itemResult8;
	}

	public void setItemResult8(Long itemResult8) {
		this.itemResult8 = itemResult8;
	}

	public String getItem9() {
		return this.item9;
	}

	public void setItem9(String item9) {
		this.item9 = item9;
	}

	public Long getItemResult9() {
		return this.itemResult9;
	}

	public void setItemResult9(Long itemResult9) {
		this.itemResult9 = itemResult9;
	}

	public String getItem10() {
		return this.item10;
	}

	public void setItem10(String item10) {
		this.item10 = item10;
	}

	public Long getItemResult10() {
		return this.itemResult10;
	}

	public void setItemResult10(Long itemResult10) {
		this.itemResult10 = itemResult10;
	}

	public String getItem11() {
		return this.item11;
	}

	public void setItem11(String item11) {
		this.item11 = item11;
	}

	public Long getItemResult11() {
		return this.itemResult11;
	}

	public void setItemResult11(Long itemResult11) {
		this.itemResult11 = itemResult11;
	}

	public String getItem12() {
		return this.item12;
	}

	public void setItem12(String item12) {
		this.item12 = item12;
	}

	public Long getItemResult12() {
		return this.itemResult12;
	}

	public void setItemResult12(Long itemResult12) {
		this.itemResult12 = itemResult12;
	}

	public String getItem13() {
		return this.item13;
	}

	public void setItem13(String item13) {
		this.item13 = item13;
	}

	public Long getItemResult13() {
		return this.itemResult13;
	}

	public void setItemResult13(Long itemResult13) {
		this.itemResult13 = itemResult13;
	}

	public String getItem14() {
		return this.item14;
	}

	public void setItem14(String item14) {
		this.item14 = item14;
	}

	public Long getItemResult14() {
		return this.itemResult14;
	}

	public void setItemResult14(Long itemResult14) {
		this.itemResult14 = itemResult14;
	}

	public String getItem15() {
		return this.item15;
	}

	public void setItem15(String item15) {
		this.item15 = item15;
	}

	public Long getItemResult15() {
		return this.itemResult15;
	}

	public void setItemResult15(Long itemResult15) {
		this.itemResult15 = itemResult15;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	/*
	 * 计算总票数
	 * */
	public Long getTotalItemResult() {
		long num = 0L;
		long r1 = 0L;
		long r2 = 0L;
		long r3 = 0L;
		long r4 = 0L;
		long r5 = 0L;
		long r6 = 0L;
		long r7 = 0L;
		long r8 = 0L;
		long r9 = 0L;
		long r10 = 0L;
		long r11 = 0L;
		long r12 = 0L;
		long r13 = 0L;
		long r14 = 0L;
		long r15 = 0L;
		if (this.getItemResult1()!=null) {
			r1 = this.getItemResult1();
		}
		if (this.getItemResult2()!=null) {
			r2 = this.getItemResult2();
		}
		if (this.getItemResult3()!=null) {
			r3 = this.getItemResult3();
		}
		if (this.getItemResult4()!=null) {
			r4 = this.getItemResult4();
		}
		if (this.getItemResult5()!=null) {
			r5 = this.getItemResult5();
		}
		if (this.getItemResult6()!=null) {
			r6 = this.getItemResult6();
			
		}
		if (this.getItemResult7()!=null) {
			r7 = this.getItemResult7();
			
		}
		if (this.getItemResult8()!=null) {
			r8 = this.getItemResult8();
			
		}
		if (this.getItemResult9()!=null) {
			r9 = this.getItemResult9();
			
		}
		if (getItemResult10()!=null) {
			r10 = this.getItemResult10();
		}
		if (this.getItemResult11()!=null) {
			r11 = this.getItemResult11();
		}
		if (this.getItemResult12()!=null) {
			r12 = this.getItemResult12();
		}
		if (this.getItemResult13()!=null) {
			r13 = this.getItemResult13();
		}
		if (this.getItemResult14()!=null) {
			r14 = this.getItemResult14();
		}
		if (this.getItemResult15()!=null) {
			r15 = this.getItemResult15();
		}
		num = r1 + r2 + r3 + r4 + r5 + r6 + r7 + r8 + r9 + r10 + r11 + r12 + r13 + r14 + r15;
		return this.totalItemResult = num;
	}

	public Set<PrVoteSubQuestion> getPrVoteSubQuestions() {
		return prVoteSubQuestions;
	}

	public void setPrVoteSubQuestions(Set<PrVoteSubQuestion> prVoteSubQuestions) {
		this.prVoteSubQuestions = prVoteSubQuestions;
	}

	public Set<PrVoteUserQuestion> getPrVoteUserQuestions() {
		return prVoteUserQuestions;
	}

	public void setPrVoteUserQuestions(Set<PrVoteUserQuestion> prVoteUserQuestions) {
		this.prVoteUserQuestions = prVoteUserQuestions;
	}

	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public Long getItemScore1() {
		return itemScore1;
	}

	public void setItemScore1(Long itemScore1) {
		this.itemScore1 = itemScore1;
	}

	public Long getItemScore2() {
		return itemScore2;
	}

	public void setItemScore2(Long itemScore2) {
		this.itemScore2 = itemScore2;
	}

	public Long getItemScore3() {
		return itemScore3;
	}

	public void setItemScore3(Long itemScore3) {
		this.itemScore3 = itemScore3;
	}

	public Long getItemScore4() {
		return itemScore4;
	}

	public void setItemScore4(Long itemScore4) {
		this.itemScore4 = itemScore4;
	}

	public Long getItemScore5() {
		return itemScore5;
	}

	public void setItemScore5(Long itemScore5) {
		this.itemScore5 = itemScore5;
	}

	public Long getItemScore6() {
		return itemScore6;
	}

	public void setItemScore6(Long itemScore6) {
		this.itemScore6 = itemScore6;
	}

	public Long getItemScore7() {
		return itemScore7;
	}

	public void setItemScore7(Long itemScore7) {
		this.itemScore7 = itemScore7;
	}

	public Long getItemScore8() {
		return itemScore8;
	}

	public void setItemScore8(Long itemScore8) {
		this.itemScore8 = itemScore8;
	}

	public Long getItemScore9() {
		return itemScore9;
	}

	public void setItemScore9(Long itemScore9) {
		this.itemScore9 = itemScore9;
	}

	public Long getItemScore10() {
		return itemScore10;
	}

	public void setItemScore10(Long itemScore10) {
		this.itemScore10 = itemScore10;
	}

	public Long getItemScore11() {
		return itemScore11;
	}

	public void setItemScore11(Long itemScore11) {
		this.itemScore11 = itemScore11;
	}

	public Long getItemScore12() {
		return itemScore12;
	}

	public void setItemScore12(Long itemScore12) {
		this.itemScore12 = itemScore12;
	}

	public Long getItemScore13() {
		return itemScore13;
	}

	public void setItemScore13(Long itemScore13) {
		this.itemScore13 = itemScore13;
	}

	public Long getItemScore14() {
		return itemScore14;
	}

	public void setItemScore14(Long itemScore14) {
		this.itemScore14 = itemScore14;
	}

	public Long getItemScore15() {
		return itemScore15;
	}

	public void setItemScore15(Long itemScore15) {
		this.itemScore15 = itemScore15;
	}

	public String getWeight() {
		return weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public Long getScore() {
		return score;
	}

	public void setScore(Long score) {
		this.score = score;
	}

	public Long getIsRequirde() {
		return isRequirde;
	}

	public void setIsRequirde(Long isRequirde) {
		this.isRequirde = isRequirde;
	}

	public Long getIsCustom() {
		return isCustom;
	}

	public void setIsCustom(Long isCustom) {
		this.isCustom = isCustom;
	}

	public double getAvgScore() {
		return avgScore;
	}

	public void setAvgScore(double avgScore) {
		this.avgScore = avgScore;
	}


}