package com.whaty.platform.entity.bean;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.whaty.platform.database.oracle.MyResultSet;
import com.whaty.platform.database.oracle.dbpool;

/**
 * SsoUser generated by MyEclipse Persistence Tools
 */

public class SsoUser extends com.whaty.platform.entity.bean.AbstractBean
		implements java.io.Serializable {

	// Fields
	
	private String id;

	private EnumConst enumConstByFlagIsvalid;

	private EnumConst enumConstByFlagBak;

	private PePriRole pePriRole;

	private String loginId;

	private String password;
	
	private String passwordMd5;

	private String passwordBk;
	
	private Long loginNum;

	private Date lastLoginDate;

	private String lastLoginIp;
	
	private String sumAmount;
	
	private String amount;
	
	private String unUseAmount;
	
	private String balance;
	
	private Set prPriManagerSites = new HashSet(0);
	
	private Set prPriManagerMajors = new HashSet(0);

	private Set prPriManagerEdutypes = new HashSet(0);
	
	private Set prPriManagerGrades = new HashSet(0);
	
	private Set peBzzStudents=new HashSet(0);

	private Set peEnterpriseManager=new HashSet(0);
	
	private Set trainingCourseStudent=new HashSet(0);
	
	private Set prBzzPriManagerEnterprises=new HashSet(0);
	
	private Set assignRecord = new HashSet(0); 
	private Set prVoteSubQuestions=new HashSet(0);
	private Set prVoteUserQuestions=new HashSet(0);
	//private Set prBzzTchStuElectiveBack = new HashSet(0);
	// Constructors

	public Set getPrVoteSubQuestions() {
		return prVoteSubQuestions;
	}

	public void setPrVoteSubQuestions(Set prVoteSubQuestions) {
		this.prVoteSubQuestions = prVoteSubQuestions;
	}

	public Set getPrVoteUserQuestions() {
		return prVoteUserQuestions;
	}

	public void setPrVoteUserQuestions(Set prVoteUserQuestions) {
		this.prVoteUserQuestions = prVoteUserQuestions;
	}

	public void setUnUseAmount(String unUseAmount) {
		this.unUseAmount = unUseAmount;
	}

	/*public Set getPrBzzTchStuElectiveBack() {
		return prBzzTchStuElectiveBack;
	}

	public void setPrBzzTchStuElectiveBack(Set prBzzTchStuElectiveBack) {
		this.prBzzTchStuElectiveBack = prBzzTchStuElectiveBack;
	}
*/
	/** default constructor */
	public SsoUser() {
	}

	/** minimal constructor */
	public SsoUser(String loginId, String password) {
		this.loginId = loginId;
		this.password = password;
	}

	/** full constructor */
	public SsoUser(EnumConst enumConstByFlagIsvalid,
			EnumConst enumConstByFlagBak, PePriRole pePriRole, String loginId,
			String password, Long loginNum, Date lastLoginDate,
			String lastLoginIp,Set peBzzStudents,Set peEnterpriseManager,Set prBzzPriManagerEnterprises,
			Set assignRecord) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.pePriRole = pePriRole;
		this.loginId = loginId;
		this.password = password;
		this.loginNum = loginNum;
		this.lastLoginDate = lastLoginDate;
		this.lastLoginIp = lastLoginIp;
		this.peBzzStudents=peBzzStudents;
		this.peEnterpriseManager=peEnterpriseManager;
		this.prBzzPriManagerEnterprises=prBzzPriManagerEnterprises;
		this.assignRecord = assignRecord;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagIsvalid() {
		return this.enumConstByFlagIsvalid;
	}

	public void setEnumConstByFlagIsvalid(EnumConst enumConstByFlagIsvalid) {
		this.enumConstByFlagIsvalid = enumConstByFlagIsvalid;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public PePriRole getPePriRole() {
		return this.pePriRole;
	}

	public void setPePriRole(PePriRole pePriRole) {
		this.pePriRole = pePriRole;
	}

	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Long getLoginNum() {
		return this.loginNum;
	}

	public void setLoginNum(Long loginNum) {
		this.loginNum = loginNum;
	}

	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	public Set getPrPriManagerSites() {
		return prPriManagerSites;
	}

	public void setPrPriManagerSites(Set prPriManagerSites) {
		this.prPriManagerSites = prPriManagerSites;
	}

	public Set getPrPriManagerMajors() {
		return prPriManagerMajors;
	}

	public void setPrPriManagerMajors(Set prPriManagerMajors) {
		this.prPriManagerMajors = prPriManagerMajors;
	}

	public Set getPrPriManagerEdutypes() {
		return prPriManagerEdutypes;
	}

	public void setPrPriManagerEdutypes(Set prPriManagerEdutypes) {
		this.prPriManagerEdutypes = prPriManagerEdutypes;
	}

	public Set getPrPriManagerGrades() {
		return prPriManagerGrades;
	}

	public void setPrPriManagerGrades(Set prPriManagerGrades) {
		this.prPriManagerGrades = prPriManagerGrades;
	}
	
	public Set getPeBzzStudents(){
		return this.peBzzStudents;
	}
	
	public void setPeBzzStudents(Set peBzzStudents){
		this.peBzzStudents=peBzzStudents;
	}
	
	public Set getPeEnterpriseManager(){
		return this.peEnterpriseManager;
	}
	
	public void setPeEnterpriseManager(Set peEnterpriseManager){
		this.peEnterpriseManager=peEnterpriseManager;
	}

	public Set getTrainingCourseStudent() {
		return trainingCourseStudent;
	}

	public void setTrainingCourseStudent(Set trainingCourseStudent) {
		this.trainingCourseStudent = trainingCourseStudent;
	}

	public Set getPrBzzPriManagerEnterprises() {
		return prBzzPriManagerEnterprises;
	}

	public void setPrBzzPriManagerEnterprises(Set prBzzPriManagerEnterprises) {
		this.prBzzPriManagerEnterprises = prBzzPriManagerEnterprises;
	}

	public String getPasswordMd5() {
		return passwordMd5;
	}

	public void setPasswordMd5(String passwordMd5) {
		this.passwordMd5 = passwordMd5;
	}

	public String getPasswordBk() {
		return passwordBk;
	}

	public void setPasswordBk(String passwordBk) {
		this.passwordBk = passwordBk;
	}

	public String getSumAmount() {
		if(sumAmount == null)
			sumAmount="0";
		return sumAmount;
	}

	public void setSumAmount(String sumAmount) {
		this.sumAmount = sumAmount;
	}

	public String getAmount() {
		if(amount == null)
			amount="0";
		return amount;
	}

	public void setAmount(String amount) {
		this.amount = amount;
	}

	public Set getAssignRecord() {
		return assignRecord;
	}

	public void setAssignRecord(Set assignRecord) {
		this.assignRecord = assignRecord;
	}

	public String getBalance() {
		try {
			if(this.sumAmount==null)this.sumAmount="0";
			if(this.amount==null)this.amount="0";
			return String.valueOf(Double.parseDouble(this.sumAmount) - Double.parseDouble(this.amount));
		} catch (NumberFormatException e) {
			return "0.0";
		}
	}

	public void setBalance(String balance) {
		try {
			if(this.sumAmount==null)this.sumAmount="0";
			if(this.amount==null)this.amount="0";
			this.balance = String.valueOf(Double.parseDouble(this.sumAmount) - Double.parseDouble(this.amount));
		} catch (NumberFormatException e) {
			this.balance="0.0";
		}
		
	}

	public String getUnUseAmount() {
		BigDecimal b1 = new BigDecimal(this.getSumAmount());
		BigDecimal b2 = new BigDecimal(this.getAmount());
		BigDecimal b = b1.subtract(b2);;
		b.setScale(1, BigDecimal.ROUND_HALF_UP);
		return b.toString();
	}

	/**
	 * 获得集体管理员管理员自己和下属机构ID
	 * @return
	 */
	public String getSubEnterprisesStr(){
		String entStr = "";
		String sql = 
			"select distinct pe.id\n" +
			"  from pe_enterprise         pe,\n" + 
			"       pe_enterprise_manager pem,\n" + 
			"       pe_enterprise_manager pem1,\n" + 
			"       sso_user              su\n" + 
			" where (pem.fk_enterprise_id = pe.id or\n" + 
			"       pem.fk_enterprise_id = pe.fk_parent_id)\n" + 
			"   and pem1.fk_enterprise_id = pe.id\n" + 
			"   and pem.fk_sso_user_id = su.id\n" + 
			"   and su.login_id = '"+this.loginId+"'";
		dbpool db = new dbpool();
		MyResultSet rs = null;
		try {
			rs = db.executeQuery(sql);
			while(rs!=null && rs.next()){
				entStr += "'"+rs.getString(1)+"',";
			}
			if(entStr.length()>2){
				entStr = entStr.substring(0, entStr.length()-1);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			db.close(rs);
			db=null;
		}
		
		//entStr = entStr.substring(0, entStr.length()-1);
		return entStr;
	}
	
	/**
	 * 获得集体管理员管理员自己和下属机构管理员ssoID
	 * @return
	 */
	public String getSubManagersStr(){
		String entStr = "";
		String sql = 
			"select distinct pem1.login_id\n" +
			"  from pe_enterprise         pe,\n" + 
			"       pe_enterprise_manager pem,\n" + 
			"       pe_enterprise_manager pem1,\n" + 
			"       sso_user              su\n" + 
			" where (pem.fk_enterprise_id = pe.id or\n" + 
			"       pem.fk_enterprise_id = pe.fk_parent_id)\n" + 
			"   and pem1.fk_enterprise_id = pe.id\n" + 
			"   and pem.fk_sso_user_id = su.id\n" + 
			"   and su.login_id = '"+this.loginId+"'";
		dbpool db = new dbpool();
		MyResultSet rs = null;
		try {
			rs = db.executeQuery(sql);
			while(rs!=null && rs.next()){
				entStr += "'"+rs.getString(1)+"',";
			}
			if(entStr.length()>2){
				entStr = entStr.substring(0, entStr.length()-1);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			db.close(rs);
			db=null;
		}
		return entStr;
	}
}