package com.whaty.platform.entity.bean;

/**
 * SystemVariables generated by MyEclipse Persistence Tools
 */

public class SystemVariables extends
		com.whaty.platform.entity.bean.AbstractBean implements
		java.io.Serializable {

	// Fields

	private String id;

	private EnumConst enumConstByFlagBak;

	private EnumConst enumConstByFlagPlatformSection;

	private String name;

	private String value;

	private String pattern;

	// Constructors

	/** default constructor */
	public SystemVariables() {
	}

	/** minimal constructor */
	public SystemVariables(String name, String value, String pattern) {
		this.name = name;
		this.value = value;
		this.pattern = pattern;
	}

	/** full constructor */
	public SystemVariables(EnumConst enumConstByFlagBak,
			EnumConst enumConstByFlagPlatformSection, String name,
			String value, String pattern) {
		this.enumConstByFlagBak = enumConstByFlagBak;
		this.enumConstByFlagPlatformSection = enumConstByFlagPlatformSection;
		this.name = name;
		this.value = value;
		this.pattern = pattern;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public EnumConst getEnumConstByFlagBak() {
		return this.enumConstByFlagBak;
	}

	public void setEnumConstByFlagBak(EnumConst enumConstByFlagBak) {
		this.enumConstByFlagBak = enumConstByFlagBak;
	}

	public EnumConst getEnumConstByFlagPlatformSection() {
		return this.enumConstByFlagPlatformSection;
	}

	public void setEnumConstByFlagPlatformSection(
			EnumConst enumConstByFlagPlatformSection) {
		this.enumConstByFlagPlatformSection = enumConstByFlagPlatformSection;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

}